### ISSUE TITLE
Ability to rename a file

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1000]
Priority 8 (0	3	2	3)

A coordinator has noted that for admin purposes each church needs a unique code. Should this be entered wrongly by transcriber it has to be corrected. It would be useful to be able to do this online.

**Comment by edickens** [comment]
The reason for this (correct me if I'm wrong) is that it is useful in 
large reports to group all batches for a Place/Church together..

Perhaps, if the reports had a sort option on Place/Church this would not 
be needed.

**Comment by Captainkirkdawson** [comment]
There is no requirement from a system perspective. All batches link to their register and church no matter what their name. 
In FR1 coordinators needed a file naming structure to make links to churches since there was no ability within FR1 to so do. 
Having structured names in FR does not affect the system in any way except if there are errors introduced as a result of making changes to names

**Comment by Sherlock21** [comment]
Kirk's comment above is of course very true.

But here are plenty of other people in the operation who live by file name inside and outside of the Online database and they need the file names to be in some ready- understandable structure.

I fully support the request by the CC concerned.

**Comment by Captainkirkdawson** [comment]
This story has a large size because the file name is an integral part of the system. Providing an ability to change it has significant likelihood of causing unintended consequences which need to be investigated

**Comment by SteveBiggs** [comment]
This refers to the uploaded file, for example; SSXSBEBA.CSV.  which perhaps "should" be SSXSBABA because the transcriber used the wrong file code on creation of the file. Functionally it makes no difference what the file is called but it is untidy from an admin point of view and there could be a practical problem if the transcriber subsequently creates a file for the place/church that really does use the file code SBE, it would potentially mean they had two files with the same name but for different churches.

I agree with @edickens that this is relatively rare and the CC can download the file, rename it, upload it and then delete the wrongly named file.

However, if we ever achieve the goal of fully online transcribing, then online renaming would be required.

**Comment by Captainkirkdawson** [comment]
In view of comments propose to close
