### ISSUE TITLE
Prepare images for RAP and allocation

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1023]

**Comment by edickens** [comment]
Now that Ben has decided on the structure, can I now start preparing the images for processing in FR?  There could be as many as 5Tb of data to sort out.  Every image will need copying into  the new structure so that it is linked to a County/Place/Church/Register Type and be a "Set" to cover a range of years.  Hopefully the filenames will not need changing.  They presently look like ABD-Aberdeen-BA-1759-1770-1-001.jpg

This is a job that I would like to start now because it will take time and these images are necessary for the RAP and GAP to work.  Also,  CCs may have to identify which images match which transcription so that we know not to transcribe them again, however I'm hoping that the RAP will do this matching, particularly if I can associate the images with an existing Church/Register Type and year range.  And it is this associating of images which will take the time, particularly if the year range of the batch of images is not easily identified, unlike the example above.  So an Image upload screen is needed which will also accept the images presently on  images.freereg.org.uk/freereg/regimages/.uploads which can then be used for the images to be copied across.
E

**Comment by edickens** [comment]
I have started going through all the images to ensure that the filenames include the year range and record details.  I have got as far as CAM and this has raised some facts.
I now suggest that the information we need to hold in the Set Header, which identifies a group of images, should contain the following, or these links:-
County (Pick list from existing)
Place (Pick list from existing)
Church (Pick list from existing or create a new one)
Register Type (Pick list from existing)
Data Type (Pick list of BA, MA, BU, PR (Parish Register of mixed BA, MA, BU), OD (Other Data such as the history of the Church, list of vicars, Family names))
Year start (Enter)
Year end (Enter)
Note (Enter for such things as Donors name, Copy, Rescan etc.)
Quality of image (Pick List to match the field in the UserID.  Default "Straight Forward Form")
Image filenames (Browse for filenames and be able to use Shift+Click to select a range.)
Note: Files may be jpg, tif, pdf, doc, docx, xls, html, and the option to enter txt which could be a URL link to another website.  So if we are going to provide the means to view these images, then these file types must be viewable.

**Comment by Captainkirkdawson** [comment]
As currently conceived and being programmed. It is expected that initial runs will not create anything but produce logs for review

The image server folder place, church and register names must match the FR place, church and register names for there to be a match; just like a csv file has to match.

The image names themselves do not get matched so do not need that information. 

Anything in that folder is assumed to belong to the location specified by the folder. 

Clearly record type and date range on the image name will be of use to the coordinator

Error conditions or Missing components of a location.

a) The place must already exist on FR and IS.

I do not like the following b) and c) but

b) missing churches

If there is  a single church on FR and there is no church on the IS we will link to that church on FR

If there is no church on FR and there is a church on the IS we will create the church on FR

If there are multiple churches on FR and no church on IS  we do not process the images and ask for a church name to be set upon the IS (folder only)

If there is no church on either we create a church called Tobe Determined. 

c) missing register type

If there is  a single church register on FR and there is no church register on the IS we will link to that church register on FR

If there is no church register on FR and there is a church register on the IS we will create the church register on FR

If there are multiple churches registers on FR and no church register on IS  we do not process the images and ask for a church register name to be set upon the IS (folder only

**Comment by Captainkirkdawson** [comment]
Initial tests have shown issues with missing churches and inconsistent register types.

**Comment by edickens** [comment]
Hi Kirk,

This is done, to the best of my ability. and ready for your selection program.

E

**Comment by Captainkirkdawson** [comment]
That is understood. The reason for it being back here is that we need to process it into the collection and that we need a story that is appropriate to hang the work on.

**Comment by edickens** [comment]
The idea is that if there is no Church on the IS, then the Church on FR is used, and there should be just one.  I have added a Church to the IS if there is more than one on FR, and I have added a Church on FR if there was none.  So you should not need to use your idea of setting up a "Dedication To be determined" Church.

**Comment by Captainkirkdawson** [comment]
On Jan 24 just before we put a hold on this work EricD proposed.
To this end I have been tidying up the folder names in the IS.  It is not necessary for the image filenames to match as FR will just contain a link to the filename.  But it does mean that the IS folder names must have a standard format which is:-
In this order:-
Place name, which can contain hyphens and is not case sensitive
Church name, which is preceded by an Underscore.  This does not need to be entered if there is only one Church in a Place.  The indexing program will select that Church.  Church names must not contain a hyphen.  A Church names must be entered if there is more than one Church in a Place so that the indexing program knows which one to choose.
Comment, which is preceded by a hyphen and can contain hyphens.
Register Type, which is the two character code in the FR Help and is preceded by a space and is the last entry in the IS folder, and is mandatory.

Please note that it is only essential to have a Church name in FR if there are images in the IS, even if they have not yet been transcribed.  When I have found this situation I have created a Church called "Parish Church" with a denomination of "Unknown", if there is no indication of this information in the images.  You can change this information when transcribing starts, but do not do it now as it will then not match with the IS.  You will now  which these are because in the list of "All Place" they will show with no Register Type and no Last uploaded date.

There are a lot of Register Types in FR called "Unspecified" which were created when transcriptions were brought across from FR1.  I have entered a Register Type in the IS from information in the images, but this will not match with FR.  The indexing program will create the Register Type as entered in the IS and you can tidy this up in FR at a later date.  It is not essential that they match at this time.

Please check what I have done using getscan.pl and then let me know if I need to make any changes to the folder names in the IS.

When the indexing is done, there will be a report of mismatches and other information.  Also, eventually, you will have a regular report which will show you where there are images but no transcription. This will happen with the "Unspecified" Register Types as they will not match the Register Type in the IS folder name, but as they will be for the same Place and Church, this is not a serious problem.

It is not necessary to enter Church names at this time for Places where we do not have images on the IS.

There are a lot of transcriptions where we do not have the images on the IS.  This is not a problem at this time.  When version 1.5 is complete you will be able to enter information as to where to find these images and they will not need to be on the IS.  This is very useful information for checking images when someone queries a transcription and also, if they have not been transcribed to manage what still have to be done.  If you do have images that you would like on the IS, do not get them uploaded to the IS until we have done the linking and indexing.

**Comment by Captainkirkdawson** [comment]
I commented

It is significantly different from the original standard that you proposed and which we tested. That standard still had issues for which we had not reached consensus on how to handle.

We have not even agreed on the next steps to be taken after the 2 test cases.

The use of hyphens within hyphens as comments and hyphens within Place names has NOT been tested.

**Comment by edickens** [comment]
Kirk,
The hyphens within hyphens is quite rare.  At least 99% of the places conform to what you have done.  I suggest that in your processing report you just use "Cannot process" for anything that does not fit and I will sort it out later.  We will need a routine for entering new images and I can use that to enter those which you reject.
Also, nearly all images have been transcribed so if you reject anything, it will not upset anybody's work.
E

**Comment by edickens** [comment]
I will have some more images to upload to the server soon.  Will this affect what Bev is doing or should I wait?  I'd prefer to upload them if I can.

**Comment by Captainkirkdawson** [comment]
Please upload.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
I have now uploaded all that is needed.  OK for Bev to check again.

**Comment by Captainkirkdawson** [comment]
Bev is currently unavailable

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Currently Bev is working to create a loaded test dataset of pages and sources for SSX against which see can develop and test the UIs

**Comment by Captainkirkdawson** [comment]
We have got to the point where we can process the information from the image server into the database. The next step is to write the UIs to display and manipulate the information.
