### ISSUE TITLE
Display emendations to researchers

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1040]
@Sherlock21 has requested that we create a way for researchers to know what emendations are being applied.  Since these live in the `emendation_rules` table, we could just create a user-visible list of them under `freereg_contents`.  I suspect this would be an excellent project for @israelriibeiro

**Comment by israelriibeiro** [comment]
Hi, Ben. 
There is only one thing for this to be ok. Where should i put a button or link to get this url ( /emendation_rules ) [Commit](https://github.com/FreeUKGen/MyopicVicar/commit/299d1aefc8fef2c4a12708e74261d19fb1aed176) 

Execution example:

![emendation](https://cloud.githubusercontent.com/assets/4265692/21956430/a19dbc34-da67-11e6-8516-a195bdf166fb.gif)

**Comment by benwbrum** [comment]
HI @israelriibeiro.  Would it be possible to change this to a more tabular fomat, in which the table headings are "Abbreviation" (currently `Original`), "Name" (currently `Replacement`), Gender, and there are three columns with a row for each emendation rule?

**Comment by benwbrum** [comment]
I'm also interested in @Sherlock21's take on this, as this was his request originally.

**Comment by Captainkirkdawson** [comment]
The initial code is integrated into master and deployed on test3.

After sort correction looks good

**Comment by Captainkirkdawson** [comment]
@israelriibeiro  Would like to see us add a display  of the specific forename emendations for the person searched for in the display About this query https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_queries/about.html.erb#L1-L120

Also could you make the emendation_rules page available to non logged in people by adding a skip to the emendations controller see how it was done in 

https://github.com/FreeUKGen/MyopicVicar/blob/master/app/controllers/userid_details_controller.rb#L3

@AlOneill have you looked at the About this query for accessibility?

**Comment by AlOneill** [comment]
@israelriibeiro 
Please replace first two paras of introductory text with this single para:
`<p>This page lists forenames (first names) together with the variations, abbreviations, and Latin forms that will be found automatically for each forename in a search.</p>`

The third para to remain as is. Thank you.

**Comment by AlOneill** [comment]
@Captainkirkdawson 
'About this query' has one major issue (line length too long) plus a few minors (mostly visual).

Had forgotten all about it! Will take a close look at erb.

**Comment by Sherlock21** [comment]
I was asked by Kirk to comment on an earlier version by email.
I made two comments: 1) about the table not being in alphabetical order. - this has now been addressed.
2) it is hard to read the options per Name because the comma separators get mixed with the colon and semi colons which are often part of the abbreviation. and even on my wide screen Desktop Mac, its difficult to read the font.

SO example: display the actual test of the abbreviation in larger, bold fine.
and the comma separator in feint. This might make a much better option for distinguishing in this case.

If you are in doubt as to exactly what I am suggesting: the bold font which is displayed in this forum as: @Captainkirkdawson in the box above this one - use as the actual abbreviation,  and the normal display that I am writing in, in my own comment box here, as the separator comma.

**Comment by israelriibeiro** [comment]
I'll take look into this things that was mention here, tonight.

**Comment by israelriibeiro** [comment]
@AlOneill , add that: [commit](https://github.com/FreeUKGen/MyopicVicar/commit/9599e6626d337416e38d6844474e8adc25e8a9dd)

@Captainkirkdawson ,  you want to open this page to everyone?  And you want to add path in this view? [about.html.erb]( https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_queries/about.html.erb#L1-L120). It that it?!

**Comment by Captainkirkdawson** [comment]
That Is correct the page does not require login protection

Yes I want to extract the emendations for the specific forename that was in the search (if there was one) and have them displayed as part of the about, You may need to work with @AlOneill on the formatting of that section in the document,

I do not want to display the whole page just for the search forename entered

@AlOneill also needs to access your full page from the help materials which is why it needs to be publicly available

The controller will have "protected" actions like new and edit sometime down the road,  So you only need to open up the index

**Comment by AlOneill** [comment]
Thank you.
Sorry, Israel, but have only now remembered that we are using a scoped style element -- many browsers do not support/honour the scoping, so we need to use a class to make sure styling is not messed up on other parts of page.

Please change line 4 to:
`nav.simpleIndex a { display: inline-block; padding: 5px; width: 2.5rem; }`
and line 10 to:
`<nav class="simpleIndex">`

**Comment by israelriibeiro** [comment]
@AlOneill and @Captainkirkdawson , [commit](https://github.com/FreeUKGen/MyopicVicar/compare/correct_paragraph) . Now we have to check  where this link will be on about.html.erb.

**Comment by Sherlock21** [comment]
One fundamental thing about access to this table:

If you put it into Researcher's free access, then fine for them.
BUT for Members, it actually means having to LOG OUT, to get the public researcher access, just to look something up in this list, then log back into the Member session.

Not good at all.

So please have it in both camps so we (CC's & Management) can just simply use it. - when we get the means of updating the table, it will need to be on our side of the fence anyway.

**Comment by edickens** [comment]
Hi EricB,

Are you sure you need to log out for search access?  The Search Action 
is there, or you can click the FreeREG logo to get to the homepage.

E

Eric J Dickens

**Comment by Sherlock21** [comment]
If I log in to do something, and then decide I need a bit of Help on the Emendations Table,
the Help button is where I would intuitively go.
 On the help menu, I see nothing that indicates help for Transcribers let alone the specific topic.
In the text, there is a tiny green link to Information for Transcribers but why is it not a big link in the R/H column under I:information for Coordinators?
Taking the text link to Information for Transcribers, I don't go anywhere where it looks like data and Emendations of first names not surnames [ like it is If I start without being logged in as a Member.]

SO - log out and start again. 
Don't log in, and use Help.

Now, the first page that I land on,from the HELP button,  there in the RH column is the heading that's exactly where I need to be.
SO why is it not there when I am logged in as  a Member?

**Comment by Captainkirkdawson** [comment]
What EricB may be talking about is really nothing to do with Emendations, it is a question of access to the main help when logged in as a Member. That is a general issue that has been there since day 1, Separate story raised. 
The issue of open access to the page is a fundamental requirement if researchers are to be able to display the page.

**Comment by Sherlock21** [comment]
Yes, indeed Kirk.
 Sorry that I put my comment in with other things.

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , did you check what i did already? @AlOneill , where should i put the link in about.html.erb?!

**Comment by AlOneill** [comment]
@israelriibeiro @Captainkirkdawson 
I am a little confused: it looks like lines 32-36 are there to pull in a list of the emendations for the forename being searched for (if applicable), but this does not happen on test3. Why not?

Some of the lists, e.g. for Elizabeth, are very long. We may need to give them a paragraph of their own!

(I am assuming that the idea is to pull the emendations in, rather than link to the full emendations page, yes?)

**Comment by Captainkirkdawson** [comment]
@israelriibeiro public access is fine TY

@AlOneill will have a look to see what is there.

Your assumption is correct. We just list them for the forename in the search. As you say paragraph may be needed

**Comment by Captainkirkdawson** [comment]
Never ever looked at that code its been there since day 1. @israelriibeiro  please have a look at it. It seems to me the issue may be in the upcase of the forename so there is no match
@AlOneill do we have a link in the help page to the emendations?

**Comment by AlOneill** [comment]
@Captainkirkdawson 
No link yet -- do not know url for researcher access (only the url that requires login) -- perhaps I missed it?

**Comment by Captainkirkdawson** [comment]
@AlOneill   Link remains the same http://www.freereg.org.uk/emendation_rules

**Comment by AlOneill** [comment]
Link now in place from 'Help' page. (Will re-work para when muse strikes ...)

Noticed that `<% title "Forename abbreviations" %>` (for browser tab) is missing.

**Comment by israelriibeiro** [comment]
@Captainkirkdawson , i think it's correct already:

The only thing that is upcase here is the "name" of the link. The id is downcase.
[Link to letter](https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/emendation_rules/index.html.erb#L12)
The same here, the id is downcase.
[Letter](https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/emendation_rules/index.html.erb#L19)

I'll take a look into it, @AlOneill

**Comment by Captainkirkdawson** [comment]
@israelriibeiro the problem is https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/search_queries/about.html.erb#L32-L36
There the selection is using an upcase on the first name so it will never select anyone as all the records are in lowercase. The selection should be  for a down cased first name
While you are making changing the use of a selection like this in  a view is poor coding practice (not your writing I know) we should move the selection to the controller and pass a variable containing the emendations  to the view

**Comment by richpomfret** [comment]
Reopened - minor addition needed (title to page needs adding).

**Comment by Captainkirkdawson** [comment]
? Unsure of comment

**Comment by israelriibeiro** [comment]
I have to add <% title "Forename abbreviations" %>. I'll do it this weekend.
