### ISSUE TITLE
Increase the maximum number of search results

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1043]
When FR2 was initially launched we imposed a maximum number of search results to be retrieved and displayed. This was an attempt to limit the response time that a user would experience when conducting a search. The number was selected by Kirk on the basis of reasonableness ie how many results could be meaningfully be considered by a researcher while at the same time limiting the network transfer time and the browser table construction time.. He selected 250
There have been periodic requests for an increase.
Given that user devices are generally faster, browsers have improved and network connection speeds have increased is it now time to increase the limit.
Is a limit needed? Yes. Imagine the number of SMITHs in some counties. There is no way we should try to provide and display a table of 100,000 entries.
What is a reasonable limit?
.

**Comment by edickens** [comment]
I still think 250.  Not because of the processing time, but the 
researcher is going to have to read through all the 250, and perhaps 
look at the Detail, to find the one they want.  To increase it is just 
making this job even more difficult.  In fact I think you may find that 
after they have looked at the first page or two, they will decide to 
refine the search.  And that is what we should encourage them to do.

Taking the example of the Smiths, yes, there are a lot.  And we offer 
the ability to search the whole country.  So all that is needed is to 
put in a narrow year range, or select a few Counties.

But the problem could be with BU.  The researcher may know when they 
died, but not where they are buried.  So they need the whole country 
search.  But they should know the firstname, or at least the first few 
letters if there could be abbreviation problems, and they should know 
the year.  So they can limit their search.

Asking for more per search is just being lazy and I don't think they 
read them all, not even with the present 250.

E

**Comment by Captainkirkdawson** [comment]
Personally I agree with you!!
Should be a scrum decision

**Comment by edickens** [comment]
I have not heard any more complaints about this.  I still agree with what said in December 2016.
