### ISSUE TITLE
Main help links in other help pages

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1084]
Currently we tailor the Help to the role of a person,  Researchers see the main helpl transcribers the Transcriber help, managers the coordinators help. The coordinators help has a link to the transcribers help.
Requirement is for a clear link to the Main Help in the landing pages for transcriber and coordinator help

**Comment by AlOneill** [comment]
"Other Help" sub-menu now available on both Transcriber Information and Coordinator Information pages. (There are also selected links in the page text.)

The new sub-menu is the third sub-menu, below the "On this page" and section Help menus, if you see what I mean. Does this work for people?

**Comment by PatReynolds** [comment]
Which website, please - I can't see anything on test2, test3 or live.

**Comment by AlOneill** [comment]
@PatReynolds  Production, e.g. https://www.freereg.org.uk/cms/information-for-coordinators

The Coords version is the 2nd sub-menu — should be visible on the right and 'above the fold' in a lap/desk sized window; the Transcriber equivalent is in a similar relative position, but 'below the fold' because the other sub-menus are longer.

![Information_for_Coordinators___FreeReg.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5609b1960367a9170003b106/125516c66e82c728ace21e0d46c19a9c2c908ea89be0b04d9b5bff861665287c3b00aa257191ec3aac7d443e291d1bf9230d0856e0ebc969f9ec6923ce4e01ffd46e0a27976818a5bc8a1fb853bf20894f85b7bfdf4cc3be2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee14851ac17376be673357b55d9.png)

**Comment by PatReynolds** [comment]
Belated thanks.  Can this be closed?
