### ISSUE TITLE
Empty "FreeReg update processing reports" are being sent out.

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1096]

**Comment by edickens** [comment]
I am receiving these report a number of times every day.  For example at 07.22  on 08/02/2017.
This is not a problem to me, but it could be a problem elsewhere.  E

**Comment by Sherlock21** [comment]
Instead of sending these out as they arise, can you collect together and send in a daily bundle please? Its too disruptive - even when there will be content, that invariable won't need action.

Will this listing contain those batches/files that are too big for the normal uploader's limit?  If not in here, how will they come to me please?
