### ISSUE TITLE
'Transcriptions' tab link is down

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1101]
http://www.freereg.org.uk/freereg_contents/new is reporting an error.

**Comment by Captainkirkdawson** [comment]
Missed a location for a change. Fix is percolating through the servers at this time

**Comment by Sherlock21** [comment]
This story id #1101
There is also another story #1101 (111768646 Data Problem (Andy Phillips) #1101 is also #1101.
Please get rid of THIS story or renumber it.

 The Andy Phillips  story has much much more content, and is a more significant a job.

**Comment by Captainkirkdawson** [comment]
This is a closed story

**Comment by Sherlock21** [comment]
My point was that there are 2 totally different records with the same number #1101.

it matters not whether one is closed or not.  A search by number finds the wrong one ( i.e. this one)

**Comment by SteveBiggs** [comment]
Eric, I'm afraid that appears to be the way github works. Closed issues' numbers get reassigned to later ones when they are opened.  @richpomfret should be able to explain it better than me.

**Comment by smrr723** [comment]
I don't think Issue numbers get reassigned like that - the problem here is that we have multiple repositories dealing with FreeREG which results in duplication of issue numbers, i.e. Myopicvicar - https://github.com/FreeUKGen/MyopicVicar/issues, and FreeREGProductIssues - https://github.com/FreeUKGen/FreeUKRegProductIssues/issues, and now also FreeREGNonProductIssues?

Quite confusing when these are all included in the same waffle board - we could just use labels to separate these issues and use the one main repo - Myopicvicar.

**Comment by SteveBiggs** [comment]
Thanks Scott. I see what you mean. When someone 'Reports a Problem' on the FR website, it gets (automatically) raised as a FreeUKRegProductIssue, but when an issue is raised directly (manually) on the waffle board, it is under Myopicvicar. As you say, confusing!
