### ISSUE TITLE
Researcher can leave Reviews

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1195]
Link to bouquet page in footer

Economic 6, urgency 3, streategic importance 4, cost 5 P18

**Comment by Captainkirkdawson** [comment]
Interesting. We used to have such a page and display. Your predecessor had us remove it.

**Comment by DeniseColbert** [comment]
Moving to Needs Review for checking of the form: https://forms.gle/nU65K3MCFWaAzAvw9

**Comment by Captainkirkdawson** [comment]
Looks fine to me

**Comment by AlOneill** [comment]
Looking good. I have a few thoughts:

**In the opening para**, should that be 'testimonial' (singular) rather than 'testimonials' (plural)?

Maybe there is a better word or phrase than testimonial? — it is rather formal (or associated with matches for long-serving or retiring football players!).

"… or thank the FreeREG volunteers for their _hard work and dedication_?" (emphasis mine) loads the question somewhat — _we_ know how much work our volunteers do, but … we could get a bunch of reviews that simply repeat that phrase. What would we do with a review that included a complaint? We could be accused of saying, "Be positive or don't bother" — in which case we would _not_ be asking for a review in the way that word is used today, especially on the net. 

**In the first label**, that should be a horizontal ellipsis (…) rather than 3 full stops.

If that is the actual form to be used (rather than it being translated to an app page), then tabbing works OK but focus/ hover is not clearly visible on the submit button. Also, screen-reader users would probably not get the 'required' information (asterisks are frequently not reported).

**Comment by PatReynolds** [comment]
@DeniseColbert to revise

**Comment by DeniseColbert** [comment]
Form amended apart from this:

> "… or thank the FreeREG volunteers for their hard work and dedication?" (emphasis mine) loads the question somewhat — we know how much work our volunteers do, but … we could get a bunch of reviews that simply repeat that phrase. What would we do with a review that included a complaint? We could be accused of saying, "Be positive or don't bother" — in which case we would not be asking for a review in the way that word is used today, especially on the net.

This issue has arisen I think because we changed the word from "Bouquets" and/or "Thank You" (the latter is what this work is due to replace) to "Reviews". 

For decision: Are we inviting ALL reviews - good _and_ bad? If so, will we _publish_ the bad ones? If not, should we rethink the word "Reviews"?

**Comment by DeniseColbert** [comment]
@DeniseColbert to note on the form/page that complaints/problems should be sent in via the Contact form. Also, we won't publish everything submitted. We may change your message slightly e.g. to remove personal details.

**Comment by DeniseColbert** [comment]
Also blocked by page size issue (slack) @Vino-S

**Comment by DeniseColbert** [comment]
I don't think it worked @Vino-S ?

![image](https://user-images.githubusercontent.com/19173257/116418065-b5b0e680-a833-11eb-86d5-3e2b600e0365.png)

**Comment by PatReynolds** [comment]
@Vino-S to see why the page is not saving.

**Comment by Vino-S** [comment]
@DeniseColbert updated the page size  in test3

**Comment by DeniseColbert** [comment]
Still not working @Vino-S :(

**Comment by Vino-S** [comment]
The issue here  about some text is in bad format (utf encoding) not about page length

**Comment by PatReynolds** [comment]
Can you fix the text, @Vino-S . Also (silly question!) where is the 'leave a review' button?

**Comment by PatReynolds** [comment]
Further work needs doing: block quotes and block quote styling, and adding the form.

**Comment by DeniseColbert** [comment]
Form added, via embed code. It shows in the preview box, but doesn't seem to work on preview page. This is a similar issue to the issue I'm seeing trying to embed YouTube videos in FreeCEN Refinery. Will raise this on Systemwide, but ready for Alison to look at HTML/blockquote markup.

**Comment by DeniseColbert** [comment]
Form added, via embed code. It shows in the preview box, but doesn't seem to work on preview page. This is a similar issue to the issue I'm seeing trying to embed YouTube videos in FreeCEN Refinery. Will raise this on Systemwide, but ready for @AlOneill to look at HTML/blockquote markup.

**Comment by AlOneill** [comment]
Page now marked up as it could be, depending on our style decisions.

The markup using `blockquote` (the most obvious element) is inevitably a little involved because:
1.  our markup needs to be valid, for the sake of screen-reader users, and so the attribution (author credit) should be in a separate element to the blockquote itself
2.  the attribution and the blockquote need to be grouped together, which entails using a container for each pair
3.  if we wish to use quotation marks, then `p` elements are necessary to ensure correct use where there is more than one paragraph — which means `p` elements are necessary for all, irrespective of number of paragraphs in the quote

**Comment by AlOneill** [comment]
Although the form is not working on t3, I could see it when working offline:
* there is an unpaired closing bracket at the end of the last paragraph in the preamble
* suggest that "Complaints/problems" would be better as "complaints and problems" — lower-case c and a word instead of a forward slash which a screen-reader user will probably not be aware of

**Comment by DeniseColbert** [comment]
Form issues: fixed. Form not showing - still a problem.

Are we leaving them 'as sent'? Or do they need tidying up?

**Comment by PatReynolds** [comment]
Discision: leave as-is, but do not display those that are not coherent.

**Comment by PatReynolds** [comment]
@DeniseColbert to review and choose which quote style to go with.

Incoherent ones to be identified in Documentation meeting.

**Comment by DeniseColbert** [comment]
- Combine the two Felmingham quotes into one
-

**Comment by DeniseColbert** [comment]
Original document: https://docs.google.com/document/d/1BfmJptksNDK0OLmPqx3KR-LUTXdcAh6A0DNOqQ2I_lA/edit?usp=sharing

**Comment by AlOneill** [comment]
Have stitched individual reviews back together as per the original document. Also made changes as decided in meeting and listed 2 comments above.

Will update styling when requested changes (System-wide) have been reviewed.

**Comment by DeniseColbert** [comment]
@AlOneill I think this is ready to deploy? https://test3.freereg.org.uk/cms/refinery/pages/draft-about-your-reviews/edit

**Comment by AlOneill** [comment]
@DeniseColbert 

**No**, this is not ready to deploy. There are some presentation and accessibility issues.

There are **some issues with the form**: there is an empty tab between the last of the reviews and the first link in the form, "Sign in to Google". That link then opens in a new (browser) tab without any warning.

The links "Sign in to Google", "Learn more", "Report abuse", "Google forms", "Privacy policy", "Terms of Service" and "Report a problem to Google" have very weak changes: on `:hover` the only change is to the cursor; the same links on `:focus` have only the browser default (varies with browser). 

The :`hover` and `:focus` styling for the Submit button is weak — a small change in background colour only. This also applies to the "Clear form" button. (The changes are very similar to those of the "Comment" and "Close with comment buttons" in ZenHub!)

When "Clear form" is selected, the top of the form changes to:

![review-form](https://user-images.githubusercontent.com/14852554/139753182-4c3aa39a-cba8-4f17-9842-ba6ab8f8f000.png)

Before using the clear button, the form starts at "Leave a Review for FreeREG". What should be at the top?

On using "Clear form", the bottom of the form also expands to include some of the links listed above. Before clearing the links are a little different and one has to scroll to see them. Is this intended?

I _think_ that a screen-reader user will be able to understand the form inputs but I cannot be sure — the markup is not a conventional form but a series of `div` elements with a number of Aria attributes designed to mimic a form. (Why, oh why??)

**Finally, some simple questions**:

The current page title is "About — Your Reviews" [sic]. Should it be "About — your reviews" or simply "Your reviews"?

Should the page be moved to be a child of "About"? (It is currently a top-level page.) Can I assume that we need to add a link to this page from "About"? Thank you!

**Comment by AlOneill** [comment]
@DeniseColbert One more thing: which style of quotation marks do we want: the large coloured ones as seen towards the top of the page or the simple styling used further down? Thanks!

**Comment by AlOneill** [comment]
@DeniseColbert It looks like we decided on the version with the over-sized opening quotation mark. I'll tidy up the scoped CSS offline and post when that's done.

**Comment by AlOneill** [comment]
@DeniseColbert Page updated as far as I can for now.

**Comment by DeniseColbert** [comment]
Thanks, @AlOneill

I've changed the theme colour to the blue-grey, hopefully that helps some of the issues.

I thought we opted for project colour and grey alternating, for the blockquote styling as the lighter project colour is too low-contrast?

The Clear Form/image issue seems to be a bug. The image is at the top of the form but not shown as default. However, something clearly changes when the form is cleared and the image is shown. Should I remove the image for consistency? The links issue is also unintentional and perhaps indicative of bugginess on Google's end.

**Comment by AlOneill** [comment]
@DeniseColbert The blue-grey does not provide a good colour change on focus/hover. Did you try it?

It seems that I need to read that article more carefully or that colour changes were not taken into account. Sigh.

I don't remember clearly what we decided on for the block-quote styling. Here is a REG project colour plus grey (contrast ratio 3.15:1, suitable for an AA UI component) example:

![reg-project-grey.png](https://images.zenhubusercontent.com/5ce6b34165b1a70acc0a9124/5be313c8-f77d-47b6-bb85-8b3fee020c5a)

I think it would be better to remove the image from the Reviews form.

Not sure what you mean by the "links issue" as there are a couple of problems.

You or I need to establish just what we can edit for the styles. I'll review the article to see what looks possible.

**Comment by DeniseColbert** [comment]
Change colour to FR blue
Remove image
Note above form re. accessibility and alternative submission (info@etc)

**Comment by AlOneill** [comment]
Have added note re accessibility and alt submission by email.

Just noting that the image is still there, at the top of the form and that the colour is still a blue-ish grey.

**Comment by DeniseColbert** [comment]
Should be done now @AlOneill

**Comment by DeniseColbert** [comment]
Page now ready for @AlOneill to make live, add link from About page (removing 'About' from the page title).

Next step after page is live, we need to add it to the 'Contact Us' form. @Vino-S and @DeniseColbert to discuss how this can be best achieved.

**Comment by DeniseColbert** [comment]
The documentation team suggest a paragraph at the top of the 'Contact Us' page, above the form, and removal of the 'Thank You' option from the Nature of Contact select box. We would provide the text.

**Comment by AlOneill** [comment]
@DeniseColbert Link to "Your reviews" added to [DRAFT About](https://test3.freereg.org.uk/cms/draft-about), along with improving the source order plus a number of other fixes — mainly typos and non-semantic use of various elements.

**Comment by AlOneill** [comment]
DRAFT About promoted to About.

**Comment by DeniseColbert** [comment]
All looks good and works well, thanks @AlOneill !

**Comment by DeniseColbert** [comment]
> The documentation team suggest a paragraph at the top of the 'Contact Us' page, above the form, and removal of the 'Thank You' option from the Nature of Contact select box. We would provide the text.

Just this to see done before this can be closed ^^
