### ISSUE TITLE
Add names to emails on message system

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1218]
Add a 'Dear *first name*' to emails from the message system, in order to improve deliverability / reduce misapplied spam barriers (and because it is friendlier to do so)

**Comment by PatReynolds** [comment]
May need a change in the message system - does it send out one message with lots of bcc, or does it send out lots of individual messages?

**Comment by Captainkirkdawson** [comment]
It only sends 1 message. 
Recipients are bcc's so as to reduce volume of actual emails being sent to sendgrid.

**Comment by edickens** [comment]
So does anyone know how we can show SpamCop that although the messages are computer generated they are not a general Spam mailing?  That is why I suggested personalising them.  ED

**Comment by PatReynolds** [comment]
"Spammers constantly adapt to these anti-spam measures, so administrators have to continually modify server configurations to help reduce spam. As a result, there is no single thing you can do to ensure that all of your outgoing messages are delivered successfully." and, I would add, for every thing we do to ensure that our messages are delivered, there are spammers ahead of us on the work-around, and the communications industry is already trying to stop EVERYONE using the work-around, including us.
 http://www.seas.upenn.edu/cets/answers/spamblock-false.html
https://www.a2hosting.com/kb/security/managing-unwanted-e-mail-spam/preventing-outgoing-e-mail-from-being-marked-as-spam

**Comment by edickens** [comment]
Understood.
My GoogleGroup gets through every time, but it is impractical to use that.
I sent my message 80254692 through the server and the CC mail group, but it did not get to Jackie SOM Coord who said:-
"FYI I only got this email, not the earlier one sent through the message system. "
But I never got a bounce for this either.  Odd.  ED

**Comment by edickens** [comment]
My bank advises me never to open emails that are not addressed to me personally.  So they send individual computer generated messages that do get through.  But I do understand the problem of so many messages through Github.  ED

**Comment by dougkdev** [comment]
Last time I looked at a message coming from the applications to me, the email passed the SPF test, but I noticed that DKIM was not used.  Setting up DKIM / DMARC might help for recipients who use some email providers. But as Pat mentioned, it is very difficult to reliably get emails through no matter what because spam filters have gotten so aggressive.

Personalizing emails might help for some recipients, but hurt for others- an email can get flagged as spam because of lots of BCCs, but an email can also get flagged as spam because it is too similar to emails sent to lots of individual recipients. On one project I worked on, the email for the domain was hosted by Google's mail servers and Google blocked outgoing emails that were personalized after only a few dozen were sent. Google's tech support said they were blocked as "spam" because they looked too similar to those that had recently been sent. At least at that time, Google preferred fewer outgoing emails BCC'ed to many people instead of many individual emails, and that was the only way we could get the emails out to more than a few users. Of course Google's outgoing filter is not the same as sendgrid's and Google may not even use the same criteria on its servers for incoming mail as it does for outgoing mail; this is just an indication that personalizing emails may or may not help, depending on the specific filters and rules any given email provider uses for determining whether incoming email is spam or not.

**Comment by edickens** [comment]
So should we scrap the messages system?  If we can't reliably contact members, then there is no point.

**Comment by PatReynolds** [comment]
No to scrapping (without replacement). If we are to continue to consult
with our volunteers, it is vital. Still need to find out why some emails
appear not to be sent by sendgrid as they are the main problems. Those That
are sent from sendgrid but are not received at endpoint (under 20 a time)
can be resent by MailChimp.

I will start a story for the investigation. This can be on hold in incoming
until more I'd known.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by Captainkirkdawson** [comment]
Any investigation should be done as part of #965

**Comment by richpomfret** [comment]
To test sending out an individual email with name included to a blueyonder or ntlworld account

**Comment by dougkdev** [comment]
Do the messages get consistently rejected as spam when they are sent as sender freereg-contacts@freereg.org.uk, or are they being sent as sender being yourself?

**Comment by Captainkirkdawson** [comment]
Remember regardlees of the sender the main recipient is
freereg-contacts@freereg.org.uk, with all others as bcc

As to question I have no idea

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
A  personalization of the subject has been added, as well as identification in the message. An encouragement to add a sign off has been added

**Comment by Captainkirkdawson** [comment]
Have deployed the new version to test3 for evaluation
