### ISSUE TITLE
Amend Transcriber Information to include informing their coordinator of any Data Restrictions on images or data they find for themselves

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1256]
Priority 25 (0	10	8	7)

a note is needed in the Transcribers Information to say that they must tell the CC about new data.  The CC then sets the restrictions.  Perhaps when we program in the restrictions a message needs to go to the Data Manager whenever a Church gets entries for the first time.

**Comment by Sherlock21** [comment]
As I have said before, this DM only needs to know such things when anything goes wrong - like I do at present. The CC is competent to create their own churches - or ask for help. Similarly they ( or the SC) can manage their own Transcribers. So I do not need to be getting emails just for the hell of it.

**Comment by AlOneill** [comment]
@PatReynolds Not sure I get the proper gist here ...

Are you saying that if a transcriber acquires new data (not already in the database) that they intend to transcribe, they need to clear it with the appropriate CC before they begin work? So that Place and Church can be created if necessary? And/or because ... (I think people respond better to injunctions if they know the reasons).

What about data that they don't intend to transcribe, for whatever reason? (That might sound weird, but I'm not sure exactly what this is all about!)

And can you expand a little on what the CC "setting restrictions" means? Thanks!

**Comment by Sherlock21** [comment]
In case no one else responds, I can reply for some of your queries:-
Records for New Places and or New churches need to be advised before they transcriber starts on them, so that:-
the appropriate Place Name can be created by the DM if its not already there in the right County & spelling etc  and the church needs to be created by the CC if it's not there already.
ESLE the uploaded file may had the wrong Place & church names and will get rejected.
Also, some CC's need to set the file name.  

There will be other requirements as soon as Pat has resolved this question of Copyright requirements
And Credits under any Licencing that applies.
 
AND in cases where the Transcriber is providing new images to FR, then the CC needs to be the link to ensure any other restrictions like showing images to the public get the right copyright arrangement OR get the blocking  set properly so they dint get shown.

For PAT: And what about applying the (NEW) 100 Year Rule  equivalent under the EU Regs?

The item about data they don't intend to transcribe: well when they do decide to Transcribe it with a view to uploading to FR, then they need to follow the steps above.

**Comment by PatReynolds** [comment]
100 year rule (or lack of one) and our response to it is not changed by the EU regs.

**Comment by Sherlock21** [comment]
Ah!

but the so called 100 year rule is not written anywhere in any sort of legislation, rather its a Gentleman's agreement according to Eric D isn't it?

SO how are you covering that in FR please?

**Comment by Captainkirkdawson** [comment]
Requirement is totally unclear

**Comment by richpomfret** [comment]
Process task relating to documentation. We need to capture the data restrictions and ensure this is communicated to the CC.

**Comment by PatReynolds** [comment]
Suggested text:
If you have access to new images that have not come from the Image Server, or access to new data (e.g. a transcription made by a friend), you must inform the relevant County Coordinator before accepting the images / data.

**Comment by PatReynolds** [comment]
Text above added to Information for Transcribers - [DRAFT] above warning re using images from Ancestry, etc., on test 3.

**Comment by AlOneill** [comment]
The 2 islets contain overlapping information, so I will combine them and edit the text for a better flow.

**Comment by AlOneill** [comment]
@PatReynolds This edit is now done (on test3), combined with updates to the page required by adding the 4 new pages of #1442.

The draft version of "Information for transcribers" has been deleted (out of date).

Suggest that when a DRAFT page is created from an existing page, it is **placed next to the original** in the Refinery listing, so that it does not get overlooked by a second person who may also need to edit the same page!

**Comment by PatReynolds** [comment]
All good, @AlOneill  . I have added the instruction that the DRAFT copy should be below the original.
As I am not sure at the moment (on to do list to make myself certain) where we are on the copying back from live to test3 / copying from test 3 to live rake task, I've added the DRAFT back to it so it isn't overwritten.

**Comment by Captainkirkdawson** [comment]
@PatReynolds As far as I recall; the copy live to test3 was a one time action that has been completed and should not be repeated
