### ISSUE TITLE
Acknowledge transcriber in the the search record detail display

### ISSUE THREAD

**Issue by Sherlock21** [FreeUKGen/MyopicVicar#1267]

**Comment by Sherlock21** [comment]
When a person's name to be credited with doing a Transcription, is put into Batch Header field ow 3, col C, it does not get onto the individual records in that batch,  when the record comes up in a search results listing ( and is viewed under "Detail"}

Some donated files are being obtained under Licences   that requires that information to be shown to the researcher.
Some Volunteer members also wish that information to get to the user.
Having the ability to add into the File Header details within the FR Application, ( i.e. online)  does not get onto the individual record in that batch either so far as I can determine.

**Comment by PatReynolds** [comment]
Do we need to add a question about desire to be accredited to the
Transcriber sign up?

**Comment by Captainkirkdawson** [comment]
Pat that is a totally different story

**Comment by Captainkirkdawson** [comment]
There is no code that has ever placed the transcriber or other credit information into the individual record. It has always been held at the batch level,

**Comment by Sherlock21** [comment]
AH!

But many Transcribers wish their name to be shown to the Public. And the only way the public see the records is in a search result where the individual record item is shown.
The file header is only seen by the CC ( and Mgrs) who know format he userid whose it is.
I recall that when originally specced by the Review Group, it was intended to have the means of optionally showing the 'Credit of Transcriber's name' to the end point user.

SO how do we get that in please?

**Comment by Captainkirkdawson** [comment]
The transcribers name and any credit information is available to the researcher through the Transcriptions (DAP) pages at a register level.
https://www.freereg.org.uk/freereg_contents/565ae372f493fd51320001c5/show_register

**Comment by Sherlock21** [comment]
That's a very back door way to get there in my view.
How many transcribers actually know that to be the case - I didn't and I am part off the team! -

The logical of the Search tool is:
you do a search
scan down the results list,
pick the ones of interest and look as the Details Link
read down the details.
End.

All the details available this was round are also on the DAP route as you rightly say. so why not let the researcher find the other things out via the DAP info route too?

**Comment by Sherlock21** [comment]
Furthermore the DAP Credit information bundles all the Credits together for each type of record as here below:-

Thats not going to be compatible with Agreements to Credit the Transcriber in some cases. There, the actual single record will need a Credit.



![dewsbury transcripts credits](https://user-images.githubusercontent.com/9368704/29276171-a8c5622e-8105-11e7-9bb9-7fba4eca5bb3.jpg)

**Comment by PatReynolds** [comment]
Yes, I think the details page needs at least a change of text from "Place (link for place information)" to "Additional information", or perhaps more detailed links (so Place is the Summary (e.g. "Burton Latimer" linking through to the information about that Place). Since Transcriber, supplier of images, Record Office and Church may each Open or Close the transcription, this data is known at this level (I think!).

**Comment by SteveBiggs** [comment]
If it is a condition of the Licence from the supplier of the source data to provide information at the individual search result level, then we need to find a way to do it. But what information is required? Is it just the transcriber or the whole supply chain of the data as Pat lists? If the latter, this will be very difficult because many (most?) uploaded csv files do not include specific information on where the source came from. The comments in the header often just says "Parish Register" for the source or nothing at all. So for many records, all that's recorded is the transcriber and going back and adding the other supply chain information to all the files is clearly not feasible.

**Comment by Sherlock21** [comment]
WE have just obtained some date that comes with this Creative Commons licence - which I understand mens we need to show the right credits - from the start.. SO there is a degree of urgency needed as the files would be ready for uploading shortly -

**Comment by Sherlock21** [comment]
I forgot to add the screenshot!
![Credit.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/545bc5c91920350200d20f63/125516c66e82c728ace21e0d46cb869f278b97ebc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98515be04ba24834785b1bc8d4ec9e82f68.jpg)

**Comment by Sherlock21** [comment]
File info re source and credits for data is entered in file header. But this is not seen in search results.

There may be multiple sources and credits within one register. How would these be entered in Register details?

Could the header info be used instead?

**Comment by SteveBiggs** [comment]
Eric, could you post a clickable link to the license please?

**Comment by Sherlock21** [comment]
Steve - this was what I attached - or so I thought.

please replace it for me.

**Comment by Sherlock21** [comment]
For which comment please, Steve ?

**Comment by SteveBiggs** [comment]
You posted a screenshot of Creative Attribution ....3.0 ....License.
Could you give a clickable link to this license?

**Comment by Sherlock21** [comment]
what I posted is on the bottom of the first page on this website.

http://tadhistory.org.uk


Eric

**Comment by Sherlock21** [comment]
I am now ready to upload some files for this particular  case.

SO I need the necessary advice on what to put and where please.

AND what extra do you need - in respect the flag: NEEDS INFO please.

**Comment by PatReynolds** [comment]
Sorry, missed this yesterday.  Is any info still needed?  If not, I'll move and prioritise.

**Comment by PatReynolds** [comment]
I believe that you need to create an ID for the donor society, and record the information against that ID, upload the records against the ID.

**Comment by Sherlock21** [comment]
I can't quite imaging how this would work. Can you create an example in T3 please?

**Comment by edickens** [comment]
We usually upload the batch against the person's ID who converts it to our format.  But this would seem to be a much better system and does not require any changes to the website.  Just some words in the CCs section to say that this is our policy and why.

**Comment by PatReynolds** [comment]
Issue #1177 is about updating instructions for CC.

**Comment by Sherlock21** [comment]
I can't agree with this as a suitable method at all.

Firstly, the User's ID does not get onto the individual viewable record, does it.

Secondly, where does the ID of the person doing all the work go to?

Thirdly, if a County RO does give access to its records, and it wishes to have a credit/ acknowledgment, are you proposing to do this  to all the batches that are created from that source, again without the Transcriber getting any credit? IF not, then how do you propose to divide up which system applies to which? and later on find the batches concerned?

Fourthly,  how do all the Transcribers in a County share one ID so that all the requisite batches do get uploaded into the same ID?

Fifthly, how will a Transcriber later find a particular batch, in order to do a Reload in this system?

Sixthly how on earth do those who need to, find their batches, to reload

**Comment by suffolkroots** [comment]
Perhaps all that is needed is info to guide users to where they can find credits etc?

"Transcriptions" is not self explanatory.

**Comment by PatReynolds** [comment]
Firstly, the User's ID does not get onto the individual viewable record, does it.: _this is planned_

Secondly, where does the ID of the person doing all the work go to? _the ID of the volunteer doing the conversion?_ That we hadn't thought of recording. Why is it needed (other than to thank them - that could go in public notes).

Thirdly, if a County RO does give access to its records, and it wishes to have a credit/ acknowledgment, are you proposing to do this to all the batches that are created from that source, again without the Transcriber getting any credit? IF not, then how do you propose to divide up which system applies to which? and later on find the batches concerned? _There are going to be multiple credits: transcriber, Record Office, originating body._

Fourthly, how do all the Transcribers in a County share one ID so that all the requisite batches do get uploaded into the same ID? _Can you clarify why all the transcribers in a county share an ID - perhaps the answer is the answer to 'what do you mean by 'all the requisite batches'?_

Fifthly, how will a Transcriber later find a particular batch, in order to do a Reload in this system? _As they do at the moment._

Sixthly how on earth do those who need to ( like the CC, or DM), find a particular batch, to reload or to edit online? 
Is how they do at the moment not possible once they also have an ID for an organisation (which will act in the same way as an ID for a transcriber)?

**Comment by Captainkirkdawson** [comment]
Could I remind you that a batch has 2 fields for the purpose of identifying the transcriber and who should receive credit for the batch. 
The credit can acknowledge multiple people and entities. This is the information that is summarized in the  Transcription displays.  That information can be edited on line if needed.
Can I remind you that there is no technical requirement to have this information "ripple through" to the  individual entry. Since an entry belongs to a batch any information about the batch is automatically available to the entry.
Put simplistically the entry "already knows" the transcriber and the credit information as well as everything else about the batch.
If there is a requirement to make this information "visible" to a researcher with the display of a record it is a trivial effort. There is NO need to store it in the record!

**Comment by Sherlock21** [comment]
Given Kirks timely summary of How the present Application was designed to be, it seems appropriate to say
Let us close this story, and start again with the following header:

Arrangements for complying with the Creative Commons Licence and also with the New Copyright Act.

In fact I started this story off thinking that we already had the means to do this - in fields 3B and 3C of the file header.
That was a simplistic view perhaps, as it turns out even though it may end up as the easy solution in the end.

SO better start with defining WHAT we have to achieve, and By WHEN and cover:-
1) the Creative Commons licence  that may attach to using some source data
2) the Copyright Act which may well attach to other sources particularly Register Images.

**Comment by Captainkirkdawson** [comment]
I am a strong advocate of What and a strong critic of HOW

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
Irrespective of the legal requirements, I think it would be good to display the credits with the search record and helpful with the drive to increase engagement/collaboration with source record providers.

Since it's trivial as Kirk says, then let's just do it. For any batch where it is required/desired to show these credits, the transcriber or coordinator needs to ensure the relevant header fields are entered.

**Comment by Sherlock21** [comment]
As Kirk says in #1306, the fields are already there in various places - not necessarily where I an suggesting.
Also, he says we should stick to defining WHAT and not try to define HOW in this forum. i am content with that, but its only by also discussing HOW that I get the end result of WHAT. - perhaps because my definition of WHAT is lacking?

SO here's my WHAT in this case, using a real example.:-
Lets say County = WWW; Placename = AAA; Church name = All Saints; My Original "doc" = Parish Register images on fiches from the RO [ not using the actual one as I don't know who might read this]

NOW when I started transcribing this set, some  12 years ago, I got the fiches from the RO with no problems and no requirements for any credits of conditions etc. SO none got put in anywhere.
Now I need some more fiches to continue with, and the RO rules have changed and they require a credit to the source.
Now this credit is only required to apply to the new fiches. & not back dated.
And the requirement is also: those search results that come form the ORIGINAL batches do not need the new "credits" whereas the individual search results that come format he NEW fiches, do need the new Copyright Credits ( or  maybe in some cases, a Creative Credits tag from Pat's Legal references)  

SO the WHAT is defined.

Question therefore is HOW, given that the church is the same in both cases and the PR is  exactly the same in both cases. - its just the new Copyright Rules or the Creative Commons Licence that have changed as far as I can see. 

SO please advise how the list of Forms & tables in FR  need entering form my Data spreadsheet,
in order that the WHAT is achieved.

This entry is also common to the later stories 1307, 1309.

**Comment by SteveBiggs** [comment]
I think we just need the "Credit to" field to be made visible in the search detail result. For any files where you want a specific organisation/church/etc. credited, you must type that into the credit field (line 3 of batch header). If it's not required, then don't enter it.

**Comment by PatReynolds** [comment]
Although the RO has only just requested that it be credited (or haven't yet), this is useful information for the researcher in any case.

**Comment by SteveBiggs** [comment]
I agree.

**Comment by Sherlock21** [comment]
I am still discussing the credits requirement with 2 different RO's and each has a totally opposite view on the subject. So at worst they may say: a little logo type thing is required - or at best: say No nothing is needed so long as we stay as a  Not for Profit Organisation. I will advise when I get a result.

That leaves it remaining personal Transcribers and  Donators, which am not tackling.

**Comment by Captainkirkdawson** [comment]
Will deal with as part of #809

**Comment by Captainkirkdawson** [comment]
See following for examples
![marriage.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46e59588318b82ae8aabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb60bbb258a4786bfb58e4ac6ee3b20f5c6.JPG)
![Burial.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46ca81882a838febc3abaf51ab57f5973d047d317c57a6287180ba71eb1a2b560d5a4eae41585e47a9f98a7db4aa2e32db025fb28c341521842f1bbeb98515be04bb2888468cb2ba8c4ac9e92f68.JPG)

**Comment by Captainkirkdawson** [comment]
Update to use the field in #1310 to decide if to display the field

**Comment by Captainkirkdawson** [comment]
This story unfortunately is mixing three different components into 1 story with people commenting at cross purposes. Unfortunately it is also using credit in a general sense while credit has existed within FR with a specific meaning.
2 of those components require that we respond to the EU directive GDPR on the projection of personal information that requires a positive opt in to acknowledgement.
I propose to split this story into the 3 component, 
The GDPR also affects the Transcriptions (DAP) displays so will raise 2 additional stories for those. These latter stories can wait for implementation until the specification for how to deal with the 2 current acknowledgements.

**Comment by Captainkirkdawson** [comment]
Have set up so that after 25 May 2018 the transcriber will have had to formally authorized the use of their name by the setting of the field established in story #1310
This means that effective that date we will not be acknowledging the contribution of  99% of our transcribers since they are now inactive. 
This is in flexible_csv branch

**Comment by Captainkirkdawson** [comment]
On test2

**Comment by SteveBiggs** [comment]
Should the transcriber be listed now in a search record on test2? This result does not show it:

![image](https://user-images.githubusercontent.com/25303607/36425050-68a8a48a-163d-11e8-9c2e-9a62b3fef3cc.png)

I then went in to my profile and ticked the box "Acknowledge my transcription", clicked Update and got this:
![image](https://user-images.githubusercontent.com/25303607/36425102-9cc52234-163d-11e8-80e4-71eb4c19dbad.png)

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  Fixed the crash, bad merge of code with multiple changes. My error.

However the code changes in #35 management are very problematic.

Will now look at the first part of your comment

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  I believe that it now works as designed.
Transcribed by will appear for all up until 25 May 2018. After that only those that have asked for acknowledgement will be shown.
The credit still comes from the file and will be shown until 25 May 2018

**Comment by SteveBiggs** [comment]
Yes that all works now thanks, but should we still have the old 'Transcription agreement accepted' tick box as well?:
![image](https://user-images.githubusercontent.com/25303607/36482387-0b2a99a2-170b-11e8-92a1-f43e9e9895e8.png)

**Comment by Captainkirkdawson** [comment]
No I was unaware of the work on the new transcriber agreement so this is not required. 
As you will have seen I have major concerns over how that has been coded.

**Comment by Captainkirkdawson** [comment]
Revised. Please see #1310 for the edit form.
Revised to work with the latest guidance from Pat. We use an opt out of acknowledgement instead of an opt in

**Comment by Captainkirkdawson** [comment]
Deployed to production

**Comment by SteveBiggs** [comment]
Looks good
