### ISSUE TITLE
CC County level Image Group Report

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#1289]
Provide a single tabular view of all Image Groups within a County to help CC's manage image allocations. This should include columns for; Place, Church, Register, Image Group, Status, Start Date, End Date, Transcribers and Actions as a minimum.

**Comment by Sherlock21** [comment]
Yes please. Exactly what is needed for a planning overview.

**Comment by edickens** [comment]
Be careful not to confuse this with the RAP report because that should show image groups for those images which have never been transcribed or are marked as needing to be done again.
But I agree that a report to let the CC know what images/groups are there is needed.

**Comment by SteveBiggs** [comment]
This is to give CCs an overall view of all the IGs in their county without having to click into each place/church/register/image source in turn.

**Comment by SteveBiggs** [comment]
EricD wrote:
"This is what the RAP report should cover, but perhaps only part of what you are asking.

So thinking through the process, you need to go through the sequence of things the CC would do.  I think it is this:-

- The CC is looking for some work for a particular transcriber.
- The CC wants to know what has and what has not been done.
- The first thing is to look through the list of places and see a count of how many images there are and how many transcribed entries.
- The CC would then home in on a particular Place/Church/Register type to see if it is suitable for allocation.
- This list could also be used to see when it is necessary to obtain images, or whatever.
- Next would be to sort out any wrong descriptions and mark it to give it a priority.

Do you think this could be part of the Places listing?  It just needs the number of images and transcribed entries against each Place/Church/Register Type.

Or are we into the allocation process again.  It should be possible to call up all transcribed images, or image groups, in the RAP report.  Or is best to start from the transcriber.  Call that up and then ask what images have not been transcribed for a particular county with the level of difficulty to match the transcriber.  This would be a filter option of the RAP.

Let's define the images first.  As this has never been done, there is a lot of work to be done.  And there are many Register Types which do not match."

**Comment by Captainkirkdawson** [comment]
@SteveBiggs you said

"Do you think this could be part of the Places listing? It just needs the number of images and transcribed entries against each Place/Church/Register Type."

I was about to ask essentially the same question but in a different manner. 

I was about to ask if we should remove the image source column and link from the All Places and Active Places displays and expand the Manage Images Action to include the Image Groups?

We do not need it in both. 

You must remember that such a display becomes extremely time consuming to create. That was why we limit the range of places to be shown. In big counties we only show single alphabetic places eg just A  

It becomes a question of how often a coordinator is going to be working with place/church/register and how often with place/church/register/image_souce/image_group.
If there is enough of the former we should have a manage image action if not we combine.

**Comment by SteveBiggs** [comment]
I would agree that we don't need the image source column in the Places display as well as under Manage Images and I do understand that a display with all Image Groups for the county would be huge (there are over 2500 IGs in Sussex). I'm just trying to find a way for the CC to quickly see which places have images available for transcribing. The RAP that EricD describes is at a single place level so you need to know which places to look at to find available data.

Perhaps the Manage Images page could have a column stating it has un-transcribed images with a boolean 'True' or 'False'?

**Comment by Captainkirkdawson** [comment]
Shall we hold this until work on the allocation process is complete or do you think that CCs will want it straight away?

**Comment by SteveBiggs** [comment]
Hold until the allocation process is complete when we can then assess exactly what we need here.

**Comment by edickens** [comment]
Agreed.  This report will show a lot of discrepancies because the Images have the correct Register Type but those batches uploaded from FR1 only had "Unspecified".  It will not be necessary to change the database Register Type (which takes a lot of processing) if we can identify which images have been transcribed.  So the main job will be to link the Batches to the Images.  This is part of the Allocation process.

**Comment by edickens** [comment]
Yes,  I saw this but it is more to do with the Allocation process rather than managing the images and their Sources and Groups.
This is the "All Places" for SSX letter B...
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa871ebf01b0218e4f86bfbf8a4ac0ee3522ef99c2.JPG)
This is very nearly the report that Steve wants.  e just need to know if there any (not necessarily how many) Entries against "Register" and Images against "Sources".  This would then show if there were images with no transcriptions and transcriptions with no images.
It would then be possible to go into more depth to find out what is going on.
