### ISSUE TITLE
Add more information about the church to the detailed results page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1306]
e.g. link to the church website, address of the church

**Comment by Captainkirkdawson** [comment]
Before you go off defining new fields in inappropriate documents can I remind you that those fields and others already exist in the church document, In almost all cases they are empty as no one has entered the information.
As I reminded you in 1267 an entry has access to this information since it belongs to a batch which belongs to a register which belongs to a church (which belongs to a place)

**Comment by PatReynolds** [comment]
So two stories ... add more information to the church document (new story), and serve it on the results page (this story)

**Comment by Captainkirkdawson** [comment]
This is identical to #1389 that is active. Will close this as a duplicate
