### ISSUE TITLE
Add acknowledgement to the source of our information (such as the record office) to the detailed results page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1307]
Including link to their website.
Info about record office or other holding institution

**Comment by Sherlock21** [comment]
The last time a question of adding urls for external links came up, it seemed to get the thumbs down, due to the resource necessary to maintain them.

SO you would need to have a policy establishing to cover that.

The only url link that I am aware of, is the Location of the Place (in FR). and that's going to be an issue shortly as Genuki are changing all theirs. - and this will be no mean feat, given the present staffing position.
see #1308

**Comment by PatReynolds** [comment]
We need to have at least the ability (it is being made a condition of access to images).  Ideally, there is a list somewhere that we could regularly harvest.  E.g. http://discovery.nationalarchives.gov.uk/find-an-archive

**Comment by Sherlock21** [comment]
Which results page please? The Researcher's Search results? Or these stats results that you have also referred to recently?
What is the purpose of this link or reference? or both??
Does this reference need to be just a text line? Or might some  want a pictorial logo as well?
And if this is about Researcher Search Results, then what do you specify for the results that pull in records from more than one RO? This will happen when the results cross the County Boundaries in a Nearby search.

**Comment by edickens** [comment]
The researcher results page, but the information will come from the County, Place and Church record.
The idea is to point out, without the researcher having to click on the Place, Church, that there are other places to get more information.  This is so that others see that we want to work with them and point researchers to them.  Hopefully  they will then see that it is worth their while working with us, rather than other websites.  Also, it justifies our existence by promoting further research and genealogy tourism.
I suggest just text, but it needs to be a banner or something that comes up when they select and entry.  Pop-ups are not a good idea as they can be blocked.
It would be the detailed result, because we would not want to show this information for an entry that was not relevant to the researcher.
This needs specifying in detail.

**Comment by Sherlock21** [comment]
I agree with Eric D's very last line in the previous comment.
In fact: a mockup actual example or what it would look like would be the best way of getting the point across. 
"A picture is worth a thousand words....."

The opening comment said:  (it is being made a condition of access to images). So exactly what -and how- are they requiring please? 
Lets not build something that's not required or does not meet the requirement

**Comment by Captainkirkdawson** [comment]
Before you go off defining new fields in inappropriate documents can I remind you that those fields and others already exist in the register document, In almost all cases they are empty as no one has entered the information.
As I reminded you in 1267 an entry has access to this information since it belongs to a batch which belongs to a register (which belongs to a church which belongs to a place)

**Comment by Captainkirkdawson** [comment]
It is proposed that we add a link to the source of the information by linking to the register collection information where this information should be retained.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  The register contains credit, status  and source fields . The image server source has more detailed information on the source and restrictions. Should we be linking the 2?BUT it  is possible that the register has multiple sources so there are issues with linkage.
Should we be using the register credit field rather than the individual file credit field?. 
These fields are freeform. I suggest that the register status field use the image status field definitions
https://github.com/FreeUKGen/MyopicVicar/blob/bevbranch5/lib/source_property.rb

**Comment by SteveBiggs** [comment]
I like the idea of using the register credit field because it's far easier to add this to registers that have already been transcribed rather than having to add to each individual file. It would also be good if this credit populated the "Contribution by these ..... " field under Transcriptions:

![image](https://user-images.githubusercontent.com/25303607/36379733-9f6ec42a-1577-11e8-8dec-8967e7d4c3b2.png)

**Comment by Captainkirkdawson** [comment]
A little confused .
Are we to have 2 or 3 fields in the details? 
1)Transcribed by 2) Who contributed to its creation (ie credit) and 3) The source of the record that was transcribed 
Or just 1 and 3

**Comment by SteveBiggs** [comment]
I think we only need two fields; 'Transcribed by' and 'Source', but historical confusion has been caused by the naming of fields in WinREG particularly of 'Source' for the first set of comments:
![image](https://user-images.githubusercontent.com/25303607/36666425-86be54a2-1ae2-11e8-9046-454786b834cb.png)
This has often understandably, been used to record the name of the RO or other institution that supplied the images rather than the 'Credit to' field below (which if used at all, has generally repeated the name and email address of the transcriber).

**Comment by PatReynolds** [comment]
Possibly all three, created by (eg church, local authority or other name), transcribed by, and acknowledgement/other eg intermediate source (Phillimores) by kind permission of Vicar of ...,  Original held at .. .

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  I have had Bev write a rake task to explore what is contained in the various header fields.
I am afraid to say the there is little that is consistent in their content for the comments fields. Even SSX which is likely the "best" has 100s of files with non source information. I will let you have the collection dump when things are quieter but my bottom line conclusion is that the comments field of the header is not viable.
Even the source field in the register is limited to the following unique values

Bath RO photographic copies of Original Register
Bishop's Transcript
Bishops Transcripts
BT
BTs
BTs and PRs
Cambridge Records Office
Doncaster FHS
Dwelly's Transcript CD
Fiche from SHC
http://freepages.genealogy.rootsweb.ancestry.com/~davidbeare/CurryRivel/curryrivel01.htm
http://freepages.genealogy.rootsweb.ancestry.com/~pbtyc/H_m_w/Kittisford/Index.html
http://www.durtnall.org.uk/Somerset%20Pages.htm
http://www.portbury-hundred.co.uk/
L
Latter Day Saints
LDS
LDS Burials Books
LDS Film 1526112
Library images
National Archives
nk
Non-Conformist Records
Norfolk Records Office
NRO
Parish records
Parish Register
Parish Registers
Phillimore
Photographed by Bob & Pat Chown
Photographs from RO
Phtographs from RO
PR
Rev C H Mayo
RO photographs
Roy Parkhouse transcriptions
SEAX
SHC
SHC fiche
SHC FICHE M14743 - 1 & M14743 - 2
SHC registers and fiche
SHC?
Somerset History Centre
source
South West Heritage Trust DEV
Suffolk Records Office
Thoresby Society Transcription
Thoresby Society Transcripts
Timothy Jollie's Register of baptisms
Transcription
Transcription by W J Stavert MA FSA, published 1912 and 1915
Unknown
W
West Sussex Record Office
Wisbech and Fenland Museum

**Comment by Captainkirkdawson** [comment]
Based on the preceding analysis I am tempted to propose that we not show the source information in the search details field

**Comment by Captainkirkdawson** [comment]
The SSX comment1 list of unique values was 171
42743
42757
42770
42779
42789
42806
42896
42924
42949
42950
42961
42972
42976
42981
43005
43037
43065
43079
43099
43110
# 19/10/2016 Parish Registers SSX-Shipley-GR-1733-1772-168-1-1-3
# 20/10/2016 SSX-Shipley-GR-1733-1772-168-1-1-3
# 43163 Parish Registers SSX-Yapton-BA-1853-1876-225-temp
# West Sussex Records Office Ifield Parish Registers 12-Jan-05
1813-1903
1837-1900
Angmering Parish Registers, Sussex Record Society, 1913
Baptism Records 1558 to 1812 converted from transcript at barriesgenealogy.co.uk
Baptism Records 1807 to 1837 converted from transcript at barriesgenealogy.co.uk
Bolney Parish Registers
Bolney Parish Registers, Sussex Record Society, 1912
Burials 1803-1834
Burials 1813-1843
Burials 1828-1847
Copy of Parish Register 1890
Cowfold Parish Register
Cuckfield Parish Registers
data converted from Excel spreadsheet of Dorothy Spence
Englishparishregisters.Com
FHL Film 1067139
General Register
GR
GR-1646-1812-79-1-1-1
Marriage Records 1571 to 1837 converted from transcript at barriesgenealogy.co.uk
Marriages 1822-1834
Microfiche of Parish Records
Other Transcrip
Other Transcript
P R T Society
P.R.T. Society
Pafrish Registers
Paish registers
Parish
Parish Baptism Records 1760 to 1812
Parish General Record
Parish General Register
Parish General Register + some BT inclutions
Parish General Register + some BT notes
Parish General Register 2
Parish General Register with some recovered BTs
Parish Record
Parish Records
Parish Records.
Parish Register
Parish Register Transcripts
Parish Registers
Parish Registers 1813-1837 Verified
Parish Registers 1813-1856 Verified
Parish Registers GR
Parish Registers of Ardingly
Parish Registers SSX-Ashington-GR-1736-1812-9-1-1-1 Verified
Parish Registers SSX-ChichesterTheClose-46-1-5-1-BU-1813-1863 Verified
Parish Registers SSX-Coates-Par-51-1-3-1-Temp-BA-1813-1881 Verified
Parish Registers SSX-Cocking-53-1-2-1-BA-1813-1871 Verified
Parish Registers SSX-Graffham-BA-1813-1873-93-1-2-1 Verified
Parish Registers SSX-Nuthurst-1813-1875-143-1-5-1 Verified
Parish Registers SSX-Slaugham-MA-Banns-1754-1812-483-1-1-4 Verified
Parish Registers SSX-Woolbeding-216-1-1-3-BA-BU-1763-1812 Verified
Parish Registers SSX-Woolbeding-216-1-1-4-MA-Banns-1754-1810 Verified
Parish Registers SSX-Woolbeding-216-1-3-1-MA-1813-1837 Verified
Parish Registers Transcripts
Parish Registers.
Parish Registerss
Parish registersSSX-Felpham-BU-1813-1882-84-1-5-1
Parish Regiters
Parish Regitsers
Parish Rgisters
Parish Tegisters
Parish: St Bartholomew, Burwash, Sussex, Marriages 1699 - 1717
Patish Registers
Pistersarish R
PRT Society
SSX-Balcombe-GR-1708-1747-234-1-1-4
SSX-ChichesterStMartin-BU-1813-1885-40-1-5-1
SSX-Climping-51-1-2-1-BA-1813-1876
SSX-Compton-Par-56-1-1-5-MA-1785-1809
SSX-Compton-Par-56-1-2-1-BA-1813-1875
SSX-Eartham-MA-1813-1836-74-1-3-1
SSX-Henfield-BU-1679-1695-100-1-1-2
SSX-Henfield-GR-1695-1721-100-1-1-3
SSX-Henfield-MA-1813-1837-100-1-3-1
SSX-Iping-BU-1813-1875-110-1-5-1
SSX-Iping-GR-1739-1799-110-1-1-2
SSX-Linch123-1-1-1-GR-1701-1780
SSX-Linch-123-1-1-1-GR-1701-1780
SSX-Linch-123-1-1-1-GR-1710-1780
SSX-Linch-123-1-1-2-GR-1781-1812
SSX-Linch-123-1-2-1-BA-1781-1812
SSX-Linch-123-1-2-1-BA-1813-1876
SSX-Linch-123-temp-BU-1814-1880
SSX-Linch-123-temp-MA-1849-1876
SSX-Merston-MA-1811-136-1-1-3
SSX-MidLavant-121-1-1-1-GR-1567-1748
SSX-MidLavant-121-1-1-2-BU-1735-1798
SSX-MidLavant-121-1-1-2-GR-1735-1798
SSX-MidLavant-121-1-5-1-BU-1813-1879
SSX-NorthStoke-GR-1565-1692-184-1-1-1
SSX-NorthStoke-GR-1692-1761-184-1-1-2
SSX-NorthStoke-GR-1736-1812-184-1-1-3
SSX-Rumboldswhyke-GR-1747-1812-161-1-1-2
SSX-Rumboldswhyke-MA-1754-1812-161-1-1-3
SSX-Singleton-174-1-1-2-GR-1728-1788
SSX-Singleton-174-1-1-3-Banns-MA-1755-1812
SSX-Singleton-174-1-1-4-BA-BU-1789-1812
SSX-Singleton-174-1-3-1-MA-1813-1837
SSX-Singleton-Linch-123-1-3-1-MA-1813-1834
SSX-Slaugham-GR-1749-1780-483-1-1-2
SSX-Slindon-BA-1813-1874-175-1-2-1
SSX-Terwick-194-1-1-1-GR-1571-1685
SSX-Warningcamp-GR-1572-1717-204-1-1-1
Sussex Record Society Transcript, volXXI, 1915
Sussex Record Society Volume XXI, 1915
Sussex Record Society Volume XXIV 1917
Sussex Record Society, Volume XXI
Sussex Record Society, Volume XXIV, 1917
Sussex Record Society, Volume XXV, 1917
Sussex Record Society, volXXI
Sussex Record Society. Volume XXIV 1917
Sussex Record Society.VolXXI
Sussex Records Society, Volume XXI
Transcript
Transcript of Parish Register
Transcript of Parish Register 1977
Transcript of Parish Register TR
Transcript of Parish Registers by L.W. Cunnington, 1945
Transcripts
West Suffolk Record Office SSX-HorshamHolyTrinity-BA-1879-1903-103-1-2-1 Verified
West Surrey Record Office
West Sussex office
West Sussex Parish Records
West Sussex Record Offfice
West Sussex Record Office
West Sussex Record Office
West Sussex Record Office SSX-ChichesterSt Martin-BA-1875-1903-40-1-2-1 Verified
West Sussex Record Office SSX-ChichesterStMartin-BU-1875-1891-40-1-5-1 Verified
West Sussex Record Office SSX-ChichesterStMartin-MA-1875-1899-40-1-3-2 Verified
West Sussex Record Office SSX-Eastergate-BA-1872-1902-76-1-2-1 Verified
West Sussex Record Office SSX-Eastergate-BU-1875-1900-76-1-5-1 Verified
West Sussex Record Office SSX-Eastergate-MA-1875-1900-76-1-3-2 Verified
West Sussex Record Office SSX-KingstonBySea-MA-1841-1900-115-1-3-2 Verified
West Sussex Record Office SSX-Thakeham-1874-1900-195-1-2-2 Verified
West Sussex Record Officw
West Sussex Record Offie
West Sussex record Ofice
West Sussex Records Office
West Sussex Redord Office
West Sussex Register Office
West Sussex Registry Office
West Suyssex Record Office
WestSussex Record Office

**Comment by Sherlock21** [comment]
In a way, this diverse collection of field contents is not surprising, its it?
As It has been left to individuals to put their own interpretation onto the title of the filed, and without any clues as to what the filed was being used for, what you see, is no surprise to me.

IF the field is to be used in any analysis in any manner, then there needs to be a definition of the structure of the content in the least - or perhaps drop the field completely.?

**Comment by SteveBiggs** [comment]
What Eric says is true. Most of the 171 variants in Sussex were entered before I became SSX coordinator. My interpretation of field 1 (called "Source" in WinREG) was the source of the images. To start with, I had my transcribers put 'Parish Register' but after a while I decided it more appropriate to put 'West Sussex Record Office' so even I have been inconsistent and every other coord will interpret it different again. Also, some transcribers have misinterpreted what I asked them to do and swapped field 3 and 4 or combined them into a single field 3.

As Eric says, we either need a definition of each field or just scrap them altogether.

**Comment by Captainkirkdawson** [comment]
I agree with your comments.
As a result the source information will be taken solely from what has been entered by the CC for the register.
Wrt to the comments in the header we will continue to just store them. When we rewrite as part of #1401 we will drop the field.
@EmJayFry should be aware of this.

**Comment by Captainkirkdawson** [comment]
No further action is proposed and this can be closed at next scrum
