### ISSUE TITLE
No link to Church or Register under Search Detail

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1389]

**Comment by edickens** [comment]
After selecting the Search Detail (this one is Sloane, 1878, BA, NI, Down) you have a link to the Place but not the Church:-
The Details link gives you:-
![Capture1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791acdeabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb70bbb258a488db5b98f4ec7e13e20f5c6.JPG)
Then if you take the link to the Place you get:-
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf218c4786b3b98d4bc7eb3837aa.JPG)
where it says that there is a Church but there is no link.
However, if you use "Transcriptions" and find the Place you get:-
![Capture2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/542531935e93a002006d0247/125516c66e82c728ace21e0d46cb958a379791acddabf301b44fff9e2c4533317346f6787586e22de61b2f595f581ca9415a5f44fdfadc2ba5e02e6c981e5ab38532022d8c6853beb2901eb80bbb258a488db5b98c49c2e93b21f5c6.JPG)
where there is a link to the Church.
I suggest that the Search Detail should be the same as the "Transcriptions" version.

**Comment by Captainkirkdawson** [comment]
Interesting. It has been this way since day 1.

Its because at the time of writing the code I could not see a way of doing the back links correctly since the same basic pages are used for multiple displays and the researcher pages do not have breadcrumbs.

**Comment by edickens** [comment]
And Sandra has just noticed because she has had to add some notes to the Church for the benefit of researchers.

**Comment by Captainkirkdawson** [comment]
See also #719 for the register link

**Comment by Captainkirkdawson** [comment]
Code integrated into flexible_csv branch

**Comment by Captainkirkdawson** [comment]
Given that we are now linking to both Church and Register, It is important that those collections have meaningful content.
Propose to write rake tasks to export the content of the collections to csv records in a file for off line analysis.

**Comment by Captainkirkdawson** [comment]
Rake tasks have been written,  output for churches has been forwarded to EricD?B and Steve

**Comment by Captainkirkdawson** [comment]
EricD wrote
I've divided up Kirk's file into counties and will sort out any Denominations that do not match the standard list.  But, as Kirk says, there are a lot of Churches without denominations, and some weird spelling of Church Dedications.  So I was proposing to send this message, with my corrected file, to the CC.

We have been going through the database and trying to tidy it up so that it is consistent across all counties and provides meaningful information to researchers. 

Attached is a file containing details of all of this county's churches which are on the database. 

Will you please go through it, log in to website and make the following changes if applicable:- 
- See if the Church Dedication looks correct.  There is no need to do any further research to confirm this. 
- See it the Church Denomination is entered or not.  I have corrected any whose format does not match the standard pick-list. This information is presented to researchers so is needed.  If you come across a Church Denomination that is not in the list, let me know and I can add it. 
- If you have the website address of the Church, then enter it. This helps researchers to get more information, and helps us to get a better working relationship with the Church.  But it only needs to be entered if you have it.  There is no need to search the web for it. 
- If any of the "datemin" fields are zero, this means that there is a date error in the file.  There is an Action to locate this and so please make the correction. 


I suggest that you save the attached file and use it to make notes on what you have done.  It could also be a very useful reference file for all the places and churches set up in your county. 

Many thanks, 


Following my comments in my Newsletter, Julie has come back to me and offered to do NFK.  There are no wrong Denominations there, in fact there are hardly any.  So I have sent her the NFK file.

**Comment by edickens** [comment]
I have forwarded the file to EricB as data manager and I keep him informed.  I'm doing the tidying up in my role as looking after coordinators.

**Comment by Captainkirkdawson** [comment]
A companion copy for the registers collection has been forwarded to the Erics and Steve
