### ISSUE TITLE
Image file name conventions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1415]
Decide and document the convention for image file names that will be short, to maximise number of images that can be uploaded at one time

**Comment by edickens** [comment]
Image names have had a conventional format of AAA-B_C-D-E_F where AAA is the chapman code, B is the place, C the Church, D the record type, E the year range and F the page number.  The Register Type is held at the end of the folder name in which the image is stored.
The reason for such a full name was because in the image server all images for a Church/Register Type have to be held in one folder with no sub-folders.  Also, when allocated to a transcriber they are all put together in their personal folder and could be from different counties and places, so a full name is needed.  Similarly if a transcriber downloads the image, it is likely to go into one folder and so the filename needs to be unique.  Finally the image filename is needed to be able to match a transcription entry to the image.
To design a shorter version of the images filename I think it will be necessary to hold images in sub-folders which are defined by the image group.  So in my definition above, everything except the page number could be the sub-folder name.
But there are implications.  It will mean that there are a lot of images being processed which will just be page numbers.  To avoid confusion, I recommend that all uploads and downloads and links in the transcription entry should check that they are held in a sub-folder which should be the name of the Image Group.
Thoughts?  EricD

**Comment by edickens** [comment]
An alternative is for the website to always precede the page number by inserting the image group name.  That would be necessary for any uploading to the image server and would create the necessary full image filename.  The images to be uploaded would then only need to be a page number.  All downloads are one image at a time and now have the full image filename.

**Comment by SteveBiggs** [comment]
Every place/church combination has a 3 letter code used for the batch names, so the naming format Eric states could be reduced down to 12 characters (if we omit the date range) but still kept unique and meaningful. For example;
SSXALBBA0001.

**Comment by edickens** [comment]
Good idea.  This is also the code to be used in the transcription batch filename.
We do need to divide up the year ranges because they are the different register books, but we do not need to quote the actual years, which can be stated in the Image Group name.  We also do not need a four digit page number, so perhaps have a format such as:-
SSXALBBA3001.jpg where the 3 is say the third range of years and all images would be within the Image group of Albourne PR/SSX-Albourne-BA-1813-1900-226-1-2-1
We need to count the .jpg in working out how many digits.  This format would take 16 digits, so we could upload 90 images in one go within the 1,500 character limit.  (If the limit could be increased to say 1,700, that would allow for 100 images at a time, which is a nice group to upload.)

**Comment by edickens** [comment]
Can I take this as agreed?
If so, will Kirk please increase the limit to 1,700 characters.  And Steve, will you please include this in your write-up of the image processing system.
When done, I will start uploading the 5GB of images I have waiting and will do them under this new convention.
Thanks ED

**Comment by Captainkirkdawson** [comment]
Sorry Eric I had not been paying attention while bug fixing. There are a range of suggestions in the discussion including actions by the app  (inserting information) and actions by the image server (creating a sub folder structure) to just increasing the character limit. 

What changes of the system are you requesting?

**Comment by edickens** [comment]
Hi Kirk,
Only to increase the limit from 1,500 characters to 1,700.  Steve and I have agreed a 16 digit fixed format (including the .jpg) so that will allow batches of 100 images.  The extra 100 is because some images may say "end" or "cover" after the image number.  So a little leeway.
The rest of the conversation was about how to decide on a format, so not relevant with this fixed file naming.
Eric

**Comment by Captainkirkdawson** [comment]
OK Give me a couple of hrs

**Comment by Captainkirkdawson** [comment]
Raised to 1800.

Let me know is there is an issue at this limit

**Comment by edickens** [comment]
Have uploaded batches of 100 images.  No problem.
Thanks
Eric

**Comment by richpomfret** [comment]
To add new story for image server documentation.
