### ISSUE TITLE
Alphabetic range selection for some Source Navigation

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1443]

**Comment by edickens** [comment]
I have been working on SOM and there are over 200 places in the Image Server.  It would help if there was an alphabetic range selection, as there is with places.
Also, when going back up the breadcrumbs, it would be helpful to be at the same place as before, rather than having to scroll down again.

**Comment by PatReynolds** [comment]
@bev-fc is this something you could do? TY.

**Comment by bev-fc** [comment]
I will do the first one - "It would help if there was an alphabetic range selection, as there is with places"

for the second one - "Also, when going back up the breadcrumbs, it would be helpful to be at the same place as before, rather than having to scroll down again", I do not know how to do it, if anyone can help me out?

**Comment by bev-fc** [comment]
@edickens after enter 'Manage Images', there are 8 buttons, do you want them to be limited within the place you selected or leave as it is?

**Comment by SteveBiggs** [comment]
If we are to have an alpha-range, I suggest it be similar to when you click Places:
![image](https://user-images.githubusercontent.com/25303607/41162095-cf3da580-6b2c-11e8-8879-694a3ccfe353.png)
but the text should say "Select a Place Range"

**Comment by bev-fc** [comment]
@SteveBiggs what struggled me is, the original design is to have an overall picture of the status of the whole county in one screen, when it's divided into places, then the person needs to know exactly if this place has unallocated/allocate_request etc groups, otherwise he/she needs to go through places by places by alpha character to check.

**Comment by edickens** [comment]
Thinking about this now, perhaps a range selection is not needed.  Let's see how it develops when we get more images.
The list could be a lot shorter if those Sources which are completely transcribed can be omitted.  Perhaps the default should be to list all Sources which have images that are not complete, but then have a 9th button to list all Sources for the county.
What might be more important is the "Return to where you were".  For example, go to "Walburton", select "Image Server", then use the breadcrumb and find the next place in the list "Warminghurst".
@SteveBiggs what do you think?

**Comment by SteveBiggs** [comment]
Actually, for the way I use it in practice, I am usually looking for a specific place to allocate because I do it in a predetermined place order which is not alphabetical. So I have to scroll down to say, Walburton. Therefore an alpha-range selection would be quicker. If the CC were allocating places in alphabetical order, the alpha selection would be even more useful.
I don't think it's necessary to see all places in one screen (well you can't anyway because you have scroll a long way down), but you need to be able to quickly navigate to the place you want.
With the alpha range selection, all places under letter 'A' would be visible exactly as they are now. Then you just go back to the alpha-selection and pick 'B', etc. So it's very similar to the current listing, just one letter at a time.

**Comment by bev-fc** [comment]
I will apply alpha character to all 8 buttons under 'Manage Images'

**Comment by SteveBiggs** [comment]
@bev-fc the range selection should come before you get to the buttons. So you select 'A' then you see all places starting with 'A' in a list with the 8 buttons at the top as they are now.

**Comment by SteveBiggs** [comment]
Actually, this is more complicated than I first thought! When you click for example List Unallocated Image Groups, this needs to be ALL unallocated not just for the letter selected. The same applies for some of the other buttons such as List Allocate Request .... 

I think it best to hold off on doing anything on this until we think this through a bit more.

**Comment by bev-fc** [comment]
@SteveBiggs yes this was my question. I applied code to have range selection after click 'Image Server' to limit output, but if apply to all 8 buttons too, it seems opposite to original design.

**Comment by SteveBiggs** [comment]
Yes, sorry Bev, I didn't give it enough thought. Please leave as is for now.

**Comment by edickens** [comment]
@SteveBiggs Should @bev-fc just do the "Return to where you were"?  See mine of an hour ago.

**Comment by bev-fc** [comment]
I said yesterday 

for the second one - "Also, when going back up the breadcrumbs, it would be helpful to be at the same place as before, rather than having to scroll down again", I do not know how to do it, if anyone can help me out?

**Comment by Captainkirkdawson** [comment]
@bev-fc 

We do the going back to a specific row in an index display in a number of models.The breadcrumb part can get a little convoluted.
It all starts in an index display by assigning a tag to each row being displayed. Then using that in the breadcrumb with an anchor on the return to the the index display.
Will send you an email with an example.

**Comment by Captainkirkdawson** [comment]
@edickens @SteveBiggs  Return to where you were on source list implemented by Bev
applied to master in test3 for testing

**Comment by edickens** [comment]
Perfect.  TY.  Thanks EricD
As a matter of principle I think this routine should be done for any report that is likely to produce a long list of entries.
