### ISSUE TITLE
Update Transcriber registration page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1456]
Replace "we will not share them with any outside organisation." with "Please read our Privacy Notice for information on how we will protect and use your data.".

**Comment by richpomfret** [comment]
Ready to push to Test3.

**Comment by smrr723** [comment]
On test3 with #1426 currently - needs testing.

**Comment by SteveBiggs** [comment]
The wording on test3 is the same as production, i.e.  "we will not share them with any outside organisation."

**Comment by smrr723** [comment]
Sorry Steve - pulled this off test3 today to let Vino push her code up before she leaves.  I've merged this issue into production since it was a text-only edit - changes should now be reflected here [https://www.freereg.org.uk/userid_details/transcriber_registration?](https://www.freereg.org.uk/userid_details/transcriber_registration?).

**Comment by SteveBiggs** [comment]
OK, looks good on production.
