### ISSUE TITLE
Ability to search all counties in a country

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#1476]
E.g. select Scotland  to search all Scottish counties, to help narrow down results?

**Comment by Captainkirkdawson** [comment]
How would this narrow down the results?
Can you imagine searching for Smith in England?

**Comment by DeniseColbert** [comment]
With a date range and one record type selected, there would be fewer records to search. With a name like Smith, I imagine it may still return too many results though. Is there a way around that? Maybe forcing a forename to be entered?

**Comment by Captainkirkdawson** [comment]
I am sorry that I cannot see the benefit. 
We already have a search of all counties.
"You can search for a named person (ie both forename and surname) in all counties if you provide a year range and select just one of baptism, marriage or burial. "
The suggestion to restrict it by countries would actually take more resources because we would actually have to search each of the counties for a country. The all counties search uses a specially constructed index that does not involve counties.

**Comment by Sherlock21** [comment]
I don't see any benefit either. All there will be is loads of (unnecessary) extra work.

**Comment by richpomfret** [comment]
Even if this was considered a compelling feature, server death means it's a no-go.
