### ISSUE TITLE
Add True to options

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1499]
A number of logical entries permit Y Yes as options we should expand to include true

**Comment by Captainkirkdawson** [comment]
Deployed to test2.

PRIVATE_BAPTISM_OPTIONS = ['y','yes', 'private', 'true', 'private baptism']

MARRIAGE_BY_LICENCE_OPTIONS = ['y', 'yes', 'licence', 'by licence', 'by_licence', 'marriage_by_licence','true']

MARKED_OPTIONS = ['y', 'yes','marked','true']

**Comment by Sherlock21** [comment]
Kirk

Now we are cooking with gas….

I have completed testing Marriages files and both in the positive sense and the negative sense, this works correctly :( ie: as I expect)

Progressed to Baptisms: If you are watching the system emails, you will see I/ had a slight snag to start with - of my own making due to forgetting to get the Register code right!

However: all ended well - again in both senses of positive and negative.

SO to your last item: I need a clue here please as to where these occur other than in the list of values inthe BA and MA files above?


Eric


On 15 Jul 2018, at 04:22, Kirk Dawson <notifications@github.com> wrote:

Deployed to test2.

PRIVATE_BAPTISM_OPTIONS = ['y','yes', 'private', 'true', 'private baptism']

MARRIAGE_BY_LICENCE_OPTIONS = ['y', 'yes', 'licence', 'by licence', 'by_licence', 'marriage_by_licence','true']

MARKED_OPTIONS = ['y', 'yes','marked','true']

**Comment by Captainkirkdawson** [comment]
Thanks Eric that is the complete set I believe although Alison has
suggested an addition

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Alison suggests adding private_baptism

**Comment by Sherlock21** [comment]
Ah, I see what you mean now.

I: dont see why its a feature which is only available on online Edit. - it needs to work from a new Spreadsheet on upload.

I just tested out the options on a new upload:

All work correctly EXCEPT private_baptism which gives the result: false.

Maybe its my underscore char??
in which case i would take the easy option and remove it from the options since the field is clearly labelled what its about, and yes,  no,  private, true are all that should be needed.


EB


On 16 Jul 2018, at 15:19, Kirk Dawson <notifications@github.com> wrote:

Alison suggests adding private_baptism

**Comment by Captainkirkdawson** [comment]
I had not coded private_baptism yet. These options are only for file loads. On line can be a pure boolean

**Comment by richpomfret** [comment]
Will be added as part of flexible csv branch.
