### ISSUE TITLE
23P Deploy UCF

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1511]
Progress/implement UCF AFTER reviewing possible KO effects to performance
needs #1134
needs #1178
required by #1135
needs #1259

Priority 23 (1	4	10	8)

**Comment by benwbrum** [comment]
Assessing this so far, it looks like the base functionality works as expected:

![freereg_ucf_base](https://user-images.githubusercontent.com/199961/47438650-80157900-d770-11e8-8bd2-2bedf0522596.png)

The next step is to address rebuilds after online editing in the referenced issues.

**Comment by Captainkirkdawson** [comment]
Basic functionality is not disputed. 
However it was never turned on (implemented) because of the of the need to address the impacts of on line editing/deleting.

**Comment by benwbrum** [comment]
That's what I'm working on; it's been so long since I touched this code that I needed to establish where it was working (or not) already.

**Comment by Captainkirkdawson** [comment]
Encountered an issue with regex dying because of unbalanced brackets in the original data record. Put a rescue into the code for it to continue

**Comment by Captainkirkdawson** [comment]
Currently thinking of doing a ucf_list refresh on production the week of Feb 24-29 2020 providing to that.
The search of ucf would not be activated until after the refresh.

**Comment by edickens** [comment]
For my general interest and so that I can answer questions after UCF has gone live:-
How does it work?  It looks as if a new set of names is created, but what are the rules?  Was there ever a specification of the system?  My understanding was that FR1 and the other projects handled UCF in a very simple way.
I'm not suggesting that this system will not work or needs changing, and it is very likely that it will be much better than the one in FR1, but we need to know how it works and if something needs to be written into the County Coordinators Help.
Thanks EricD

**Comment by Captainkirkdawson** [comment]
@edickens these are general questions. Many are the subject of specific stories in the epic 2224. More specifically you can review story 1135 Document rules for a ucf match; that story contains a link to a document by Ben https://docs.google.com/document/d/14iIoZtEjfN_CgDUwc6X9qjwUQIxsnHK568QseblTNRc/edit#heading=h.voiqdnxhjmht

**Comment by Captainkirkdawson** [comment]
Have refreshed the ucf field on test3; took 2 days. Production will be longer as we must do it more slowly.

**Comment by Captainkirkdawson** [comment]
UCF fields on production have been completed. We are ready to turn on UCF record display in production
