### ISSUE TITLE
Physical File Processing - Processor Stopping unexpectedly with very little Error info

### ISSUE THREAD

**Issue by smrr723** [FreeUKGen/MyopicVicar#1605]
The CSV processor stopped processing files for approx 12 hours or so, starting between 10am & 11am on Sept 28th.  I have downloaded a copy of the passenger.log file from that day, if required.

The issue has resolved itself, but there was very little feedback from the logs, and nothing shown in errbit, to notify of what the issue was, although we suspect it was caused by a problem file that was uploaded.

**Action**: Determine the root cause of the issue to prevent re-occurrence, if the cause can be found in the passenger log file errors.  
needs #1621

**Comment by smrr723** [comment]
@SteveBiggs @Sherlock21 - FYI, related to issues from this weekend, in case you want to add anything to this story.

**Comment by Sherlock21** [comment]
I suspect that it had stopped prior to me trying to upload file WOCCRLMA.csv in the userid of davejo - because later in the morning, when I tried to load that file into T3, it worked OK straight away.
The only thing I had done prior to this was to use my "Super completely delete a batch" - on an STS file (but I don't remember the filename), which eventual  gave me the Gateway timed out even thought he file was just over 5000 record I think. The file concerned had gone when I got back online later. - if this is any clue to you.

**Comment by Captainkirkdawson** [comment]
The processor  does  log messages to passenger  log  it crashes

**Comment by Captainkirkdawson** [comment]
@smrr723  @Sherlock21 
There is no evidence in the logs that the processor actually crashed. 
Given that and that there were no multiple message files created and the fact that the processor "appeared" to recommence with no intervention I believe the problem was caused by the file/entry deletion action undertaken by @Sherlock21. 
ie the processor did not stop but simply slowed down.
Such deletions are always likely to cause significant delays in files being processed as indexes are being updated in real time. It is for this reason that the file/entry deletion is available only to the DM or SA with the recommendation that it only be used in quiet times.
To do improve documentation of processor actions and how to diagnose issues. Make the error message on a crash "#{csvfile.userid}\t#{csvfile.file_name} line #{line} crashed the processor. <br>" more visible

**Comment by Captainkirkdawson** [comment]
Have added code such that the error message on a crash contain the key words FREEREG:CSV_PROCESSOR_FAILURE:
Added crash message to user message file and to update file and continue processing with next record and "hopefully" finish file and delete from waiting to be processed list.

**Comment by Captainkirkdawson** [comment]
Documentation has been updated.
https://docs.google.com/document/d/1tS88di-Q0dQTlUcNCbY7rEd3EC0ig2P0oxckXzUql-Y/edit

**Comment by Sherlock21** [comment]
Thank You


On 14 Oct 2018, at 18:52, Kirk Dawson <notifications@github.com> wrote:

Have added code such that the error message on a crash contain the key words FREEREG:CSV_PROCESSOR_FAILURE:
Added crash message to user message file and to update file and continue processing with next record and "hopefully" finish file and delete from waiting to be processed list.

**Comment by richpomfret** [comment]
Ready for deplpoyment
