### ISSUE TITLE
Unexplained zero dates

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1611]
![zero date](https://user-images.githubusercontent.com/10379655/46605000-ed2ddb00-caef-11e8-82f8-80f443876e26.jpg)
needs #1581

**Comment by SteveBiggs** [comment]
I've experienced similar issues - sometimes a reprocess of the file fixes the zero dates, but other times each individual "zero" record needs to be edited to force it to reprocess and correct it. We need to find the underlying cause.

**Comment by PatReynolds** [comment]
Can be cleared by making some edit in the record - e.g. putting a full stop in the notes field.

**Comment by suffolkroots** [comment]
As will be seen from the explanation of the problem, it has happened because of an edit.
As Steve so rightly says, we need to find the underlying cause.

**Comment by Sherlock21** [comment]
I thought that we had fixed this one just a few weeks ago? Or did it not get loaded into Production? - only Kirk & Scott will know.

Meantime if this is the same issue as existed as over the past months, then the solution that always worked then, was to Reprocess the file - using the Reprocess action or by uploading a Replace version of the file.

**Comment by Sherlock21** [comment]
FYI
I have uploaded Ali's file into T3 in my name, (i.e. with the Edited items in it) - i.e. exactly as it now appears in FR.
There are NO errors or flags of any sort  present - thus confirming there are NO errors in the data now. So the issue must remain within the Proocessing of an Online Edit action.

**Comment by Sherlock21** [comment]
Can we please have a speedy coded solution to this problem?

There are much more useful things for CC's and me to do than chase round trying to get one of the workarounds to fix these Zero Date Errors - e.g. like Reprocess file (which does not always work for some reason). The next option is for the CC to get me to delete the Zero Dates /Error file, and reload it - A total waste of our time.
ELSE the Zero Dates flag will be ignored by CC's and myself because sometimes it will be genuine, and sometimes it will be one of these false messages.

This latter option amounts to the alternative being to let the data descend into an unreliable state. - which we don't wish to see happen.

**Comment by SteveBiggs** [comment]
Email from Eric Booker:
At your next Exec meeting, could you please get some action on this above issue. despite Pat closing it off, it is not included elsewhere so far as I can see, and the problem certainly does continue still.

**Comment by Sherlock21** [comment]
SO are you saying that everyone should NOT update dates in a record by using the Edit Online tool?

That leave users the only option of doing date changes of all kinds, in their file, and doing a reload does it not?
Or have I missed something?

**Comment by Captainkirkdawson** [comment]
This is the same issue as #1661. The code fix for that issue has been developed. It is deployed to test3 for review
