### ISSUE TITLE
(For Discussion) Create and About page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1659]
Looking for a quick copy-and-paste text to put elsewhere, realise there is nothing on the FreeREG site which explains the project, aims and ambitions!

**Comment by Captainkirkdawson** [comment]
What is wrong with current page
About
The aim of FreeREG is to provide free Internet searches of baptism, marriage, and burial records, which have been extracted from parish registers, non-conformist records and other relevant sources in the UK.

The recording of baptisms, marriages and burials in parish registers began in England and Wales in 1538 and is separate and distinct from the civil registration process that began in 1837. (The latter is covered by our companion project, FreeBMD.) We want to make it easier for researchers, no matter where you are in the world, to find a specific record relating to your ancestor within a church register.

FreeREG is a relatively new project but due to the work of a dedicated set of volunteers we already have some 37 million records in the database. Even so, you should not expect to find all your ancestors in the database yet.

FreeREG is a part of the Free UK Genealogy Charity and a companion to FreeBMD (which is a database of the General Register Office (GRO) birth, marriage and death indexes from 1837) and FreeCEN (which is a database of census information).

Membership
You do not need to be a Member to search our database. However, to make FreeREG an effective tool we are in urgent need of volunteers willing to undertake the transcription of registers or make available transcriptions that they have already completed.

Volunteer

Please note that we cannot accept donations of images purchased from commercial sites such as Ancestry, FindMyPast, Scotlands People, and so on, because the licence accepted by the purchaser permits only personal use of those images and their contents.

Search
We provide an internet-based search for events relating to a named person in up to three counties at a time. The search may be narrowed to a specific place within a single county and for a year range of your choice.

Alternatively, you may search for a named person in all counties if you provide a year range and select one of baptism, marriage or burial. In either case, only records that match the details in the search form will be displayed.

It is not possible to request a search that provides all of the records for one church or parish. Neither can you make a search for everyone whose name begins with the same letter (or letters).

Browsing
For copyright reasons, we cannot allow you to browse all the transcriptions from a register, or a section of the transcriptions. We do recognise that this can be useful to genealogists: if you want to find out if there is an illegible record at a specific date (for example). You can ask us such specific questions through the Contact form. For other use of such complete transcriptions, where these exist, you should contact either the appropriate local County Record Offices or the relevant Family History Society.

Accessibility
You will notice some changes to the site as we seek to improve access to FreeREG, especially for mobile phone users and for visitors with a range of disabilities. See our Accessibility statement for more details.

**Comment by AlOneill** [comment]
The first few paras on
https://www.freereg.org.uk/cms/about
offer some of what you are looking for.

@PatReynolds What would make this explanation better?

**Comment by AlOneill** [comment]
OK — the number-of-records-transcribed figure needs updating!

**Comment by PatReynolds** [comment]
Ah - sorry - the 'About' section dissappears when one is logged in!  I will close this and add a new story for revising the figure!

**Comment by richpomfret** [comment]
Shall close. No need for this.
