### ISSUE TITLE
More zero date issues

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#1749]
Perfectly good files listed as having zero date entries are still being included in zero date round up.

See attachment.
![zero date query](https://user-images.githubusercontent.com/10379655/50632742-ce997d80-0f40-11e9-8295-ea2c98e2f0d2.jpg)

**Comment by suffolkroots** [comment]
The above file when uploaded as is to T3 shows no zero date. (Uploaded as WRYBAM99.CSV)
![image](https://user-images.githubusercontent.com/10379655/50723858-48656e80-10db-11e9-9577-950970f00122.png)

**Comment by Captainkirkdawson** [comment]
The original entry on upload on 9 November was  

WRY,Barnoldswick,St Mary le Ghyll PR,,11 amy 1810,15 Oct 1810,Ralph,M,John,Ellin,SLATER,STARKIE,Salterforth,Blacksmith,2nd child,,WRYBAMPR-1766-1812-83

Clearly in error and creating the zero (null) year 

On 15 November there was an edit to the record to correct it.
WRY,Barnoldswick,St Mary le Ghyll PR,"",11 May 1810,15 Oct 1810,Ralph,M,John,Ellin,SLATER,STARKIE,Salterforth,Blacksmith,2nd child,"",WRYBAMPR-1766-1812-83

There were a number of other editd to the record leading up to the last one on 3 January 2019. The record currently is 

        "_id" : ObjectId("5bed7217f493fd443c9992fb"),
        "error_flag" : "false",
        "register_entry_number" : "",
        "birth_date" : "11 May 1810",
        "baptism_date" : "15 Oct 1810",
        "person_forename" : "Ralph",
        "father_forename" : "John",
        "father_surname" : "SLATER",
        "father_occupation" : "Blacksmith",
        "mother_forename" : "Ellin",
        "mother_surname" : "STARKIE",
        "person_abode" : "Salterforth",
        "notes" : "2nd child",
        "film" : "",
        "film_number" : "WRYBAMPR-1766-1812-83",
        "person_sex" : "M",
        "register_type" : " Parish Register",
        "county" : "Yorkshire, West Riding",
        "place" : "Barnoldswick",
        "church_name" : "St Mary le Ghyll",
        "private_baptism" : false,
        "bride_marked" : false,
        "groom_marked" : false,
        "marriage_by_licence" : false,
        "year" : null,
        "line_id" : "JHissett.WRYBAMBA1.CSV.1208",
        "record_type" : "ba",
        "file_line_number" : 1208,
        "record_digest" : "f0x6qBi06N5tKkuJ7xcb+A==",
        "u_at" : ISODate("2019-01-03T08:28:14.436Z"),
        "c_at" : ISODate("2018-11-15T13:18:15.649Z"),
        "freereg1_csv_file_id" : ObjectId("5be5d9bbf493fd5d2d66eea3"),
        "transcribed_by" : "John Hissett",
        "credit" : "Donation from ManCity"
}

My summary is that the file and record did initially have a zero year entry. The initial correction was done at the time BEFORE my november code corrections to the on line edits. *The earlier code did not update the year field so it remained null).

The reports were all correct based on the data available to them.

The test3 result is a red herring as it is processing the corrected record from scratch.

The subsequent attempts to re update the record did not change the record since they likely did not include a date change.

Final comment the source of apparent issue was the error in the on-line update code which was fixed and deployed in mid november. 

Solution on specific record.

I changed the date of the birth in an on line edit to 1811 and then changed it back to 1810 in a subsequent on line update.

The record now contains the 1810 year and the file shows the correct minimum date and the file no longer appears in the list of those with zero years.

**Comment by suffolkroots** [comment]
Thanks Kirk for a speedy resolution to this issue.
However, your explanation re the solution to the 0 date problem is as clear as mud to me, as I have no access to such records of corrections as you show above. All I see is the uploaded date. There is no communication concerning online corrections.
Are you suggesting that we should keep our own personal records re such online corrections of which we are aware?
I have now changed a date and back again in the non-offending files.

**Comment by Captainkirkdawson** [comment]
Ignore my explanation. I am not suggesting any record keeping by yourselves.

I do suggest a solution for situations where a zero date appears in a batch that was corrected on-line prior to 23 November 2018. (You do have access to that information). 
Do an on-line edit of a date to a different year and then on-line edit it back to what it should be.
