### ISSUE TITLE
Add a reminder to message system page for transcribers to contact their SC in the first instance

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#1804]
p 0 7 8 1 : 16

**Comment by edickens** [comment]
Some transcribers are using the message system for asking for Help and other questions which their SC can answer.  May I suggest that if someone is Logged In, and they create a message or use the Contact Us, that they get a message to say "Have you already tried contacting your Syndicate Coordinator?"

**Comment by suffolkroots** [comment]
As the new messaging system seems to have been designed to reduce personal interaction between transcribers and CCs, "Have you already tried contacting your coordinator" raises an interesting point. I personally am very disappointed in this new system where the postman comes to my door, only to inform me that I have a letter but I must go to the post office to collect it. We have a word in YKS---daft.

**Comment by Captainkirkdawson** [comment]
What I find really interesting is that I received a number of replies from transcribers to the General Message on software that said they had been unable to contact their SC so they had stopped transcribing or their SC had stopped sending them material to transcribe. (Not you Ali)
As for the above comment we only use the mail because we have been told that coordinators do not log on to the system to see what is going on. The mail is a gentle reminder to do so. There is nothing impersonal about the actual communication that is up to the style of the SC/transcriber.

**Comment by Captainkirkdawson** [comment]
I am unsure what is being referred to as message system in the description.  Transcribers have no access to the message system to originate messages. We added the Communicate action to enable them to contact members of the team but we have NEVER told anyone how to use  it. So we should expect random usage.

Why should we be suggesting they should use the Contact us??? That was for researchers. 

Similarly we have not told CCs how to use the reply capabilities of the Contact system system

**Comment by edickens** [comment]
I was asked to raise this because I keep getting transcribers contacting me for help.  The first port of call should be their SC.  The problem might be that because I am retired they get a quicker response from me.  Perhaps I should only answer once a week.

**Comment by SteveBiggs** [comment]
To answer Ali, the SC message system we have introduced is mainly for when you need to send a broadcast to all your transcribers to say something like you'll be on holiday for two weeks, etc. because it is always an up to date list of all your active transcribers. For all individual communication between me as SC and one of my transcribers, I use my personal email system as I always have done.

**Comment by SteveBiggs** [comment]
What's more important to use the website message system for is comms with researchers, because it allows us to check and ensure that researchers' questions are being answered. Some coordinators such as yourself, Ali are very efficient at dealing with queries, but unfortunately, there are many counties where researchers' contacts are going unanswered and it's very difficult to know which ones they are if all comms is outside the FR system.

**Comment by suffolkroots** [comment]
The interesting point in these posts is the apparent lack of knowledge re coordinators' active state. We have, on a regular basis, to confirm our email on the website, but what use is made of this info? Are non-responders followed up in any way? Perhaps a personal email to all CCs every 6 months requiring a response might be helpful, and would highlight the nil returns. Further contact could then be made, eg through their county's active transcribers, to ascertain any recent communication. Should there have been none, consideration might be given to the re-assignment of transcribers.

**Comment by richpomfret** [comment]
Vino to await multi-modal rollout before this can go into master.

**Comment by richpomfret** [comment]
Has been completed and deployed to live.

**Comment by richpomfret** [comment]
@SteveBiggs to test this (it is already live).

**Comment by SteveBiggs** [comment]
Could the following changes please be made:

- Change the wording to "**For transcribing queries, please contact your Syndicate Coordinator using the Communicate Action**" 
- Use bold font
- Can "**Communicate**" be made a hyperlink to the action?

Thanks

**Comment by richpomfret** [comment]
@Vino-S one for you to change as per the above request. Moving back into 'in progress'.

**Comment by richpomfret** [comment]
@Vino-S please comment/update when you get a chance.

**Comment by richpomfret** [comment]
Ready for testing on TEST2.

**Comment by richpomfret** [comment]
Tested and working fine.

**Comment by SteveBiggs** [comment]
Clicking the Comnunicate Action button opens a new browser tab here:
![image](https://user-images.githubusercontent.com/25303607/66498797-9702c780-eab6-11e9-9f31-ef6bfae261dd.png)

The Communicate -> Create Communication action goes here:
![image](https://user-images.githubusercontent.com/25303607/66498945-d03b3780-eab6-11e9-8bb9-5cb69b2920b5.png)

Are these different pages?

**Comment by richpomfret** [comment]
Ready for deployment - as it is the same page
