### ISSUE TITLE
Why are we not found by search engines - update SEO

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#1844]
Do a google search for parish registers or church of england registers or anything similar and we never appear. Why?

**Comment by smrr723** [comment]
I see us appear second in Google for "Parish Registers".  On further inspection, it looks like we could do with an SEO review of our websites.

<img width="749" alt="screenshot 2019-02-12 at 20 23 05" src="https://user-images.githubusercontent.com/2768445/52665692-11695080-2f04-11e9-9fa5-532df0d186ee.png">

A few initial observations:-

- The title of the main page for FreeREG is "Search Query | FreeREG", which isn't the best description of our website for new users, or search engines.  FreeCEN2 has "FreeCEN - UK Census Records" which is better.  Titles carry a lot of "weight" in the Google search algorithms.
- The main logo in the header uses the code `<h1 class="accessibility">FreeReg</h1>` which again isn't very descriptive, and should be changed to match the title.
- It looks like our homepage might be getting split (therefore "diluted") into two different pages and treated as such by Google.  Doing a search for parish registers as above shows our home page as being `https://www.freereg.org.uk/search_queries/new` whereas a search for "FreeREG" shows a link to `freereg.org.uk`.  I believe best practice for this is to do a permanent 301 redirect from one of those URLs to the URL that we want to use, to avoid two URLs existing for the same page.
- There is no description of our home page showing in Google search results as shown in the image below.  Description is also weighed quite heavily by Google.  This is supplied by the code in our head tags `<meta name="description" content="The FreeREG project provides free online access to transcriptions of parish registers and similar resources from England, Scotland and Wales.">` but it's not currently being shown because we are blocking Google from crawling our homepage in our `robots.txt` file - which isn't recommended.

![screenshot 2019-02-12 at 20 07 57](https://user-images.githubusercontent.com/2768445/52666035-0105a580-2f05-11e9-9c48-bbb40ce6f527.png)


I'm sure there are also other things that would be picked up if we did a full site review, which would help us appear higher in Google.

**Comment by Captainkirkdawson** [comment]
But most search will not, mind you BMD does no better.
![seo5.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919576c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10a4b2831aba01ba208f4a81b7bb8d44d2a5.JPG)
![seo4.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919577c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10a4b2831aba01ba208f4a81b7bb8d4ed2a5.JPG)
![seo3.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919570c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f13acb2831aba01ba208f4a81b7bb8d48d2a5.JPG)
![seo2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919571c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10abb2831aba01ba208f4a81b7b48a4dd2a5.JPG)
![seo1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919572c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f13acb2831aba01ba208f4a81b7bb8d4fd2a5.JPG)

**Comment by SteveBiggs** [comment]
A search in DuckDuckGo for parish registers puts us fifth:
![image](https://user-images.githubusercontent.com/25303607/52666940-7d998380-2f07-11e9-86bf-7b8210f467c0.png)
but it says "We would like to show you a description here but the site won't allow us."

**Comment by Captainkirkdawson** [comment]
records and register gives different results. Interesting that as Scott noted we can have 2 entries; 1 with detail 1 without!
![seo6.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ecbbfc82b317f7d9ad93dc/125516c66e82c728ace21e0d46fb919575c0cfeb9ffbb049a15ee4d6730472202c07a22e29dcb770ef1579545f5d4eac405b0a44ffaf9b37b4f46d2ede0356b49b381d66cc2f10a4b2831aba01ba208f4681b7b98345d2a5.JPG)

**Comment by Captainkirkdawson** [comment]
We have the following site map for ses
https://www.freereg.org.uk/freereg_contents/new
https://www.freereg.org.uk/search_queries/new
https://www.freereg.org.uk/cms/refinery/login
https://www.freereg.org.uk/cms/donate
https://www.freereg.org.uk/cms/about
https://www.freereg.org.uk/cms/help


Also Scott we do have a referral from freereg.org.uk/
