### ISSUE TITLE
20 Hide search_id parameter from URLs

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#1854]
As discussed in #1144, the `search_id=......` parameter that appears in the URL of an individual record's page is now optional, but is certainly ugly.  If researchers use the citation generator, that parameter is removed, but if they cut-and-paste the URL they see in their browser, it's present.

By moving the search_id into the session--and carefully replacing it whenever a new search is performed--we can hide the parameter from the URL.

E1, U3, S9, C7: P20

**Comment by Captainkirkdawson** [comment]
The search is already a session parameter. It always has been! We just never used it. It is set in the create action


On February 20, 2019, at 6:45 PM, "Ben W. Brumfield" <notifications@github.com> wrote:

As discussed in #1144, the search_id=...... parameter that appears in the URL of an individual record's page is now optional, but is certainly ugly. If researchers use the citation generator, that parameter is removed, but if they cut-and-paste the URL they see in their browser, it's present.

By moving the search_id into the session--and carefully replacing it whenever a new search is performed--we can hide the parameter from the URL.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/header.png">https://github.githubassets.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://github.githubassets.com/images/email/message_cards/avatar.png">https://github.githubassets.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/FreeUKGen/MyopicVicar">https://github.com/FreeUKGen/MyopicVicar</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Hide search_id parameter from URLs (#1854)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/FreeUKGen/MyopicVicar/issues/1854">https://github.com/FreeUKGen/MyopicVicar/issues/1854</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/FreeUKGen/MyopicVicar/issues/1854">https://github.com/FreeUKGen/MyopicVicar/issues/1854</a>", "url": "<a href="https://github.com/FreeUKGen/MyopicVicar/issues/1854">https://github.com/FreeUKGen/MyopicVicar/issues/1854</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by Captainkirkdawson** [comment]
The code has been adjusted to avoid the use of the search query id in the display of a search record.
It has been deployed to test3 and requires testing.

**Comment by PatReynolds** [comment]
Bar now shows without search_ID parameter, eg https://test3.freereg.org.uk/search_records/58187f1de93790eca33821d9?locale=en#

Not sure if this change was supposed to, but citation generator not showing permanent url (with or without search_ID parameter): eg 
Source title: FreeREG - St Mary, Newark, Nottinghamshire
Repository: unknown
Citation detail: Register of unspecified type
Citation text: Baptism Rich. Alcock 08 Feb 1686 
Web address:https:www.freereg.org.uk viewed 8 April 2019.

**Comment by Captainkirkdawson** [comment]
@PatReynolds This story was restricted to the topic. i.e. the removal of dependence upon a search_id in the url.
You have confirmed that the code works as desired.

**Comment by Captainkirkdawson** [comment]
For citation please review #1374

**Comment by DeniseColbert** [comment]
@PatReynolds to check

**Comment by Captainkirkdawson** [comment]
OK  Ready for deployment as part of Multi Modal
