### ISSUE TITLE
Validate search query date entries (must be 4 digits)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1905]
Trying to pick up the burial of St Alban in St Albans ... got two 19th century men.  See image

![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/f367efc7-8052-4164-905b-7dc8433b4200)

Note this was a search without surname, just forename, although I don't know why that would make a difference.

**Comment by Captainkirkdawson** [comment]
It does if you enter a 4 digit year.
Issue title changed

**Comment by PatReynolds** [comment]
So it needs changing to a 3 year validation?  I tried with 0100 to 0900, and got the same result (i.e. records from the  19th century).

**Comment by Captainkirkdawson** [comment]
This turned out to be a little more complex than it appeared. 
Resolved the 3 digit date issue. The code was correcting a value in the start date but not the end date.
What research showed was that having only one date entered ended up with the search going out of that date. A search with both start and end dates abides by the dates.
Have added an additional validation that requires both dates. 
This may upset some people but it does now lead to consistent and correct results within the range.
Code has been deployed to test3/2 for review. @PatReynolds

**Comment by PatReynolds** [comment]
![image](https://user-images.githubusercontent.com/6338822/60604419-8d7b0c80-9daf-11e9-8985-1eee654af58b.png)
Works fine!

**Comment by richpomfret** [comment]
@PatReynolds to further test.

**Comment by Captainkirkdawson** [comment]
Deployed to production
