### ISSUE TITLE
21 Document current status of GAP

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#1931]
Review original requirements against current functionality.

E2 U6 S8 C7:P23

**Comment by Captainkirkdawson** [comment]
Document written and shared https://docs.google.com/document/d/1TTzjvBslg9lK2YBKbTfrE84hxpL3RIA6TsmdXNEketM/edit
Current Status Summary
There are 7 GapReason documents
Only SA can add new reasons
There are no Gap documents.
Only Syndicate and County Coordinators have access to source documents for the image server
No one can create a gap document because access is rejected if there is no gap document
Source documents can only exist for the image server
Transcribers have no ability to enter a gap
Transcribers have no ability to list gaps
Researchers have no ability to list gaps

**Comment by edickens** [comment]
I put in the list of reasons.  I  will add if necessary.
You say in the document that Transcribers can add Gap information, which is essential for when they come across a Gap.  But what happens if they are transcribing something which is not on the Image Server?  May I suggest that as part of Upload, or the new Online Data Entry, that the transcriber is asked for details of the Image Group.  This will ensure that CCs create them, even if there are no images included.  It will also ensure that a Gap report can easily be put against this Image Group.
Also, should we now think about how a Transcriber, CC or SC will enter the Gap information?  The Transcriber should be able to do it as they transcribe and come across some missing or unreadable pages.

**Comment by PatReynolds** [comment]
Thanks, Kirk,  I've put in some thoughts about reasons.

**Comment by edickens** [comment]
Pat,
We get Gaps within a page, for example when there are no marriages at a Church for a number of years.  The register will just continue but with a gap of many years.

**Comment by richpomfret** [comment]
@PatReynolds and @richpomfret to go through and create stories based on doc.

**Comment by PatReynolds** [comment]
Question:  Currently, only SA can add new reasons.  
Is that fine, or does a story need making to change this?

**Comment by PatReynolds** [comment]
Question: currently only Syndicate and County Coordinators have access to source documents for the image server.
Is that fine, or does a story need making to change this?

**Comment by edickens** [comment]
I am happy with only SA adding Reasons.  The list needs to be as short as possible and standardised.

**Comment by edickens** [comment]
Pat.  Please clarify your comment about source documents.  We don't have a separate system for source documents.  Anything can be loaded onto the images server and all the images there are therefore the source documents.

**Comment by Captainkirkdawson** [comment]
Believe this can be closed. The implementation epic is FreeUKGen/MyopicVicar#2040
1.6 GAP: a system to notify Gaps in Register information
