### ISSUE TITLE
Decide policy re no surname

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/MyopicVicar#2004]
There is no guidance in Help re whether or not to include a surname if it is not given in the transcription.
eg Jane the wife of John Smith
To assume Jane's surname is Smith is not TWYS

**Comment by Sherlock21** [comment]
Indeed!
And from memory, all my transcripts that refer to a wife will be in that category.
So part of that Policy will need to address what to do about these, if they are deemed not to be satisfactory

**Comment by SteveBiggs** [comment]
You should TWYS. If no surname is given, then leave it blank.

The Help for surname in a burial states:
![image](https://user-images.githubusercontent.com/25303607/62378848-9fcaa080-b53d-11e9-886c-b8c83ebf1705.png)

which does state you should not assume the surname of the deceased is the same as the relative.

In the example given (Jane the wife of John Smith), the wife's surname is not explicitly given so it should be left blank.

**Comment by suffolkroots** [comment]
Steve the help for surname is ambiguous to say the least. Nowhere is it made clear that if there is no surname the field must be left blank.

**Comment by Sherlock21** [comment]
Using Steve's last example above, Jane the wife of John Smith, this means that virtually ALL the Baptisms, and a large portion of Burials will need correcting, because the surname of the main subject of the record - Jane in the above - is only implied by the relationship.

Baptisms of children will all have been recorded as Alison, dau Matthew and Mary Browne was Baptised on third,
- because often, the register has a page per month, and 12 pages per year, so it does not explicitly spell the date out - one has to use one's knowledge of the Vicar's style rather than pedantically doing TWYS.
You can't have a pedantic TWYS rule about surnames in one place, but not in others,   and use implied logic ones about date for example.

**Comment by suffolkroots** [comment]
It should be made clear in all guidance that we must TWYS, not make assumptions, however well-founded they appear to be. That is up to the researcher.

**Comment by Sherlock21** [comment]
To be quite clear about this: are you saying that its right,or its wrong to  put Alison down as Alison Browne, in my example above?

or to put Jane as Jane Smith in Steve's example?

**Comment by Sherlock21** [comment]
To be quite clear about this: are you saying that its right,or its wrong to  put Alison down as Alison Browne, in my example above?

or to put Jane as Jane Smith in Steve's example?

**Comment by Sherlock21** [comment]
And, for that matter:
as each row in the attached copy of a page from the Parish Register concerned, is one person - record when it gets into FreeReg, where do you get toe Year and month from for each individual person recorded.

My answer is: you can't apply TWYS. the Transciber has to use their loaf and get it from elsewhere on the page - and even in some cases, from a page earlier in the register.

  /Users/eric/Desktop/WYK-Dewsbury-GR-1774-1796-D9-7-1-016.jpg

**Comment by suffolkroots** [comment]
Sherlock21 I can't see the slightest thing problematic in the image you've posted.

Names are there, dates are there, relationships are there.

**Comment by Sherlock21** [comment]
Elsewhere in this item it appears to me to be pedantic about 

1) TWYS applies item by item
2) within one item, its wrong to assume that Jane, wife of John Smith is NOT your authority to put 'SMiTH as the surname of Jane.
3) so therefore John son of Thomas Sanger in a Baptism or a Burial, does NOT give the transcriber the right to put John Sanger - and therefore the Program code should also 
not return the same John Sanger when one searches for that.
4) if you can't therefore make theses assumptions because they are not literally TWYS, you can't look on the previous page as a transcriber to find the relevant missing parts of a record's date.

I hasten to record that  this interpretation is NOT my way of working, and I don't accept it.

**Comment by SteveBiggs** [comment]
There's no need to get too hung up about this. The important thing is to TWYS and that the researcher can find the correct entry where ever possible. To answer @Sherlock21  points:

1) Yes for specific information, but if the heading for the page is "Burials in 1775" and it has the month and day down the side, that is still TWYS for the date for each entry.
2) Correct, but if you've put SMITH for Jane in previous files, there's no need to go back and remove it because the entry will be found in the same way as if only the husband had SMITH recorded.
3) Before flexible cvs, there wasn't even a field for the baptised person's (in this case John's) surname - only the father and/or mother and a search John Sanger will return the entry in either case.
4) The date is a special case and we always say that if the date is missing or unreadable, you should estimate at least the year from the records around it in the register if at all possible.
