### ISSUE TITLE
Cookie acceptance options NOT appearing for new users on TEST3

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/MyopicVicar#2032]
Keeping in Incoming as a reminder - we need to resolve this issue and make sure it does not arise on Live/production. Works fine on FC on test3, but FR does not and user options for changing cookies does not appear to save.

**Comment by Captainkirkdawson** [comment]
@richpomfret @Vino-S @PatReynolds performance on FR production is not as clear as it perhaps might be.

There are 3 cookies associated with cookie consent and ads.
cookie Directive (Our original cookie control)
userAcceptance (added due to GDPR)
userAdPersonalization (added due to GDPR)

If one eliminates all cookies, refreshes page then cookie message appears. adverts also appear. 
If one eliminates all cookies, ctl reloads page then cookie message appears. adverts do not appear.
You must close window and reload page to get ads to appear.
But all 3 cookies are set on webpage to (1,unknown and unknown) To remove the message you MUST accept cookies. There is no timeout on message and no ability to continue without cookies. 

If you delete solely cookieDirective  then there is no request to accept cookies. All 3 cookies are set on webpage to (1,1,1) Continues running. **Appears that it is no longer used.**

If you delete solely userAcceptance refreshes page then cookie message appears. adverts also appear. 
If you delete solely user Acceptance refreshes page then cookie message appears. adverts do not appear. Accept cookies. Message disappears. No adverts. Cannot get adverts to appear by refresh
You must close window and reload page to get ads to appear.
Same performance as  userAcceptance  for userAdPersonalization

**Comment by richpomfret** [comment]
What's the actual difference here when you do this with ctl?

'If one eliminates all cookies, refreshes page then cookie message appears. adverts also appear.
If one eliminates all cookies, ctl reloads page then cookie message appears. adverts do not appear.'

To remove the cookie message, you have 2 options - you either Accept or go into 'more options' option which allows you to pick and choose (GDPR requirement). We can always modify the text to make this a bit more explicit (as perhaps your comment indicates it needs to be).

**Comment by Captainkirkdawson** [comment]
@richpomfret 
Modern day browsers cache every front end resource like javascript or CSS style sheets. They primarily do this to increase the website performance. But this can be really irritating while one is in development mode and constantly modifying the javascript or css style sheets. The only way to see the changes is by doing a hard refresh or clear the cache of the browser.

A hard refresh is a way of clearing the browser’s cache for a specific page, to force it to load the most recent version of a page. Sometimes, when changes are made to the website, they don’t register immediately due to caching. A hard refresh will usually fix this, though occasionally completely clearing the cache is necessary.

i.e. refresh uses what is in the various caches on the internet your client. In windows a ctrl reload forces the download of a new copy of the page.

**Comment by Captainkirkdawson** [comment]
@richpomfret there is NO option to run without cookies

**Comment by richpomfret** [comment]
Fixed and now deployed so closing.
