### ISSUE TITLE
Live site search took user to test environment

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2047]
While searching for ""Anne Billett" "Francis Sprake" I receive the following hit from your site but it is password protected. I also see that it may be a test site of some sort. How can I view this record please? Resultant hit is: https://test2.freereg.org.uk › open › Sprake › baptisms-marriages-and-burials Ann SPRAKE, Baptism, 25 Jul 1602, Somerset, Winsham : Parish Church : Unspecified, Row 16 ... Francis SPRAKE, Baptism, 21 Mar 1640/1, Somerset, Winsham : Parish Church : Unspecified, Row 45

This came to FreeUKGEN contact form. I have the contact details of the user if more info is needed.

**Comment by Captainkirkdawson** [comment]
That is a proof of concept activity not yet in production Please suggest they use the FreeReg production search site 

On September 30, 2019, at 11:19 AM, DeniseColbert <notifications@github.com> wrote:

While searching for ""Anne Billett" "Francis Sprake" I receive the following hit from your site but it is password protected. I also see that it may be a test site of some sort. How can I view this record please? Resultant hit is: https://test2.freereg.org.uk › open › Sprake › baptisms-marriages-and-burials Ann SPRAKE, Baptism, 25 Jul 1602, Somerset, Winsham : Parish Church : Unspecified, Row 16 ... Francis SPRAKE, Baptism, 21 Mar 1640/1, Somerset, Winsham : Parish Church : Unspecified, Row 45

This came to FreeUKGEN contact form. I have the contact details of the user if more info is needed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/FreeUKGen/MyopicVicar/issues/2047?email_source=notifications">https://github.com/FreeUKGen/MyopicVicar/issues/2047?email_source=notifications</a>\u0026email_token=AAV52RTJXC7RKZK3BQ5NXLLQMHHC3A5CNFSM4I3Y5U22YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOQGUGQ", "url": "<a href="https://github.com/FreeUKGen/MyopicVicar/issues/2047?email_source=notifications">https://github.com/FreeUKGen/MyopicVicar/issues/2047?email_source=notifications</a>\u0026email_token=AAV52RTJXC7RKZK3BQ5NXLLQMHHC3A5CNFSM4I3Y5U22YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOQGUGQ", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by PatReynolds** [comment]
@DeniseColbert please ask the user to try again.

**Comment by SteveBiggs** [comment]
@DeniseColbert please provide contact details of the user so I can follow up.

**Comment by DeniseColbert** [comment]
Sent today.

**Comment by PatReynolds** [comment]
@DeniseColbert is the link from the advertising landing page to FreeREG correct?

**Comment by DeniseColbert** [comment]
Yes; it goes to the live site, not test 2.

**Comment by DeniseColbert** [comment]
@SteveBiggs to check if there's still an issue

**Comment by SteveBiggs** [comment]
There is no issue. This can be closed.
