### ISSUE TITLE
GiveCCs the ability to create a list with gaps

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/MyopicVicar#2054]
As per GAP requirements.

Layout of table described and discussed below.

E2 U6 S8 C9:P25

**Comment by edickens** [comment]
A transcriber should be able to enter GAP information if they find it.
Listing GAPs is a different problem.  The CC needs to know where there are gaps when they are checking if everything has been transcribed.  They can look at the decade statistics and see gaps, but are they because they have not been transcribed or are they genuine?
This is Bedfordshire, Ampthill...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/67511c10-c000-455a-94ba-e081178f1992)
Why are there so few Baptisms for 1650 to 1659?  Less than one per year.

**Comment by PatReynolds** [comment]
Thanks, Eric.  I have changed the title to reflect this.

Do you want two single tables, or a combined table?

Looking at the data that might be in table, do you need word GAP and the year?  Perhaps a short version of the reason?

Please ee linked document for alternatives/idea
https://docs.google.com/document/d/1E9h7BTiQEbW8jkChcOC6KoQ1qro9dUbrGbAbnSnmrDc/edit?usp=sharing

**Comment by edickens** [comment]
There are lots of different ways to do this, so I think we need Kirk to advise us.  There is also a difference between saying that a whole register is missing, and a few pages within a register are unreadable.

**Comment by PatReynolds** [comment]
Thanks, Eric, I've modified the story to reflect the clarification in your comment.

So ... does the cc need a listing that looks like this:

https://docs.google.com/document/d/1E9h7BTiQEbW8jkChcOC6KoQ1qro9dUbrGbAbnSnmrDc/edit?usp=sharing

(apologies to those in last Weds meeting, I thought I'd added this comment before the meeting).

**Comment by edickens** [comment]
Is the creation of GAP information by CCs a different topic to presenting this information to Researchers?
But Pat, to comment on the example you have given, I prefer the report with the GAP information included.  The only different might be for the report to say "There is a GAP in this decade, click here to see the details."  My reason is that there could be a lot of GAP reports in one decade if there is a register with lots of damaged pages.  So the researcher would want to look at the detail.
I assume that your report is a variation to the Transcriptions report that Researchers can see.  But should a researcher get a warning if they select a Place and Year Range that included a GAP, rather than having to look at Transcriptions to find out why they did not get a search result?
I don't know if CCs would want a different list so that they can Edit it.  They may want to see if they could recover some of the missing information, or try to find a different Source.

**Comment by PatReynolds** [comment]
I think CCs can already create gap information - if not, that needs creating as a separate story.

**Comment by Captainkirkdawson** [comment]
CC can create, edit and delete register level gaps and edit/delete and create batch level gaps
SC can edit/delete and create batch level gaps
DM, SA and ED can act as county coordinator
Deployed to test3

**Comment by Captainkirkdawson** [comment]
Deployed
