### ISSUE TITLE
emails from Test3 are going to those not involved in testing

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#2161]
As well as getting Log Bounced emails, others are going to CCs and may be transcribers.  Can they be intercepted?

**Comment by Captainkirkdawson** [comment]
An intercept is easy BUT means all go to the interceptor; just like we do on test2. Means that testing on test3 becomes impossible.
They get more messages now because they asked to be copied in production . 
Selective interceptors would be very difficult to design or implement and likely cause more troubles.
Could eliminate cc's if from test3 but then how to test the new features you have asked for that adds cc's to message replies.
Damned if one does and damned if one doesn't

**Comment by edickens** [comment]
I am due to send another Coordinators News;letter next week so will advise them to watch for the Test3 in the incoming email address.
Do any emails go to Transcribers from Test3?  I suspect not provided we only do edits on our own UserIDs.
I don't think this problem is significant enough to warrant programming work.  Just looking out for the Test3 in the Email address should be enough.

**Comment by Captainkirkdawson** [comment]
Rather than an interceptor have labelled messages coming from test with Test Freereg Servant; works for everything except the message system where messages are coming from the member. May be the lightening will strike

**Comment by richpomfret** [comment]
@edickens to point this out/alert users in the next user email.

**Comment by PatReynolds** [comment]
EricD. has resolved. so closing.
