### ISSUE TITLE
Add field for who created the embargo rule

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2163]
Need to keep track of who created it so can send them a message on completion of register batch processing

**Comment by edickens** [comment]
This could also be useful should we subsequently get permission and we can double check with the person who originally was asked to embargo the entries.  For example the Records Office may put on a general embargo because of using heir microfiche, but the Church gives us permission.

**Comment by Sherlock21** [comment]
I am of the opinion that we must show that there is a record which has an embargo on showing it until yyyy.

The researcher can then positively find the data by various other means. But we cannot just pretend its not there.

Eric B

On 29 Dec 2019, at 08:56, Eric Dickens <notifications@github.com> wrote:

This could also be useful should we subsequently get permission and we can double check with the person who originally was asked to embargo the entries. For example the Records Office may put on a general embargo because of using heir microfiche, but the Church gives us permission.

**Comment by edickens** [comment]
The more times that the embargoed message crops up, the more support we are going to get to have them lifted.

**Comment by Captainkirkdawson** [comment]
I fail to see any connection between you comments and this story. This story related to which Member of FreeREG created the rule. We need to keep track of that and to be able to send them a report on the actual implementation at the record level.
We already have a field for the authority that has requested the rule as well as one for the reason.
Fields are
field :authority, type: String
  validates :authority, presence: true
  field :period, type: Integer
  validates :period, numericality: { only_integer: true }
  field :period_type, type: String
  field :reason, type: String
  validates :reason, presence: true
  field :record_type, type: String
  validates_inclusion_of :record_type, in: RecordType::ALL_FREEREG_TYPES + [nil]
  field :rule, type: String
  belongs_to :register, index: true
  validate :valid_period
  validate :only_one_rule_per_record_type, on: :create

**Comment by Captainkirkdawson** [comment]
Completed and added to display of rules
