### ISSUE TITLE
Identify and establish Register Acquisition SWAT responsibilities

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2239]
E3 U6 S7 C7: P23

**Comment by Sherlock21** [comment]
If I may be so bold as to suggest:
Point 4 is dangerous, It may well prompt the Diocese to ask for money. £5 per register has been the fee in some places. IF you do rise this topic, they could well realise they have been missing out.
Point 5 on the other hand is a good idea. Especially if you were to offer then a copy when it is transcribed, Especially if they were to waive their filming fee. £100 a year here in my RO.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 you may indeed comment as I have edited my comment to note these were unedited and unapproved extracts from other stories. They are indeed in need of review and focus.

**Comment by edickens** [comment]
Point 3 is becoming more important as Churches set up their own websites and transcribe their registers.  I suggest to first look for Church websites and contact those as the team may have more success.  Also, it is the Church incumbent who owns the copyright to the registers, no matter what anyone may say.  So working with them is the most likely route to success, but there are a lot of them.
Where LDS have entered into an agreement with the Records Office to digitally photograph the registers and retain rights over the use of the images, they should also have gained the permission of the incumbent.  The incumbent should be able to give us permission to use the register, but it could be complicated.
There are some Churches where the register is not stored in the County Records Office and has never been transcribed by anyone.  Having these would be a great bonus.
Always offer back the resulting transcription.  Nobody does something for nothing.
The SWAT team need to be clear on the policies and benefits of FreeREG so that they can persuade people to work with us.

**Comment by PatReynolds** [comment]
Effect is correct, Eric, but meaning not quite: the Church of England says there is no copyright in the register, and that anyone may copy it, BUT for copying large amounts, permission of the Incumbent or PCC must be obtained.

**Comment by PatReynolds** [comment]
SWAT team should work first in counties where "registers wanted" is a (fairly) complete list and work towards generating the listing for other counties.
Probably best to discuss each step in turn, on the issue.
 Order seems to be 9 then 8 then 5 (less handling of register if the existing non-commercial images are used). Then 3/4/6 (with 7 following from 3, if needed).
This ordering_ should_ already be in place in the individual issues (ie. what is blocking what).. Do I need to tidy it up?

**Comment by edickens** [comment]
I have read through this story again and have nothing to add to what has been said.
I think we need to give Mick the freedom as SWAT team manager to decide on the tactics.  His first visit to Aylesbury (BKM) Records Office will identify the problems we face.  He can then decide how to takle them.  Mick has done a lot of negotiation for images in the past, so knows what is needed.  The ideal solution would be to get full access to the LDS images, just as Steve did for SSX, but we need to see the reaction that Mick gets on his visit.
