### ISSUE TITLE
Listing of files for large counties causes crashes on colobus

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#2305]
Over the past 3 weeks we have experienced a number of crashes with colobus. These have been identified as being caused by county coordinators listing all their files when those coordinators have large numbers of files; usually those in excess of a 1000 files. These processes gateway time out and or the coordinator walks away. Both leave orphan processes running until the next restart (at midnight). These processing are highly cpu and disk intensive. If  a couple of these are initiated then colobus become unresponsive to all apps.
@lemon-ukgen and I have explored the issue in great detail and have to date found no easy solution.
Hence we need to take action within the app to avoid starting these processes in the first place.
@SteveBiggs @edickens @Sherlock21 @richpomfret I need your advise on the possible solutions and this CANNOT wait for @PatReynolds to return or for the next scrum.
The options I see are: a) eliminate the display lists of county files actions for all counties

![file actions.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ec4aeb32-df9b-4572-8f96-839ef0de39c3)
b) limit those actions to those counties with less than 1000 files
c) replace those actions with ones that adds a userid filter (may still encounter a problem with those userids that have a 1000 files)
d) replace those actions with ones that adds an alphabet filter based on the fourth character of file name (which is usually the first character of the place name) works OK for those that follow the standard file naming

**Comment by Sherlock21** [comment]
It would be a pity to throw away all your effort and abandon the facility.
so NO to (a)

(b) is a bit unfair to Counties that have done a lot of work - and probably there is the tie one needs this facility most. - so NO to (b)

c) this seems the obvious answer on first inspection, - but I suspect there are a lot of transcribers who have more than the 1000 limit. - again, those are where its most useful. So NO to (c)
d)this one seems a workable solution to me - may take a while for users to get their head round it. but its better than nothing. 0MUCH better.

so YES to (d)

eric b

On 17 Jun 2020, at 19:18, Kirk Dawson <notifications@github.com> wrote:


Over the past 3 weeks we have experienced a number of crashes with colobus. These have been identified as being caused by county coordinators listing all their files when those coordinators have large numbers of files; usually those in excess of a 1000 files. These processes gateway time out and or the coordinator walks away. Both leave orphan processes running until the next restart (at midnight). These processing are highly cpu and disk intensive. If a couple of these are initiated then colobus become unresponsive to all apps.
@lemon-ukgen <https://github.com/lemon-ukgen> and I have explored the issue in great detail and have to date found no easy solution.
Hence we need to take action within the app to avoid starting these processes in the first place.
@SteveBiggs <https://github.com/SteveBiggs> @edickens <https://github.com/edickens> @Sherlock21 <https://github.com/Sherlock21> @richpomfret <https://github.com/richpomfret> I need your advise on the possible solutions and this CANNOT wait for @PatReynolds <https://github.com/PatReynolds> to return or for the next scrum.
The options I see are: a) eliminate the display lists of county files actions for all counties

 <https://camo.githubusercontent.com/ba935ded4a4311b38564054da29e2949de17fade/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562363861653638346235383036626332626465666366302f65633461656233322d646639622d343537322d386639362d383339656630646533396333>
b) limit those actions to those counties with less than 1000 files
c) replace those actions with ones that adds a userid filter (may still encounter a problem with those userids that have a 1000 files)
d) replace those actions with ones that adds an alphabet filter based on the fourth character of file name (which is usually the first character of the place name) works OK for those that follow the standard file naming

**Comment by Captainkirkdawson** [comment]
What is interesting is that those actions were not working correctly for 4-5 months until Ali noticed she was only getting the first page a month ago. Fixed that and created this problem instead!

**Comment by Sherlock21** [comment]
Its not easy working out ALL the possible combinations when one is testing a bit of code.
 And trying to anticipate the Operator Errors is a different game altogether isn't it!

**Comment by SteveBiggs** [comment]
You don't list reintroducing pagination of the listings which seems the obvious solution to me.

**Comment by SteveBiggs** [comment]
btw, as a coord, I virtually never use these actions hence why I didn't notice the change. If I want to look at a file, I always go via Active Places to the specific place. I suspect not many other coords do either given that no one has complained before Ali did.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs we have already tried pagination and that does not help.

**Comment by Sherlock21** [comment]
Have you asked a typical CC for their view? Maybe Ali as she raised the problem.

**Comment by Captainkirkdawson** [comment]
I leave that up to the management team

**Comment by SteveBiggs** [comment]
Expanding on my comment that I rarely use these actions, taking each button in turn:
- ... by Filename - basically sorts them in place order. I would always use the Active Places route instead
- ... by Userid - Just go direct to the Userid via Manage Syndicate and list batches
- ... by Most recent Date - the only one of these I ever use and that is to look at the least few uploads so just seeing the first page is usually enough anyway
- ... by Oldest Date - never use and can see no real value in it

So I think either option a) or only keep the Most Recent Date button as a single page
If we go with d) that is again basically sorting by place so use Active Places instead

Other CC/SCs will have a different view, so EricB's idea of polling them is a good one.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs Would you please do that and provide consensus view. It remains urgent

**Comment by SteveBiggs** [comment]
@Captainkirkdawson I will do that, but could you explain why pagination no longer works given that up until 5 months ago it did?

**Comment by Captainkirkdawson** [comment]
Wish I knew the answer to that

**Comment by SteveBiggs** [comment]
Polling message sent to all coords.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @edickens @Sherlock21 @richpomfret Steve you may terminate the survey. @lemon-ukgen found the error in my code and I have deployed an urgent fix to production. Pagination is implemented and works correctly

**Comment by Sherlock21** [comment]
That's good news.

**Comment by SteveBiggs** [comment]
Have informed all coords.
