### ISSUE TITLE
Create Information for the SWAT team page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2319]
Needs taking information from Information for Coordinators and previous discussions with SWAT team,  re-writing with SWAT team in mind - @PatReynolds to talk to Mick about what they need.

Need to move information from 'Obtaining Source Materials' to this page.

Contents:
- [x] paragraph explaining the role of the team
- [x] example of letter granting permission to the LDS
- [x] link to 'other sources'
- [x] example of letter to the Local Authority Archive asking for transcription in situ / online /fiche [needed?]
- [x] example of letter granting permission to the LD - [x] Obtaining approval of the Vicar. 
Obtaining approval of  sources other than CoE and Local Authority archives, including
   - [x] Nonconformist churches
  - [x] National archives (England, Ireland, Scotland, Wales, Crown dependencies and Overseas Territories)

Priority (4, 6, 7  6)  P23

To be developed by/in consultation with the SWAT team

**Comment by PatReynolds** [comment]
@PatReynolds to implement above

**Comment by PatReynolds** [comment]
Contacted Mick 23/10/2020

**Comment by DeniseColbert** [comment]
Pat to check for a reply

**Comment by PatReynolds** [comment]
With Mick 21 Jan 2021

**Comment by PatReynolds** [comment]
No,example letter not needed, so can close this.

**Comment by DeniseColbert** [comment]
Complete - closing

**Comment by DeniseColbert** [comment]
@AlOneill to look at the HTML of the page before we can close this.

**Comment by AlOneill** [comment]
@PatReynolds Assuming that it is "Information for the SWAT team DRAFT" that I'm to check, this is unresolved in the middle of the page:

'DELETE this section or EXPAND?

"Remember, if you are talking to them be sure to stress the nature of FreeREG. We are NOT publishing any materials, transcripts, or registers. We ARE creating a searchable index of the names of people who are entered into baptism, marriage and death registers as a research tool to assist people locate where they should undertake more detailed investigations." '

————————

I will add a link to this page from the Coords Info menu on "Information for Coordinators", unless I hear otherwise.
Do you want me to create an "On this page" sub-menu?

**Comment by PatReynolds** [comment]
Check what Mick's response was, and remove if needed / resolve

**Comment by PatReynolds** [comment]
Removed/resolved issues.

**Comment by PatReynolds** [comment]
@AlOneill please check and mark ready for deployment (if it is).

**Comment by AlOneill** [comment]
Preliminary checks made to [Information for the SWAT team DRAFT](https://test3.freereg.org.uk/cms/information-for-the-swat-team-draft). Typos, HTML and typography are fixed — including empty links, Baptist Historical Society address, keyboard quotation marks, hyphens for dashes, unbalanced parentheses, stray warning re link opening in new tab, casing of `id` attributes.

**Issues**

1. Pat's letter requires Google log-in to view

2. not clear how a volunteer gets from the "listing of Record Offices" to the "Google drive permissions folder" in order to "place a copy of the email or letter of confirmation"

**Questions**

3. is this page going to be in the "Information for coordinators" folder? or somewhere else? In other words, how will volunteers find it?

4. two links have the full web address as the link-text — keep as is or prettify?

5. should there be more content relating to "Examples of Approvals"? Cannot see the promised examples

**Comment by PatReynolds** [comment]
Thanks, Alison.


1 Model letter is now open to anyone with a link.

2. Does not seem to be a  way of allowing "anyone" to add, but not edit, delete etc.  Mick already has permission... perhaps text should be changed to 'the SWAT team' 

3. Link from Information for coordinators page.   I'd assume that SWAT team members might bookmark it, but can always reach it via Coords.

5. No - that bit should be removed.

**Comment by AlOneill** [comment]
@PatReynolds thank you.

A similar question:

Under "Other information — …" > "Storing permissions" the paragraph reads:

"Please place a copy of the email or letter of confirmation in [a listing of the Record Offices (PDF)]
(https://drive.google.com/open?id=1MRS_pqtbxfM0M1neoONLBPguRKtOVafK) in the Google drive Permissions folder.  Please send the original on to the Executive Director for manual filing (…)."

It seems that this needs some re-wording too — how does a volunteer place a file in a PDF? Passing it back to you as I do not want to assume that I know anything.

**Comment by PatReynolds** [comment]
I think the 'storing permissions' needs a human to put them in the folder - possibly Mick would be well placed?

**Comment by AlOneill** [comment]
@PatReynolds I've edited the page as per your answers to the questions above. You might want to check that I've interpreted your comments correctly.

On to the next step.

I propose to make the following changes so that the page structure is consistent with current practice, but if there is a reason to be different, please say so. 

1. split first submenu into "On this page" and "Related pages"

2. add remaining `h2` heading to "On this page"

3. delete the heading "About the SWAT team" and make its paragraph the `.lead` paragraph

4. add horizontal rules to separate sections visually

I think these next changes would also improve the page. But again, if there is a reason not to do so, just say.

5. remove "SWAT team: " from "SWAT team: County Record Offices and Local Authority Archives"

6. remove "Other" from "Other Help Sections"

7. add`h3` headings under "Other information — …" to "On this page" sub-menu

8. change menu-item "Working with National Archives (UK and Overseas Territories)" to  "Working with National Archives (RoI, UK and Overseas Territories)". Or should 'RoI' be 'Ireland' in this context?

**Comment by AlOneill** [comment]
@PatReynolds Whilst checking links, I note that the letter from you has this at the top: 
NEEDS REVISION - last revised: 16 September 2016

So, is the link going to the most recent version of the letter? Are you happy to let that stand?

**Comment by AlOneill** [comment]
The [Information for the SWAT team]("https://test3.freereg.org.uk/cms/information-for-coordinators/information-for-the-swat-team") page is sync-ready.

There is a link to the page from Info for Coords.

**Comment by PatReynolds** [comment]
Updated last date of revision and removed odd footer.
