### ISSUE TITLE
Wrong location of place

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/MyopicVicar#2359]
I live next to Gin Pit village (the place in FreeREG called Gin Pits: https://www.freereg.org.uk/freereg_contents/53cbf5edeca9eb03a6005acd/show_place?locale=en)  but the map location is a few miles out:

![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/0cec902f-86e5-4493-b309-37e8accd0e31)

Possibly a one-off but could indicate a general inaccuracy.

**Comment by Sherlock21** [comment]
Hi

I will deal with this.

EricB

On 31 Dec 2020, at 10:22, DeniseColbert <notifications@github.com> wrote:


I live next to Gin Pit village (the place in FreeREG called Gin Pits: https://www.freereg.org.uk/freereg_contents/53cbf5edeca9eb03a6005acd/show_place?locale=en <https://www.freereg.org.uk/freereg_contents/53cbf5edeca9eb03a6005acd/show_place?locale=en>) but the map location is a few miles out:

 <https://camo.githubusercontent.com/7d56702d33d58e79c361bffa7badce2bb94e07f3c5d69c44100e89d726358d32/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563616236636338313834343732353465343631653734312f30636563393032662d383665352d343439332d623330392d333765386163636430653331>
Possibly a one-off but could indicate a general inaccuracy.

**Comment by Sherlock21** [comment]
OK. I have adjusted this place location details now - both the name & map ref.

note: on the scale of the map used, the marker peardrop can only be to the left (west) or to the right (East) of the actual village because we use 6 digit OS Grid refs.

thanks for bringing this to our attention.
regards,
Eric Booker

On 31 Dec 2020, at 10:22, DeniseColbert <notifications@github.com> wrote:


I live next to Gin Pit village (the place in FreeREG called Gin Pits: https://www.freereg.org.uk/freereg_contents/53cbf5edeca9eb03a6005acd/show_place?locale=en <https://www.freereg.org.uk/freereg_contents/53cbf5edeca9eb03a6005acd/show_place?locale=en>) but the map location is a few miles out:

 <https://camo.githubusercontent.com/7d56702d33d58e79c361bffa7badce2bb94e07f3c5d69c44100e89d726358d32/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563616236636338313834343732353465343631653734312f30636563393032662d383665352d343439332d623330392d333765386163636430653331>
Possibly a one-off but could indicate a general inaccuracy.

**Comment by DeniseColbert** [comment]
Thanks Eric.

**Comment by PatReynolds** [comment]
Thank you, @Sherlock21
