### ISSUE TITLE
Develop and note on Coord help page the documentation procedures for embargo

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2361]

**Comment by PatReynolds** [comment]
Does it just need a link to https://drive.google.com/file/d/1teFkdX-rr_cKeGqlpAR5ez-zOETwiPra/view?usp=sharing ? @Captainkirkdawson @edickens

**Comment by AlOneill** [comment]
There is at least one typo in that document (have not read it all): the second heading should be, "Embargo a Register and its current and future contents" ("its" rather than "it").

**Comment by edickens** [comment]
I have read through the document and other than minor things sets out the system very well.

There are some Bold words that do not need to be in Bold.  But not really important.

I thought that we were using the name "Entry" instead of "Record" for the individual entries.

Can an Entry Embargo have no "Release back date"?  Or should we have a default of 125 years?  I'm thinking of when someone says I do not want my family to be shown.

**Comment by Captainkirkdawson** [comment]
I wrote that document a year ago when we implemented the capability as the basis for how the system works. I never claim to create great documents that is for others,

**Comment by AlOneill** [comment]
@PatReynolds Now that I have read the whole document, I suggest that we convert it to an HTML page, correcting the typos and making the language more friendly. The markup will not be straightforward (because of the images), so I'll assign myself. 

 At some point, we should consider replacing the images so that they are appropriately-sized, with neat annotations.

**Comment by Captainkirkdawson** [comment]
Mind you if they are as bad as implied then I will not bother in the future

**Comment by AlOneill** [comment]
@Captainkirkdawson Your choice of images is a very useful guide, so yes, do bother!

**Comment by AlOneill** [comment]
@PatReynolds @SteveBiggs Embargo system info added to:
https://test3.freereg.org.uk/cms/information-for-coordinators/the-embargo-system-draft

The layout needs refining for the best display of the images — my next task.

@Captainkirkdawson I assume this information should now be deleted:
"during testing on test3 [reprocessing] will run every 30 minutes on the hr and half hour" ?

**Comment by Captainkirkdawson** [comment]
yes

**Comment by AlOneill** [comment]
@Captainkirkdawson Thanks. Done.

**Comment by AlOneill** [comment]
@SteveBiggs the draft page is ready for proofreading: 
https://test3.freereg.org.uk/cms/information-for-coordinators/the-embargo-system-draft

I've tweaked the layout to give more width to the images at 'laptop' widths. It is done simply (thinking of the next editor!), but if the images do not work for you, then it will have to be complicated.

@PatReynolds, as noted on the page itself, I won't be able to complete the work for this story until the current work (?yours) on 'Info for Coords' is completed.

**Comment by PatReynolds** [comment]
Blocked (possibly) by #1991 (online editing processes - work on this does not seem to have started, but possibly would be on "File and Batch Actions" rather than Coords help?)).

Not blocked by #2361 (embargo) is complete.

I can't see any other work in progress on the coords help.

**Comment by AlOneill** [comment]
@PatReynolds Nevertheless, there is a Info for Coords DRAFT page:
https://test3.freereg.org.uk/cms/information-for-coordinators/information-for-coordinators-draft

I can see that a second para has been added to the 'Image Server' section together with a new section, 'Obtaining images to transcribe'.

In addition, 'Acquiring Data from other transcription projects' has been re-written, with new sub-sections.

Someone must be working on this! And there should be a story to go with it.

**Comment by PatReynolds** [comment]
@edickens to check Embargo element  and @PatReynolds to check the rest for work not yet ready for release.

**Comment by edickens** [comment]
@PatReynolds I can't find the Coords Draft page.  The link here doesn't work for me.

**Comment by AlOneill** [comment]
@edickens The page that requires proofreading is [The Embargo System DRAFT](https://test3.freereg.org.uk/cms/information-for-coordinators/the-embargo-system-draft).

**Comment by edickens** [comment]
I have read it and it is fine.
Not to change anything, but my reaction was to do with the need to get Trustee approval.  It is very likely that a request to embargo a single entry will come from a researcher through the Contact us.  Should we say how to contact the Trustee, and who?  And, as it is the Trustee who approves the Entry Embargo, should they set up the embargo?  If yes, then some lock is needed so that only a Trustee can set or unset the Entry Embargo, or the Trustee must give approval in some form which perhaps should be recorded.  So the system as set up is fine, it is just how Trustee permission is requested and actioned.

**Comment by SteveBiggs** [comment]
The Trustees have already directed that if an individual asks for their own record to be removed, we should do so (i.e. embargo it). It's not necessary to contact the Trustees nor for the Trustees to actually set the embargo.

**Comment by edickens** [comment]
In which case perhaps the wording needs improving, because as I read it, Trustee approval is needed each time an embargo is set.  Perhaps just add that if the person asks for their own entry to be embargoed, that is OK, but even asking for a relative to be embargoed requires the relative's or Trustee's approval.

**Comment by SteveBiggs** [comment]
I agree that the wording needs changing to state that if an individual asks for their own record to be removed, we should embargo it without requiring further Trustee guidance.

**Comment by AlOneill** [comment]
@SteveBiggs @edickens Thank you.

@PatReynolds In terms of Policy, is there anything else (in addition to Steve's last comment) that should be added to the instructions for an individual embargo? For instance, if one individual requests that a record for a second individual be embargoed, what should be done and by whom?

**Comment by SteveBiggs** [comment]
I think if an individual requests that a record for a second individual be embargoed, it depends on the relationship between the individuals. We had a recent case where a woman asked for her own and her brother's records to be removed which we did, but if the connection was more distant we should get the request from the actual individual whose record is being requested or seek Trustee approval.

**Comment by DeniseColbert** [comment]
@AlOneill to add the above info to the page

**Comment by AlOneill** [comment]
Info re whether or not explicit Trustee approval is needed has been added to page.

Also, it turns out that 'un-embargo' and 'unembargo' are not real words, so have edited text to work without them, as appropriate.

My next task: make Embargo page sync-ready and add page to sub-menus on 'Info for Coords' and related pages — requires a clear head so might take me a couple of days to finish.

**Comment by AlOneill** [comment]
"The Embargo System" page is now sync-ready and a link to this page has been added to the sub-menu on each of the pages in the Coord help.

**Comment by AlOneill** [comment]
Forgot to say that I've also added the new page as a sub-menu item to the draft page, "Other sources for transcribing DRAFT".

**Comment by AlOneill** [comment]
Strange. I made the 'Embargo system' page sync-ready 24 days ago, together with menu updates to all the other pages in the Coord Help. Looking today, the 'Embargo system' page has reverted to a DRAFT and the edits to other pages are missing.

@Vino-S could this be related to the recent software updates somehow? How best to proceed?

**Comment by Vino-S** [comment]
Hi @AlOneill ,
I have updated the test3 Refinery. Could you have a look again, please?

**Comment by AlOneill** [comment]
@Vino-S thank you! As far as I can tell, all is well again.

Closing.
