### ISSUE TITLE
Remove "Destroy ID" button

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2367]
E0 U6 S8 C7: P21

'Destroy' button should not destroy, but should move to the TO BE DESTOYED syndicate, where they will be regularly reviewed by a manager.

**Comment by SteveBiggs** [comment]
Why?

**Comment by edickens** [comment]
The problem is that there are things in the Attic, even if someone has not uploaded a file, such as a copy of the UserID.  So if you Destroy the UserID there are things left without a link.

Kirk will leave the button for SysAdmin in case there are things which really must be removed.

Not removing unwanted UserIDs will make the list of UserIDs longer and longer.  The Active Transcribers option will omit the unwanted UserIDs.  But the list of Syndicate members has both Active and Inactive.  Just as listing by Name or email address has everyone.

So may I sugget that In the long term we need a more severe form of "Inactive".  Such as "Dormant".  These UserIDs will never be shown to SCs or anyone, except SysAdmin under Manage UserIDs.  This will retain the integrity of the links to the Attic.  Perhaps even put the Dormant UserIDs in a separate list of their own.  But this is a larger job to implement, so is in the future.

**Comment by Captainkirkdawson** [comment]
Deployed to test3 for testing

**Comment by Captainkirkdawson** [comment]
It would help if I could spell Destroyed. New version on test3

**Comment by edickens** [comment]
Didn't notice that!!!

**Comment by Captainkirkdawson** [comment]
It took me 5 hrs of head scratching looking at various deep code issues before stumbling onto the spelling

**Comment by edickens** [comment]
Yes, working now.  TY.  But in production I have the  Syndicate as "To be Destroyed" and not "TO BE DESTROYED".  Syndicate names are case sensitive.  And we have UserIDs in the production version.  Do you need to change Test3?  Or I can put your version in Production and move the UserIDs across then delete the present version.

**Comment by Captainkirkdawson** [comment]
Changed as requested. Please retest

**Comment by edickens** [comment]
Yes.  Works fine.  Please move to production as soon as possible.
I also tried removing someone with batches and that test worked but the wording doesn't match the action...
![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/a9805877-f2aa-4a43-a6e3-2c2d90165e4c)
but I'm not sure that this is important.
Thanks

**Comment by Captainkirkdawson** [comment]
Actually I think the wording is correct
