### ISSUE TITLE
Forum/ system to email SCs and Transcribers, presently manually maintained GoogleGroups After#694

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#245]
EricD requested

I would like three ways of mailing UserIDs.

1. A Transcribers group
2. A Coordinators group
Both of these by opting in when registering and amendable.
3. A means to mail everyone with a notice, such as the server move
4. I should have included in my last report a suggestion that Syndicate Coordinators should be able to mail just their syndicate. This will save them having to keep a mailgroup uptodate.

Those registered, and opted in, should be able to send emails to groups 1 and 2 which will be forward automatically.

I have assumed that the alias list, which handles reg-web, reg-data, reg-winreg etc. will still be available.

E

**Comment by PatReynolds** [comment]
Something coming out of the communication survey: ideally  the opt-in groups should work both as email lists and as forums (i.e. some people want to get emails, others want to log in and see discussions online, which can be marked as sorted/finished/closed so they are not bothered by things no longer needing their attention.

**Comment by PatReynolds** [comment]
Changed name to reflect topic

**Comment by PatReynolds** [comment]
Coords to have access to the subscription activity of their teams (e.g. can look at a list and see that someone is/isn't signed up to a voluntary group.

**Comment by edickens** [comment]
SCs need to be able to use the message system to send a message to just those in their Syndicate.
For this to replace the Googlemail systems that I use for Transcribers and Coordinators, then a User needs the means to add to their profile that they wish not to receive non-urgent messages.  The Transcribers mail group has a lot of messages of the form "Can you read this image?"  Quite a few have unsubscribed from the transcribers mailgroup because they do not want these messages.  So a marker on their profile is needed to say "Urgent or management messages only."  And can Transcribers create messages?  That would be the only way for them to use the server instead of the googlegroup.  And that raises the next question as to whether we keep all replies so that someone can look through all the correspondence on a particular subject.  I think we need to decide what sort of a messages system we will have.  Is it just for management messages as now, or is it a full discussion group?  If not the latter I will need to keep the Transcribers mailgroup going.

**Comment by Captainkirkdawson** [comment]
The SC component is already being dealt with in #692 newsletter distribution and #746 Message waiting.
The message system was set up to distribute "management" information.
Why would we get into setting up discussion groups when other vehicles exist for that purpose?

**Comment by edickens** [comment]
Because they are not integrated and I have to process every new registration as a copy and paste and ask them if they want to join the mailgroup.  Any changes in email address do not get passed on.  So the decision is "Do we want to integrate the discussion forums, or just have a management message system on the server.  I have no preference, but would prefer not to be the manager of the discussion forums.
Of course we could make these groups Open like Rootsweb, and then just prompt new volunteers to sign up when they register.  But the FreeREG groups were set up as closed groups to avoid Spam and unwanted people registering.  Copies of images go on these messages and they should not be shown to the world.

**Comment by Captainkirkdawson** [comment]
We could ask on the registration form or ask them at  confirmation and then feed the request to yourself and/or any syndicate list manager for addition.

**Comment by edickens** [comment]
This is no less work than what I do now.  Just as easy for me to
    work from the Registration Completed messages that I get now.
    
    Story can be closed.
    
    E
    
      On 17/10/2016 22:13, Kirk Dawson wrote:
    
    
      We could ask on the registration form or ask them at
        confirmation and then feed the request to yourself and/or any
        syndicate list manager for addition.
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #245: We could ask on the registration form or ask them at  confirmation and then feed the request to yourself and/or any syndicate list manager for addition."}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/245#issuecomment-254335747"}}}
