### ISSUE TITLE
Gathering info for Registered Researchers PDD

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/MyopicVicar#2599]
Gather ideas of what benefits Regestering as a Researcher would bring - e.g.
* Saved searches.
* Send email when a parish / dates wanted are transcribed
* Make images available (where we have permission)

**Comment by richardofsussex** [comment]
- store a set of records of interest to the researcher; provide ability to add notes to each stored record

**Comment by edickens** [comment]
Get news via the Message system
Use widlcard and more detailed, such as Family search, option
Leave request to be emailed if Place has new records or amendments
Accept a Researcher Agreement about how to use the extra information made available
Look at the image associated with a search result, but no download and image viewed by scrolling so that it cannot be copied
Ask for help from County Coordinator
"Edit" an entry by creating a copy but include changes.  County Coordinator can then verify.  (Ancestry has this)
Browse not download transcriptions
Membership of a mail group
Look at the structure of Place/Church/REgister type and the information held
Look at the list of Available Image groups to see what is comng soon.  (Might encourage them to transcribe)

**Comment by edickens** [comment]
To set this up some programming is needed.  Probably more important than the online transcripton tool.
Quite a few of these Actions are already programmed.
A Researcher login is needed where they can sselect which project.  On selection they get a set of Actions as now, with a breadcrumb to go back to select a different porject.  This could be useful for everyone.
A separate set of Researcher UserIDs will be needed as this could be large and needs managing.
Acceptance of an Agreement and Cookies is needed.
Annual payment funcion needed.

**Comment by edickens** [comment]
As a general principle, a Registered Researcher can look but not download.
Information held is for them only, such as Saved Searches and Requests to be emailed with updates.
They should have sets of Actions, just as now, but limited to viewing.

**Comment by PatReynoldsFUG** [comment]
Took paper to 3 Sept Trustee meeting but was not discussed due to pressure of time / my absense.

I have added this story to the epic #1944 Remaining action is to ensure the ideas raised here are captured in a Project Definition Document (covering all FUG Projects).

**Comment by DeniseColbert** [comment]
Denise to add to trustee agenda

**Comment by DeniseColbert** [comment]
Closing as ComETT is in established development
