### ISSUE TITLE
Unusual Roman numerals - add to Help

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/MyopicVicar#2675]
From Ali Hill:

One of my transcribers came across F in burial dates.

eg FFIII

I found the attached list of other unusual numbers which explains that FFIII = 83.

It might be useful to add this list to numbers and dates help, what do you think?

![Capture.JPG](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/d1f6346f-92a9-4859-867f-6a9e57cc4958)

**Comment by AlOneill** [comment]
@SteveBiggs It would be good to know the source for this list — people are likely to be sceptical (as well as interested) about obscure ways of representing numbers. Thanks.

I will need to ask a developer to enable the use of those symbols for 800 (capital omega?) and 900 (not a clue!). Failing that we will need to use images of hand-written symbols rather than glyphs.

**Comment by AlOneill** [comment]
@SteveBiggs 
The symbols used appear to be more complicated or flexible than that table would indicate. See this [Wikipedia page on the Gothic alphabet](https://en.wikipedia.org/wiki/Gothic_alphabet) for instance. Which leaves me in a quandary as I would hate to give transcribers only part of the truth, but cannot see myself writing an in-depth report on the topic. 

What do you think?

**Comment by AlOneill** [comment]
Oops, this part of the [Roman numerals page](https://en.wikipedia.org/wiki/Roman_numerals#Use_in_the_Middle_Ages_and_Renaissance) is more relevant — too many tabs open!

Perhaps we mention 'F' and then link to this page? Have you come across these kinds of numerals?

**Comment by SteveBiggs** [comment]
@AlOneill I haven't come across these numerals myself but that table on Roman numerals aligns with the one that Ali found with some added abbreviations so I agree that linking to that page would be good. However, it may be an idea to also put an image of the table directly in the Help in case the URL of the Wikipedia article changes in the future.

**Comment by suffolkroots** [comment]
Here's the url

https://www.unrv.com/culture/roman-numerals.php

**Comment by AlOneill** [comment]
I've updated the Help with this information: [DRAFT Numbers and dates](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-numbers-and-dates)

I noticed that the 'On this page' menu is a little sparse as compared with the number of headings on the page and hence the scope of the content. Next, I will edit the draft further offline to improve the menu listing.

**Comment by AlOneill** [comment]
@DeniseColbert @SteveBiggs 
[DRAFT Numbers and dates](https://test3.freereg.org.uk/cms/information-for-transcribers/draft-numbers-and-dates) updated with short section on Mediaeval Roman numerals plus a link to the Wikipedia article, the URL of which is not going to change.

Also improved the 'On this page' menu so that it better reflects the scope of the information on the page and checked that the tables were adequately labelled (for screen reader users).

**Comment by SteveBiggs** [comment]
Thanks @AlOneill , looks good.

**Comment by AlOneill** [comment]
Thanks @SteveBiggs 

[Numbers and Dates](https://test3.freereg.org.uk/cms/information-for-transcribers/numbers-and-dates) is now sync-ready.

(At some point in the future I will have a go at making the tables on that page a little more accessible: they are not bad now but they could be better …)

**Comment by DeniseColbert** [comment]
Deployed, closing. Thanks @AlOneill
