### ISSUE TITLE
Syndicate Registrations for Anywhere/Lancashire/Cheshire to be sent to the Training Syndicate

### ISSUE THREAD

**Issue by CommsCoord** [FreeUKGen/MyopicVicar#2718]
Jo has asked if this can be done:

'Is it possible that registrations for Anywhere/Lancashire/Cheshire are automatically sent directly to the training syndicate.  This would cut out the need for double transfers, only need do the transfer to the county or if they’ve gone AWOL/quit to the ‘to be destroyed’.'

Is this something we could do?

**Comment by edickens** [comment]
I thin this is a program change by Vino because the selectin list accessed by the new volunteer is the list of Syndicates reduced by those not recruiting.
Having "Anywhere" go to traning makes sense, but I would be against specific counties as others may aske for it.  Much better is to set up an option within a Syndicate to say that the SC would like everyone to go to Training.

**Comment by DeniseColbert** [comment]
This is superseded by Jo now being able to move volunteers between syndicates - closing
