### ISSUE TITLE
Build need optimization and more efficient

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#288]
Make the next build easier

**Comment by Captainkirkdawson** [comment]
Need to stop hitting the place collection when adding search records

**Comment by Captainkirkdawson** [comment]
In addition we need to stop replacing unchanged records. It is proposed to calculate a digest of the record and only change those records where the digest changes. An initial test is underway of a proposed digest to ensure there are no false duplicates of a digest within a batch.

**Comment by edickens** [comment]
As soon as CCs are on board in FR2, we could, until the transcriber 
functions are ready, get CCs to upload ALL files into FR2 and shut down 
the uploading of files into FR1.  Many CCs already upload on behalf of 
transcribers now since they want to sight check the work. They will only 
need to upload a file when the transcriber finishes an allocation of 
work.  When we have shut down loading files into FR1 the FR1/FR2 update 
will be obsolete.  I would not spend much time improving it.

E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
No I do not want any uploading into FR2 until version 1.3

We also need to ensure that WinREG can interface as well before then.

I need to complete this specific story and some other tools before opening
direct loading to anyone.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Perhaps I should have been clearer.

This story affects not only the FR1/FR2 daily update by any batch process
done by any process and is absolutely essential for the future updating of
FR2.

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Sorry Kirk.  Of course.  It is needed for V1.3 when transcribers load 
batches into FR2 during the heavy daily processing time.

E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The code was implemented after full testing on vervet.  In addition a planned delay between batches of 1 minute was installed to give the slaves time to catch up with the master. The first full use of the code on May 29 processed 54 batches and 65,000 records (40,000 were unchanged). Impact on server performance of the update was minimal.
