### ISSUE TITLE
Make table padding symmetrical in search form

### ISSUE THREAD

**Issue by graphiclunarkid** [FreeUKGen/MyopicVicar#343]
As a user I want the search form to be aligned symmetrically within its frame so that it doesn't look lopsided.

ACCEPTANCE CRITERIA

- The search form appears symmetrically
- If possible, the whole of the longest place and county names appear in the drop-down list, rather than being cut off.

**Comment by juliancheal** [comment]
No wonder none of my CSS changes were taking effect. Due to `<%= stylesheet_link_tag "application" %>` not being included in `application.html.erb` since this commit https://github.com/FreeUKGen/MyopicVicar/commit/74b9b7dd87084f053b949c4a43e074d58eefaa75
However including it again is causing a Sass syntax error.

**Comment by Captainkirkdawson** [comment]
That commit was in August last and involved only views and a mailer


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
