### ISSUE TITLE
Do we include the lineid in results?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#363]
We have a lineid field that has userid.batch.entry as a compound field. This was included so that coordinators can locate the specific entry when a researcher finds a data problem. In FR1 it was a file number which changed from build to build and therefore was a problem.
Some coordinator have commented that publication of a userid is poor security.

**Comment by edickens** [comment]
Hi Kirk,
      I think this needs some debate.  The lineid field that you have
      defined is unique at any one point in time.  But what happens if a
      transcriber replaces the file after sorting it?  Or deletes some
      entries?  Or deletes the file as it was a duplicate?  True, these
      are not done often, but they do occur.
      The ideal reference to find an entry again would be
      Place/Church/Date.  This would not be unique, but usually no more
      than ten entries.  So perhaps an entry number for equal dates. 
      However, what do we do with UCF dates?  A Coordinator I think
      would be happy to be presented with a few entries that included
      what they were looking for.  The researcher should be able to
      quote (or get it included in a report) the place/church/date.
      But some lateral thinking:  What about marking a record when a
      researcher reports a problem with a "Problem marker"?  When they
      see a problem, they click a button which marks that record with a
      sequential number.  When the Coordinator gets the message to
      correct the error, the record can be found using this number.  It
      will always be unique.  This same system could also be used for a
      researcher to mark a record if they want to return to it.  If the
      record is already marked, the researcher can use that number.  A
      ten digit number should be large enough!  If the file gets deleted
      or replaced or anything else, then the number will be lost and
      some other method will be needed to find the record, but a message
      should say that the record no longer exists or has been amended. 
      I'm not sure of any other circumstances when a marker number
      should be deleted because the entry is no longer what they were
      looking at, even with a date or name change the marker should
      stay?
      The other option a Coordinator has is to scan the batch, and there
      has been a request for a report to be able to do this.  So is the
      lineid actually needed now, especially with a "Problem marker"?
      So thought needed.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 06/01/2015 16:22, Kirk Dawson wrote:
    
    
      We have a lineid field that has userid.batch.entry as a
        compound field. This was included so that coordinators can
        locate the specific entry when a researcher finds a data
        problem. In FR1 it was a file number which changed from build to
        build and therefore was a problem.
        Some coordinator have commented that publication of a userid is
        poor security.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
I am just transcribing some baptisms and at the preset point, (1835) there are OFTEN 50 or 60 entries with the same Baptism date. so its worse than "just a few" and happening much more frequently.
I would also comment on the topic of uploading a Replacement file: are there any stats on how frequently this happens ?  and what does Kirk's plan for recordId do in that case?

**Comment by edickens** [comment]
Hi EricB,
      Is that 50 or 60 on the same day in the same Church?  I have come
      across ten or so when a family is baptised, but then the
      researcher would want all of these.
      When we are live transcribers should upload their file regularly
      as they add more records to it.  But I don't know if this is
      delete and upload, or just replace changed records and add new.
      EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 07/01/2015 08:26, Sherlock21 wrote:
    
    
      I am just transcribing some baptisms and at the preset point,
        (1835) there are OFTEN 50 or 60 entries with the same Baptism
        date. so its worse than "just a few" and happening much more
        frequently.
        I would also comment on the topic of uploading a Replacement
        file: are there any stats on how frequently this happens ? and
        what does Kirk's plan for recordId do in that case?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Sherlock21** [comment]
Yes, 50 or 60 all on one day. Must have been like a production line! and not just the odd isolated day like this. 
Perhaps there is a major conflict of methodologies hear? Those Transcribers who will be working online can do a record be record upload or a shift by shift one however you like. But those who work off line, in spreadsheets, manage their job i spreadsheets so they can have the benefit of lookup past details when the handwriting or the image gets tough to read. They - and I am one of them - work most effectively with files of a 1000  or 3. and so this is the batch size that gets uploaded either as a first time completely new set, or as a "replace" because some more records have been added to the end of the previous set, and a few of the previous records might also have been changed with the benefit of hindsight from something done more recently. And the combinations  are infinite.

If there is a move to 'directing' the workforce to work in one particular manner, then it will be counter productive. So the methodology of the software, coping with the line naming, will have to allow for all these possibilities.

I suppose it will boil down to a case of: do the FreeReg  Exec want quantity or prescribed methodology?

**Comment by DarrenWright** [comment]
Isn't this issue less about whether there should be a lineID and more about whether it should be displayed in search results to the public? If the public don't know what it means and can't do anything with it then there is no point in showing it to them in the results.

**Comment by Captainkirkdawson** [comment]
Its purpose was to enable the coordinators to locate the record that the
researcher was referring to.

With some reprogramming we can have it as a field only seen by coordinators.

We could also consider adding some form of tagging the record when a
researcher considered there was an issue.

2 separate stories


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Hi Kirk,

Researchers also ask for this for their benefit.  I get emails from them 
complaining that the record number which we show them in FR1 brings up a 
different record when they use it again a few weeks later.  An update 
has taken place so it has changed.

That is why I suggested that rather than having a predetermined ID, we 
add one when requested.  So if there is an issue with a record we tag 
it.  If a researcher wants to return to a record, they tag it.  The tag 
only needs to be displayed if there already is one and it can be used 
again.  There is a bit more detail to discuss, such as what happens when 
a record is amended or a file is replaced, but I think the idea will work.

E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
The number we use does not change at all. It is the one visible unique record identifier.

**Comment by Sherlock21** [comment]
Was this LineID  number + the UserId of the transcriber when this topic began?

If so, has the UserID part been dropped? If not, then answering Darren's point: NO its a lot more than you suggest.AS It contains the UserID that's half of the secure logon.
And if you hide that, and just use the remaining part, is that still unique for life for that record?

Whatever reference you add as the LineID, it must not include Transcriber info of any sort if its going into the public domain.

**Comment by Captainkirkdawson** [comment]
The field is hidden for the researcher and visible to the transcriber/coordinators etc
