### ISSUE TITLE
API login/logout via Devise for WinREG

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#381]
Mike is blocked by needing a way to establish a Rails session, but none of us knowing off-hand how his WinREG tool can log in to the F2 site.  Surely there are other client programs that do authentication via Devise; we just need to research them and communicate an approach to Mike

**Comment by juliancheal** [comment]
We have two options, I believe: OAuth2, or roll our own with Devise

If we want to go down the OAuth2 route, there are plenty of examples of doing OAuth2 and this I would think would be the most secure.

The alternative would have been to have used to be Devise's token_authenticatable (http://blog.codebykat.com/2012/07/23/remote-api-authentication-with-rails-3-using-activeresource-and-devise/), but that's been deprecated due to security reasons. There are examples of securing an API in this Railscast http://railscasts.com/episodes/352-securing-an-api

**Comment by benwbrum** [comment]
Thanks, Julian!

@EmJayFry does that Railscast help?

**Comment by EmJayFry** [comment]
Can't tell at the moment. Got no power.

-- 
Regards
Mike Fry (Jhb)

-----Original Message-----

**Comment by EmJayFry** [comment]
Power eventually came back at 20.00 - a break of 5 and a half hours.

I've had a look at the Railscast and found it quite interesting. Particularly as there seems to be some .NET support for OAuth2. That should allow me to get the initial phase of my FreeREG2 development working. Just a lot of research.

**Comment by juliancheal** [comment]
Let me know if you need any help.

**Comment by EmJayFry** [comment]
I'm not sure that OAuth2 is the way to go. There's no real 3rd-party in this scenario. There's just the transcriber (represented by a browser or my WinREG program) and the FreeREG/2 server.

When using a browser to log in, the user sees a Login page, fills in the id. and password and clicks on a button. This is effectively the way that WinREG works with the FreeREG/1 server. I work with a DOM representation of the HTML pages and can continue to do this in the future. Provided that the DOM structure stays consistent, all I need to know are the identities of 3 things: the "Name" of the  login form (new_refinery_user) the "name" of the UserId textbox (refinery_user[login]), and the name of the password box (refinery_user[password]) . With these, I can then set the Value attributes of the id and password and then invoke the Submit method of the form. This is currently working! Even to the extent of extracting and storing the cookie information (myopicvicar something or other).

This methodology is not ideal, relying as it does on 3 things not in my control. But it's working. Eventually, I'd like to get to the stage whereby I can request a page from the server and include the userid and password as parameters to the request e.g. http://<server>/winreg/login?id=<user>&password=<password> or something similar and have the winreg controller do the login for me, passing back the session cookie(s).

So! That's where we currently stand. What's next?

**Comment by edickens** [comment]
Mike,
      I'm not sure what the first paragraph means, but I have seen how
      WinReg works with FR1.
      Since we are at the design stage, would it be better to create a
      special upload page that is only accessed by WinReg.  It would
      replace http://freereg2.freereg.org.uk/csvfiles/new which is
      equivalent to the FR1 upload module.  The advantage of this is
      that it will not change without reference to you and you can
      bypass some of the questions normally asked.  For example you will
      know the Filename, UserID and County.
      
      
      
      
      This special page could also access the Place and Church records,
      and anything else that you may need, even if they are not
      available to everyone else.
      EricD
      
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 19/02/2015 18:25, Mike wrote:
    
    
      I'm not sure that OAuth2 is the way to go. There's no real
        3rd-party in this scenario. There's just the transcriber
        (represented by a browser or my WinREG program) and the
        FreeREG/2 server.
      When using a browser to log in, the user sees a Login page,
        fills in the id. and password and clicks on a button. This is
        effectively the way that WinREG works with the FreeREG/1 server.
        I work with a DOM representation of the HTML pages and can
        continue to do this in the future. Provided that the DOM
        structure stays consistent, all I need to know are the
        identities of 3 things: the "Name" of the login form
        (new_refinery_user) the "name" of the UserId textbox
        (refinery_user[login]), and the name of the password box
        (refinery_user[password]) . With these, I can then set the Value
        attributes of the id and password and then invoke the Submit
        method of the form. This is currently working! Even to the
        extent of extracting and storing the cookie information
        (myopicvicar something or other).
      This methodology is not ideal, relying as it does on 3 things
        not in my control. But it's working. Eventually, I'd like to get
        to the stage whereby I can request a page from the server and
        include the userid and password as parameters to the request
        e.g. http:///winreg/login?id=&password= or something similar
        and have the winreg controller do the login for me, passing back
        the session cookie(s).
      So! That's where we currently stand. What's next?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by EmJayFry** [comment]
First paragraph was all about something Ben + Julian suggested that looked good at first sight. But now I'm no longer sure.

The API I've been mooting is all about setting up a special gateway for WinREG and its' successor to use in much the same way, without a lot of the inherent complexity, that WinREG currently does with FreeREG/1.

This API simply provides a simpler way for WinREG to access the server. For example, rather than collecting the list of a transcriber's files from the present File Maintenance  web page, we could request the server to send an XML file containing all  the details of the files that the server knows about for that transcriber. This I've already got working! As I also have, a method for downloading the contents of a file from the server to the PC. without resorting to displaying the contents on a web page.
