### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#399]
Need to develop a package of statistics for display to researchers

**Comment by edickens** [comment]
Kirk,
      Before you do, can we have a debate on what is needed.
      Thanks EricD
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 30/01/2015 00:17, Kirk Dawson wrote:
    
    
      Need to develop a package of statistics for display to
        researchers
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by DarrenWright** [comment]
This came up because there is a link to the statistics page in the footer
but no real plan around what they should contain.

I think a discussion of what is needed would be good in order to stop the
temptation to throw everything in there, less is more.

The things I think would be handy to reflect are headline stats on numbers
of records. The rate the database is increasing (this will be different
from current as the database won't be updated in monthly burst but will be
more incremental) and something about numbers of searches. I'm a little bit
dubious of the practical value of numbers of searches but as it
consistently seems to be a massive number it's always handy to have a
massive number in reserve for marketing purposes.

What else would we need?

*- -*
*Darren Wright*
Executive Director
Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
08452872816

**Comment by edickens** [comment]
I agree that all that is needed on the
      homepage, or nearby, is the total number of BA, MA, BU and the
      total.  There will be about 1K records added every day.  (FreeBMD
      will be much more.)
      
      The number of searches is quite useful since I get complaints
      about the FR1 server being slow and I refer the researcher to the
      statistics to show which times to avoid....
      
      
      
      
      Interesting here that there were no "Busy" periods.
      
      The other statistic I use a lot is the number of BA, MA, BU by
      county.  By comparing these month by month I can see which
      counties are really active, and which are slowing down and have a
      problem with data or transcribers.  Ideally this should be in the
      header of the Database Contents when the county is selected.
      
      E
      
      _____________________________________
Eric J Dickens
FreeREG Chairman
      On 30/01/2015 10:51, DarrenWright wrote:
    
    This came up because there is a link to the statistics
      page in the footer
      
      but no real plan around what they should contain.
      
      
      I think a discussion of what is needed would be good in order to
      stop the
      
      temptation to throw everything in there, less is more.
      
      
      The things I think would be handy to reflect are headline stats on
      numbers
      
      of records. The rate the database is increasing (this will be
      different
      
      from current as the database won't be updated in monthly burst but
      will be
      
      more incremental) and something about numbers of searches. I'm a
      little bit
      
      dubious of the practical value of numbers of searches but as it
      
      consistently seems to be a massive number it's always handy to
      have a
      
      massive number in reserve for marketing purposes.
      
      
      What else would we need?
      
      
      *- -*
      
      *Darren Wright*
      
      Executive Director
      
      Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
      
      08452872816
      
      
      
      
      On 30 January 2015 at 08:45, Eric Dickens
      <notifications@github.com> wrote:
      
      
      >
      
      >
      
      >
      
      >
      
      >
      
      > Kirk,
      
      > Before you do, can we have a debate on what is needed.
      
      > Thanks EricD
      
      > _____________________________________
      
      > Eric J Dickens
      
      > FreeREG Chairman
      
      >
      
      > On 30/01/2015 00:17, Kirk Dawson wrote:
      
      >
      
      >
      
      > Need to develop a package of statistics for display to
      
      > researchers
      
      > —
      
      > Reply to this email directly or view
      
      > it on GitHub.
      
      >
      
      > —
      
      > Reply to this email directly or view it on GitHub
      
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/399#issuecomment-72170568>
      > .
      
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by benwbrum** [comment]
Kirk just pointed me here after I started asking about search query statistics.  I think that stats on transciber activity and database coverage are very important--perhaps even more important than on search queries--but since I'm working on search queries for #316 I need to dive into that.

### Statistics Aggregation/Query Clean-up Task

At the moment I anticipate a nightly task that runs on each search server and does the following:

1. Aggregate the previous day's search query statistics from `search_queries` on that search server's local database.
   1. Find the date of most recent aggregated `search_statistic` record for this server, *R*
   2. Find the date of the oldest `search_query` record on this server, *L*
   3. For each interval *I* (presumed to be 1 hour) between *max(L,R)* and the most recent GMT midnight,
      * Aggregate search statistics for that interval
      * Put those statistics into a `search_statistics` record object (currently in memory)
2. Record those statistics in a new `search_statistics` collection in the replicated F2 via an insert (We're relying on the replica set's eventual consistency to propagate the record, which means that I'm comfortable with an insert but not with an upsert/merge.)
3. Delete those `search_queries` records which are older than *N* (presumed to be 7) days.

This will allow us (later -- possibly in this story) to surface statistics for searches once they have been aggregated.  It will not support seeing search performance from searches made since midnight GMT.

### Types of Search Statistics

The reports visible at FreeREG1 appear to only show the number of searches per hour.  I think that we should be able to collect more without much effort.  Here are the search statistics that present themselves to me:

* **Number of searches** performed during that interval
* **Total number of zero-result searches** performed during that interval
* **Total number of results** performed by all searches during that interval
* **Average number of results** performed by all searches during that interval
* **Total runtime** of searches during that interval (to be used to calculate mean)
* **Maximum runtime** of searches during that interval
* **Median runtime** of searches during that interval
* **Number of searches running for more than 1s** 
* **Number of searches running for more than 10s** 
* **Number of searches running for more than 60s** 
* **Number of full-county searches**
* **Number of date-range searches**
* **Number of radius searches**  (excluding single-place searches)
* **Number of place searches**
* **Number of record-type searches**
* **Number of soundex searches**
* **Number of surname searches** (blank-surname searches may be more interesting, but can be calculated)
* **Number of forename searches**

I'd also like to report on the searches that led to a user clicking through to an individual record--since presumably those represent a form of success--but don't see any good examples on the freereg2 site's `search_queries` collection.

### Next Steps

I'll be aggregating whatever we decide is interesting (and also meets the mandate in #316) and recording it in the F2 database.  However, recording data is not the same thing as exposing data, so I'd like to make sure we don't resolve this issue when I finish my `search_queries` work.  

Any changes to the data we want to record can be incorporated into the system after I add this code, before F2 goes live.  In fact, we can change our algorithms for recording information in a way that's not backwards-compatible after the launch of F2, so long as we realize that pre-change data won't show up correctly in whatever reports we write.

So I just want to reiterate that defining `search_statistics` functionality doesn't entirely address this #399 issue.

**Comment by Sherlock21** [comment]
I like your thinking, Ben.
May I add:
Number of searches that time out due to being too complicated?
Number of searches that are rejected due to mandatory fields not being completed.

Your comment about Can't find records of clicking through to details: I'm surprised, asI have dome several of these in the past week.
I will do some more now -  searches of 1 detail  click through on a result (for Dewsbury), then with 5 click throughs on each of 2 results -(for Thornhill. all on the logon url freereg2/freereg.org.uk

**Comment by Sherlock21** [comment]
An interesting point was observed in this set of click-through to detail: even though I did a "Revise Search" for the First of the repeats, and a "New Search" start for the last of the 3 tests, I used the same surname and place, but a wider data range, and the result list still showed the Viewed marker form the previous  tests. Not what I expected from a New Search even though the same record was in each batch. A >New Search should perhaps wipe the slate clear?

**Comment by edickens** [comment]
The things I look for in FR1 are "Failed" and "Busy" searches.  This is a sign of frustration to a researcher and will tell us when we need to think about increasing capacity.

**Comment by benwbrum** [comment]
Turns out that I was looking in the wrong place on the record, so returning to the problem this morning, I found the list of record IDs returned by each search.  However, my assumption that this list was where we stored the click-throughs (in order to render the 'viewed' text next to the records in the list) was mistaken. Instead, that's stored on the user's session, which is necessary to keep from blanking that list between each search.

I do believe that we can track click-throughs, but not on a per-search level.  Rather, watching the logs for requests to /search_records/show should yield that data.  (Postponing that for later, as it won't be part of my work on #316)

Thanks for pointing me in the right direction, @Sherlock21

**Comment by benwbrum** [comment]
Sadly, we're not logging queries that were rejected for not having required terms, as those never make it to the database to be executed.

How are "Busy" and "Failed" defined in F1, @edickens ?

**Comment by Captainkirkdawson** [comment]
The number that yield results in excess of our maximum allowed would be useful

**Comment by Sherlock21** [comment]
Back to which stats to count: As I was party to the limit of "Results Display is restricted to 250 records", I would suggest you count how many times the limit is reached in the review period, and what the total available were, with no limit in place. - with a view to raising the 250 limit if justified.

**Comment by Sherlock21** [comment]
Actually, my above post amounts to what Kirk has also said. I wrote mine a while ago but did not send it right away!

**Comment by benwbrum** [comment]
Okay, it looks like these are the statistics we'll be able to support, which is essentially the list above, minus the *median results per search* (which are both computationally intensive and invalid once you try to aggregate), the *number of click-through searches* (discussed above), but adding *number of searches that hit our limit*.

Please give this a skim and let me know if I left anything out.
```ruby
  # Search Statistics aggregate a single hour's
  # worth of search queries for a single database
  # 
  # This follows a denormalized star schema, with
  # a database dimension, a date dimension, and
  # a fact table populated by search_queries

  ###################################
  # Date Dimension Attributes
  ###################################

  field :year, type: Integer
  field :month, type: Integer
  field :day, type: Integer  
  field :hour, type: Integer  

  ###################################
  # Database Dimension Attribute
  ###################################
  field :db, type: String  

  ###################################
  # Facts 
  ###################################
  #
  # Number of searches during the interval, by result type
  field :n_searches, type: Integer      # total number of searches
  field :n_zero_result, type: Integer   # zero-result searches
  field :n_limit_result, type: Integer  # searches which hit the limit
  #
  # Total results during the interval
  field :total_results, type: Integer   # total results returned by all queries
  #
  # Aggregate runtime statistics
  field :total_time, type: Integer  
  field :max_time, type: Integer  
  #
  # Number of searches during the interval, by run time
  field :n_time_gt_1s, type: Integer    # runtime > 1 second
  field :n_time_gt_10s, type: Integer   # runtime > 10 seconds
  field :n_time_gt_60s, type: Integer   # runtime > 1 minute
  #
  # Number of searches during the interval, by search criteria
  field :n_ln, type: Integer            # surname searches
  field :n_fn, type: Integer            # forename searches
  field :n_place, type: Integer         # specific place searches
  field :n_nearby, type: Integer        # radius searches
  field :n_fuzzy, type: Integer         # soundex searches
  field :n_inclusive, type: Integer     # search additional family member names
  field :n_0_county, type: Integer      # blank county
  field :n_1_county, type: Integer      # county (exactly 1)
  field :n_multi_county, type: Integer  # county (more than 1)
  field :n_date, type: Integer          # date range
  field :n_r_type, type: Integer        # record type
```

**Comment by DarrenWright** [comment]
Hi,

The things like searches that time out and progress to successfully are
interesting and useful from a management point of view but are not useful
on a public stats page.

We don't want to broadcast to the world if we're not completing searches
properly.

We need to make a distinction between useful information and useful
information for the public.

Thanks

*- -*
*Darren Wright*
Executive Director
Free UK Genealogy <http://www.freeukgenealogy.org.uk/>
08452872816

**Comment by benwbrum** [comment]
That's a good point.  I'm recording it at the moment for #316, but there needs to be a separate conversation (indeed, that's what this thread is) about what to display to which audiences.

**Comment by Sherlock21** [comment]
Darren raises an important issue here.
I had assumed that we were only discussing Management stats topics here. - perhaps I should have clarified the matter at the top of this discussion.
If Ben could give the list of stats  2 columns - Management & Public. with Yes in appropriate column for who can view?

Then at least we all know what we are signing on to! - or am I the only one out of step?

**Comment by Sherlock21** [comment]
Sorry Guys! I have gone back and read all from the top. And yes, this started off as: Stats for Public.
In which case, I think very few of these topics in Ben's summary should be public.
Perhaps only How many searches successful in the last 7 days.
Or How many searches performed.
Things which can attract advertising.

NOT Management stats that are the foundation for improvements &  alternatives.

**Comment by edickens** [comment]
I forgot to add that some CCs like to add the totals to their Progress Pages.  See 
http://www.freereg.org.uk/parishes/dur.htm
so should we show County Stats to researchers as part of the Database Contents?
You might like to ask Amanda who she thinks uses this.
EricD

**Comment by Captainkirkdawson** [comment]
The  County stats has been implemented
