### ISSUE TITLE
Search Performance: Limit/kill long-running results

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#428]
While experimenting with the cluster and considering the number of indexes on search records I started looking at search performance.
While most searches seem to perform well. I found it easy to cause time out and gateway problems. 

Especially if one used soundex with no county specified and where one is likely to have a large number of results.

**Comment by Captainkirkdawson** [comment]
Hit enter too soon.

Firstly I observed that selecting soundex applies it to both surname and forename fields.

Secondly the limit really only limits the number of records preferred for display, it does not seem to limit the number of records actually retrieved by the search.

**Comment by Captainkirkdawson** [comment]
First Name: WILLIAM
Last Name: BRUMFIELD
Exact Match?: No
Record Type: Marriage
Start Year: 1600
End Year: 1650
Explain Plan

--- !ruby/hash:Moped::BSON::Document
cursor: BtreeCursor record_type_search_soundex_ln_fn_sd
isMultiKey: true
n: 24
nscannedObjects: 44
nscanned: 44
nscannedObjectsAllPlans: 175
nscannedAllPlans: 177
scanAndOrder: false
indexOnly: false
nYields: 1
nChunkSkips: 0
millis: 1
indexBounds:
  record_type:
  - - ma
    - ma
  search_soundex.last_name:
  - - B651
    - B651
  search_soundex.first_name:
  - - W450
    - W450
  search_date:
  - - ''
    - '1651-03-25'

**Comment by benwbrum** [comment]
The limit does indeed not terminate queries after 250 records.  I agree that we need to pursue server-side limits/timeouts.

First name soundex is probably the result of me mis-understanding SOUNDEX when I first started on this.  I'd assumed that it was a generic algorithm similar to metaphone, when actually it's very specific to English-language surnames.  

Pruning first-name soundex means:
* Decide that fuzzy matching first names is not a valuable feature when/if we ever move from SOUNDEX to double-metaphone.
* Change the search_query code to not search on `soundex(search_query.first_name)=search_record.search_soundex.first_name` but `search_query.first_name=search_record.search_soundex.first_name` (counter-intuitive, but more on this in a bit)
* Change the search_record transformation code to put `transcript.first_name` into `search_soundex.first_name` instead of using `soundex(transcript.first_name)`

**Comment by benwbrum** [comment]
The result of refactoring first name soundex as above should be fewer records returned to users when they choose an inexact search.  I don't think that there are any performance gains to be made unless more substantial refactoring of the search_record data model is undertaken.

Do we want to do this now?  I've added the Version 1.1 milestone tag, but we might want a different one instead.

**Comment by edickens** [comment]
Ben,
    
    If I understand this story correctly, you are removing Soundex from
    the firstname.  I don't think this should happen.  Variations in
    Firstname are just as common as those in the Lastname.  We also
    state that we will match Latin versions of names with English, so is
    this still happening.  There are also a lot of abbreviations in
    Firstnames.
    
    But, we could advise researchers just not to enter a firstname on
    the first attempt.  They can then enter something if they get too
    many results.
    
    With no Wildcard, we do need Soundex.
    
    EricD
    _____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
I tend to agree with EricD above.
Names often vary due to the poor spelling of the scribe and/or the bad transcription misreading a,o,e for example.
And the "differs" versions of a name - first name or surname - is surely an English language & dialect thing so the code used needs only to offer English variants. - hopefully what Soundex does.
 BUT we should tell users that this is the case, if it is so.

**Comment by Captainkirkdawson** [comment]
This is in now restricted to improving of search performance in terms of search timeouts as it appears that the limit does not in itself seem to limit the number of retrievable results but just the actual returned results from the set of retrievable results. The latter is useful but not sufficient to stop long running searches.

**Comment by benwbrum** [comment]
Agreed with all above, and have changed the issue title to reflect new scope.

**Comment by benwbrum** [comment]
Note that Kirk has moved discussion of first name soundex to issue #429
