### ISSUE TITLE
First name soundex?

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#429]
Ben wrote:
First name soundex is probably the result of me mis-understanding SOUNDEX when I first started on this.  I'd assumed that it was a generic algorithm similar to metaphone, when actually it's very specific to English-language surnames.  

Pruning first-name soundex means:
* Decide that fuzzy matching first names is not a valuable feature when/if we ever move from SOUNDEX to double-metaphone.
* Change the search_query code to not search on `soundex(search_query.first_name)=search_record.search_soundex.first_name` but `search_query.first_name=search_record.search_soundex.first_name` (counter-intuitive, but more on this in a bit)
* Change the search_record transformation code to put `transcript.first_name` into `search_soundex.first_name` instead of using `soundex(transcript.first_name)`

We're still going to need first name values in the search_soundex array in order to correctly match first and last names in marriages.

**Comment by Captainkirkdawson** [comment]
Ben wrote:
The result of refactoring first name soundex as above should be fewer records returned to users when they choose an inexact search.  I don't think that there are any performance gains to be made unless more substantial refactoring of the search_record data model is undertaken.

Do we want to do this now?  I've added the Version 1.1 milestone tag, but we might want a different one instead.

**Comment by Captainkirkdawson** [comment]
EricD wrote:
    
    If I understand this story correctly, you are removing Soundex from
    the firstname.  I don't think this should happen.  Variations in
    Firstname are just as common as those in the Lastname.  We also
    state that we will match Latin versions of names with English, so is
    this still happening.  There are also a lot of abbreviations in
    Firstnames.
    
    But, we could advise researchers just not to enter a firstname on
    the first attempt.  They can then enter something if they get too
    many results.
    
    With no Wildcard, we do need Soundex.

**Comment by Captainkirkdawson** [comment]
Sherlock21 wrote

I tend to agree with EricD above.
Names often vary due to the poor spelling of the scribe and/or the bad transcription misreading a,o,e for example.
And the "differs" versions of a name - first name or surname - is surely an English language & dialect thing so the code used needs only to offer English variants. - hopefully what Soundex does.
 BUT we should tell users that this is the case, if it is so.

**Comment by Captainkirkdawson** [comment]
We need to think about this in the cold light of day. 
In matching a forename we already, I believe, take into account of abbreviations and latinizations of forenames. So what does a Soundex of forenames add and is it useful? Lets research and take an informed decision.
I am not aware of any other search engine using a soundex of forenames. But that in itself is not a reason for eliminating. Leaving forename blank  gives a larger set of results than a forename soundex would. The latter is closer to a form of wildcard eg L* (for a L)

**Comment by Sherlock21** [comment]
Kirk asks (above) the question What does Soundex bring to the party, in respect of First Names? 
Abbreviations  and Latinisations are different things, being take into account by other bits of processing I hope. Sounded should ope with spelling errors like the name having vowels changed ( Jane being written as Jone or June OR Hepzybah- becoming Ephseyba or Hephsybah. so i see it as having a function either AFTER one has done a Surname Only search and got such a lot of results, one homes in on First Name + Soundex
OR one does it all together then uses Sort Order to get the results into blocks that have some sort of order.
Obviously, with the overall limit in Numbers < 250 records, its not as useful as in the olden days of a few thousand returns.

Since this topic is now about killing long-running results, are we sure we wish to keep the limit at 250? Having done several searches last week or two, I would like to perhaps double the present limit if possible.

**Comment by Captainkirkdawson** [comment]
No Eric this topic is about soundex of forenames. 428 is about long running searches

**Comment by Sherlock21** [comment]
Kirk: on my screen, what starts as "First Name Soundex #429" ( by yourself) then morphs into Search Performance: limit/Kill long-running results #428.\\

You can't blame me for that, nor for muddling them up!

**Comment by benwbrum** [comment]
Possible duplicate: see issue #462

**Comment by Captainkirkdawson** [comment]
Definite duplicate
