### ISSUE TITLE
Database Contents (Mobile)

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#444]
The mobile displays for database contents need revision

**Comment by PatReynolds** [comment]
Could you explain what this means?  I have just tried FreeREG2 on my android phone, and it looks lovely!  I have the text displayed as 'large', and it is fine with that.

**Comment by Captainkirkdawson** [comment]
Only the search pages and results have been tailored to display on a mobile (Glad you like it). You will see the issue if you access the Database Contents.

**Comment by PatReynolds** [comment]
Thanks - I now understand the issue

**Comment by PatReynolds** [comment]
Not sure if it is this issue, or 205:
Alison O'Neill commented: I am pleased to see that mobile devices/small screens are being catered for, although there a clearly a few tweaks to be made to the layout so that in-between screen widths flow nicely. I am seeing a horizontal scroll-bar more often than not as I resize the window -- it is annoyingly present at my preferred window width.  I am using the latest Firefox on a Mac.

**Comment by edickens** [comment]
Hi Pat.  I noticed that too.  Sometime there is a scroll-bar when it is 
not needed as everything is on the screen.
On that subject, FR1 PPP uses a different system whereby the data is in 
a table and only that scrolls, leaving the column headings.
E

**Comment by Captainkirkdawson** [comment]
See #555
