### ISSUE TITLE
Distribution of Data error messages

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#468]
It is not easy for the Data-Manager to know who has seen the message

**Comment by Sherlock21** [comment]
Can you make these data error messages REQUIRE a County and Place Name please - so we don't have to fish about and guess when its a specific issue like a possible Transcription Error.

**Comment by edickens** [comment]
I have just reported a transcription error (genuine) and so got an email back confirming my submission.  But, although it shows everything that I said, it does not give details of what I searched.  This would be helpful to the submitter so that they know what they were commenting about and that they know that we know the record to which the report refers.
E

**Comment by edickens** [comment]
Another thought:- Since I did not specify a County in my search, which CC did the message go to for correction?

**Comment by Captainkirkdawson** [comment]
The county for which the transcription was located in.


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Request for clarification of requirements made

**Comment by edickens** [comment]
Transcription Errors, which are as a result of a search, to the CC with 
copy to reg-corrections@freereg.org.uk presently Bob Wilkins and Mick 
Claxton.

Database Contents Errors to the CC with a copy to 
reg-data@freereg.org.uk presently Mick Claxton, Eric Booker and myself, 
as it is likely to be a Place name problem.

Any other screen to reg-web@freereg.org.uk although this presently goes 
to Ben Laurie and myself, so may need changing.

We can create new lists and the advantage of these are that names and 
email addresses are easily changed.  However, a distribution system 
within FR2 might be preferable.

E

**Comment by Captainkirkdawson** [comment]
If you wish to continue the use of the FR1 system of messaging so be it.  Although it will require manually updating of email addresses in 2 places. FR2 has no knowledge or access to the FR1 messaging system from a maintenance and updating perspective.. 
The downside of the 3rd paragraph is that you and Ben Laurie will have to deal with those issues rather than Ben Brumfield and myself.
The Database Contents errors cannot be copied to the CC as there is no requirement to identify a county.
The collection and processing system will require a redesign to accommodate the separation of Transcription errors and Database Contents errors as those are currently dealt with as one distribution process. (They have separate input streams)
Do not see the creation of new lists as an advantage as any new lists will require implementation design and coding
Are there any other issues with the system that require modification as we would not want to open this code up again this year (except for bugs)

**Comment by edickens** [comment]
I don't want to use the FreeREG alias distribution system in particular, but I feel that we need a system where the recipients can be amended easily, and this could be people who do not have registered UserIDs.  Can this be built into FR2 other than through this system?  This sends messages to everyone registered with it.
When someone looks at the Database Contents they have to select a county, so could that be used to identify the CC?
Transcription errors will be just when someone is Searching rather than using the Database Contents.
These two methods of deciding between Data Manager and Corrections Manager may not always be correct, but it will be better than sending to everyone.
I've not yet contacted some CCs, Data Manager and Corrections coordinator over this because I would still like to investigate what is possible and most easily managed.

**Comment by Captainkirkdawson** [comment]
The contact system users are only registered users. 
Do not understand "everyone registered with it" We only send messages to the involved CCs as well as the DM. As noted previously we can change this to just Corrections Coordinators if that function is desirable.
Contacts can be generated from any page. They have no affinity to the Database Contents. So there is no ability to do as you suggest. My original design that had users identifying county etc was rejected by Management for valid reasons.
It is possible to have a separation between contacts generated as a specific report on a data record and those generated from the Data Problem heading of the the contact. These could be restricted to the DM
