### ISSUE TITLE
How to handle special characters?

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#469]
FR1 files contain characters such as É which upset the updating system

**Comment by edickens** [comment]
I appreciate that by entering a different character set code these special characters can be processed.   This is not a "Mac" problem, but is caused by transcribers entering TWYS.
The problem now is that these characters have been accepted by FR1 and could be in hundreds of files.  It doesn't seem right to have to amend each individual file as it comes up as an error when it is amended and so updates FR2.
And if these records are being omitted from the update, were they omitted from the original creation of FR2?  If so, how can we identify these records?  We only find them when the file is updated and there are tens of thousands of files which may never be updated.
I think some other system is needed, such as to trap the errors and automatically try different character sets.

**Comment by benlaurie** [comment]
Do you have an example of such a file?

I believe in FR1 the majority (all?) files are in 8 bit character sets. If so, there's no automatic way to know which set is correct, though I'm guessing we could probably guess.

These days we have a universal character set: Unicode. I suggest we standardise on that somehow.

**Comment by edickens** [comment]
Yes, quite a few.  It shows in the overnight update log, for example

Cjvk	KENBRLMA5.CSV
Cjvk	KENBRLMA5.CSV *barfed the system*************
"\x8D" to UTF-8 in conversion from Windows-1252 to UTF-8

E

**Comment by Captainkirkdawson** [comment]
EricD
The example you provide is NOT the issue of special characters that you used in your introductory statement. The only characters that give FR2 difficulty are the 5 characters for which there is no character representation.
FR2 supports all special characters in the CP1252 character codeset. It uses a conversion of that codeset into Unicode.
If there are missing special characters then it is likely caused by  WinREG which uses a subset of CP1252 that does not include a number of special characters. It uses iso-8859-1. 
See http://www.i18nqa.com/debug/table-iso8859-1-vs-windows-1252.html

In there you will see the 5 unassigned characters.
