### ISSUE TITLE
Browsing a batch of records

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#476]
We often get requests to look through a transcription because a search has not produced a result

See also https://github.com/FreeUKGen/MyopicVicar/issues/1405

**Comment by edickens** [comment]
I can understand this request because there are so many variations to a name and Soundex will not find them.  And we have to include UCF and abbreviations in this list.
So should we provide a cut down report of a County/Place/Church where a researcher can browse just Year and Lastname?  If they find a likely entry, then they can select to see the detail.  In this way they will see entries that could be what they want and then check them out without the ability to skim and copy the whole transcription.   I have deliberately said not to show the Firstname and full date because in older register entries that is all there is, so we would be showing the full entry.  By just showing Year and Lastname we are not giving much away.
Thoughts?

**Comment by edickens** [comment]
Perhaps it would be better to ask for the first letter of the Lastname rather than showing all names.  This could be a good alternative to Wildcard.

**Comment by Sherlock21** [comment]
I have a lot of sympathy with those who prefer to scan down a list of whats there, in order to get some clues of where to start.
But i am sure, from the emails we have just had from "professionals" and webcrawlers, that this would be the wrong thing to do.
We said long ago, that we must assume Researchers bring something to the party, by way of basic knowledge or clues as to where they need to start a search of our records.
You can do  search by Full County, or add in  Place name and couple with first name only with & without soundex. Or surname only, with or without soundex.

When we get the feature which does Similar abbreviations and Latin versions of names, that will be a big step forward.

We did also discuss allowing Wild Card. I can't recall the exact conclusion but it was considered a good idea if there is a minimum number of letters provided in such a search.

So taken together, I would say there will be sufficient flexibility here. And We can still defend our integrity re: not giving the crown jewels away in these circumstances.

**Comment by edickens** [comment]
Yes, and if they want to see more they can volunteer to transcribe
    and then get access to the images, having agreed to the "Transcriber
    Agreement".
    _____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
I believe that the unique names offers an appropriate solution to this requirement

**Comment by PatReynolds** [comment]
I think you're right, @Captainkirkdawson I realise I have been using so far with names-easy-to-mishear or easy-to-misspell, so have experimented with the Smiths of Dodford (Northants) to see whether not being able to filter by year would be an issue.  Variants are *   -   0   SMITH  SMITH?  SMTH  SMYTH  
I could find the variants with letters, but not the symbols/figure. Is there a way of searching for 'matches no alphabetic characters in surname'?

**Comment by richpomfret** [comment]
Closing.
