### ISSUE TITLE
Write down what the coordinator implementation process is

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#488]

**Comment by edickens** [comment]
I think the underlying principle should be to find information for 
correcting the Places/Churches/Registers/Years in FR1 so that after the 
overnight update these corrections are moved across into FR2.

So it will be:-
- Check Place names and correct in FR1
- Check Church names and correct in FR1
- Check Register Source and correct in FR1
- Delete "Unapproved" places with no records
- Delete duplicated church names where spelling errors have been 
corrected and there are no records

After that we can then start to enter extra data such as:-
-Year range of Churches
-Registers available for transcribing but not started

This will lead to more corrections in FR1, such as records outside the 
date range.  (We may need more validation on the overnight update)

Then they can move on to SC functions:-
- Check status and experience of their UserIDs.

And then we get into the detail of allocated work.
- Dealing with new UserIDs.
- Training
- Preparing for images.

All this is needed before we can progress to V1.3.

EricB is very keen that we tidy up the Place and Church names as this is 
what is presented to Researchers, and I agree, but it has to be done by CCs.

If you agree, I will first of all try this out on the development team 
(EricB, Bernie, Howard and Julie)  Then to all CCs.

E

**Comment by Captainkirkdawson** [comment]
A good start to the epic.
I suggest that you get buy in to the approach.
Then we focus in on Phase 1 as the activities to be done during the next sprint.
Other phase can then be refined
