### ISSUE TITLE
WinReg - Inconsistant validation

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#494]
It seems that the validation of files from FR1 does not check BU Relationships set out in the standard set on the Transcriber Help pages

**Comment by edickens** [comment]
While checking out a BU file, I found  that WinReg, FR1 and FR2 seem to do different things.  WinREG rejects entries that are not in the standard list of Relationships - which would seem to be the correct thing to do -, FR1 seems to accept anything, and I am not sure if FR2 also checks, but if we want to be able to analyse the relationship field we will need to have it standardised. 
So do we want to standardise it?  If so what do we do with existing files?  Should we tighten FR2 validation so that at least no more invalid entries are uploaded?
E

**Comment by Sherlock21** [comment]
As you know, I have argued for providing data in a form that we can analyse. We may not do analysis now, but if the data is standardised now, then we can do analysis in future.

So my  vote goes to " don't add to the increase of unvalidated data". 
and furthermore, as soon as we are in a position of reasonable certainty that we will not do another total reload from F1, then introduce validation of your field(s) concerned at the time of upload into FR2.
Then do a once off correction job to the existing FR2 data to get it into the condition that matches the validated stuff.

**Comment by Sherlock21** [comment]
"standardising" of fields for later analysis obviously begs the question of WHICH fields so to treat - bearing in mind the rule of TWYS.
So here is my starter suggestion:
All Even dates must be a real calendar date. IF its wrong in the original, eg like 29 Feb 1821 then enter 28 Feb 1821 and put the Register value in the notes field with a comment.
All place names must be correctly spelled - if not use correct Event Place and Abode Place name & add the Actual register entry in the Notes with comment.  
All Baptism sex fields should be M/F or blank. not d or dau, S or son.
All Burial Abode fields should be just the Real Place name ( from the Place names table). If a whole street name address is recorded, add it all in as  Notes.

What about Occupations?
What to do with Single Woman,  Spin, Illegit and similar abbreviations relating to the subject of a child born out of Wedlock and noting that many such births have no such comment at all. > put in notes only? 

Any more?

**Comment by Captainkirkdawson** [comment]
Mike Fry wrote
This is in reference to the FR1 file SOMBECBU that I have been discussing
with Eric.

What I found in the 6982 records were 1264 errors when I validated it with
WinREG.

8 of these errors concerned double-dating errors (missing second year)
4 of these were false positives concerning double-date format errors
The rest were all to do with Relationships.

The 4 false positives all related to a date in which the last digit of the
year was denoted as unreadable and the _ UCF character used. WinREG has a
slight problem with these dates and marked them as needing to be
double-dated. Objectively, I don't see how WinREG can do this. The year
(175_ in all 4 cases) is indeterminate and I have now changed WinREG so
that it no longer attempts to check the double dating when a UCF character
is found. WinREG thus delegates the responsibility on to FR1 for now, and
to FR2 in the future.

The Relationships errors are all to do with people not reading the basic
instructions on the website, and being far too strict with the TWYS
directive. For example, the website says to use 'dau of' whilst this file
has numerous examples of 'daughter of'. Also, 'infant' and 'child' have
been used as a relationship when these are allowed in the Age field. An
amusing entry, transcribed far too literally has a relationship of 'child
of' and the male relative's name as 'christ'. The CC ultimately responsible
for this file is going to have some fun correcting and adjusting these
gaffes.

Before he disappeared until the weekend, Eric indicated that WinREG (and,
by implication, FR2 as well) should adhere to a fixed list of standard
relationships: more than we currently have. His phrasing was as follows:-

"WinREG must stick to the list of relationships that we have since we think
technical researchers may want to analyse our database and so standard
relationships are needed.  And as you say some are ages not relationships.
We need to amend the FreeREG2 validation if we want to standardise. "


Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
May I now suggest that we keep things as they are until V1.6.  That is WinREG validates Relationship according to the rules, FR1 and FR2 accept anything.  We don't want to delay things.
E

**Comment by Captainkirkdawson** [comment]
How can something that is 3 years old is urgent????????????

**Comment by SteveBiggs** [comment]
This is precisely why I have suggested a review of all "Urgent" issues in the next scrum. If they are truly urgent they should be brought up for action, otherwise the urgent flag should be removed.

**Comment by PatReynolds** [comment]
In light of current revision of WinFREEReg, can this be closed?

**Comment by SteveBiggs** [comment]
Yes. There will be no further work on WinREG.
