### ISSUE TITLE
Radius search is omitting the base place

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#502]
When a radius search is requested the centre of the search is omitted, so the researcher gets unconnected results

**Comment by edickens** [comment]
Researcher said...

 Email
shirley.elrick@gmail.com

Message
Possible error in search mechanism - Free Reg
I search for UTTING in Poringland Norfolk, ticking all 3 boxes.
RESULT
Last Name UTTING
Exact Match? No
County Norfolk
Place Great Poringland (including 40 additional places within 5.3 miles )
Include Family Members Yes

NONE OF THE RESULTS have Poringland as the location, but I know from previous searches that there should be.
I click on revise search and remove the tick in 'search nearby places'. This is the ONLY action I take before clicking the search button again.  My results now show 65 results, all from Great Poringland
Methinks something is wrong at your end??? SHIRLEY

**Comment by Captainkirkdawson** [comment]
I am unable to duplicate this situation. The stated search produces more than 250 results. See screenshot. The results are the first 250 we encounter. The rest are not displayed or retrieved. 
As we state the search needs to be revised. If this specific search is narrowed several times the researcher will observe that when the limit is NOT exceeded then Great Poringland entries are indeed in the list of results. Methinks the researcher needs to read the message.

![great poringland](https://cloud.githubusercontent.com/assets/2874694/8144682/11ed7e60-11a7-11e5-86d5-0fdbab9bf2d2.JPG)

**Comment by Sherlock21** [comment]
I am surprised that you have closed this!

It depends on how you manage the finding of the records that fall within the max radius.

If you find the place names within the minimum radius, and get the records for those places.Then if less than 250 in number, get the next place going outwards, and add in the records form there. and so on increasing the radius to get to the Max limit of 250 records. That way, the "fail" due to exceeding the max number will not be useless to the researcher. They will get something out of it, and change the search parameters as they need based of the some they got.

THEN the origin place records (if there are any) will always be in the set. If there are no actual Origin records that meet the criteria, then the the output will show the true position and the Nearest ones will satisfy the researcher. - which is perhaps a point we missed in testing!
