### ISSUE TITLE
Update emmendation process

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#508]

**Comment by edickens** [comment]
In last night's tighter validation of the places "Dudley Staffs" records were reported because this is an "Unapproved" place name.  Were these just reported or rejected?
If I remember correctly, I thought that you said that "Unapproved" is just a Reported not Rejected.  If they were rejected, I am happy with that, I just need to be clear as to what happened.
The report does not say "Not processed" as your other reports do.  If they were rejected, can you add these words to clarify.
(More detailed email being sent.)
E

**Comment by edickens** [comment]
I have now seen a new report from Kirk, which is very useful, and note that these records are Rejected.  So all that is needed are the words "Not processed".
E

**Comment by Captainkirkdawson** [comment]
Wording change done
