### ISSUE TITLE
Implement updated abbreviations/latinizations

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#516]
We did a great deal of research on the abbreviations and latinizations within the freereg dataset.  Nevertheless, we did not actually update the list of emendations applied to the search engine.

We need to do a full review of the forename data, update the list of emendations, then run the emendation application again.

**Comment by Sherlock21** [comment]
Does this mean that you will send it ( the table) out in some easy form? or put it somewhere for all to access and add lines to?
Or were you thinking of a different approach?

Who is to be asked to review & Add please? All CC's and Managers?

**Comment by benwbrum** [comment]
I need to send someone (probably you) the following:
1) My findings in the forname distribution research I did a year or so ago,
so that we can look for patterns and decide which rules make sense
2) A readable CSV file with the emendation rules that currently exist so
that you (or whoever tackles this) can modify them for use in the search
engine.

Ben

**Comment by Sherlock21** [comment]
Hi,Ben

If you sent it to me at my Virgin.net email,then its just crashed!

try: eric@jandeb.co.uk anyway please - its my new one.
Then Ii will look tomorrow  - just giving up now I have had enough for today.

best wishes,
EricB

**Comment by benwbrum** [comment]
Hi Eric.

Take a look in your gmail account for a thread with the subject "forename analysis" from the last day of May/first of June, 2014.

Ben

**Comment by benwbrum** [comment]
The research for this has been done by @Sherlock21 -- at this point we need to formalize it into the search engine and apply it.

**Comment by PatReynolds** [comment]
Does this include R finds Richard and Richard finds R (etc.)?

**Comment by benwbrum** [comment]
It does not.  We should consider explaining the emendations we apply
somewhere in the application, possibly in the documentation, but possibly
through the app itself.

**Comment by Captainkirkdawson** [comment]
Feedback: 31966401. I notice that you suggest that the transcribers input the data as it is written and that your system returns variations, but not usually abbreviations. Wm is a common abbreviation for william, would it be possible to include that under william. It has tripped me up multiple times. I do very much appreciate your system. Thank you, Rod

**Comment by edickens** [comment]
Are we still planning to have a system for registered researchers to
    add variants of names which will then be used for searching?  In
    this example they could  then have added Wm themselves.
    But in this case, the advice should be to search without firstname
    and if too many results filter by date before firstname.. Our
    researcher entered variants should only be for lastname.  Are
    Firstname variants really necessary?  E
    
    On 06/01/2016 00:02, Kirk Dawson wrote:
    
    
      Feedback: 31966401. I notice that you suggest that the
        transcribers input the data as it is written and that your
        system returns variations, but not usually abbreviations. Wm is
        a common abbreviation for william, would it be possible to
        include that under william. It has tripped me up multiple times.
        I do very much appreciate your system. Thank you, Rod
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dougkdev** [comment]
Looking at the list of recommended emendations from Eric Booker, which he
based on the forename analysis done by Ben B. on the FreeReg data, I make a
couple of observations:
1) There are several in which the same abbreviation should be expanded
differently based on the gender of the person, such as Alex => Alexander
(male) / Alexandra (female).
2) Quite a few of the "abbreviations" listed for expansion are actually UCF
names.

Regarding observation 1, I have added code to support gender-based
emendations.
Regarding observation 2, there is also story #42 (UCF Search support), and
I need to confer with Ben on his plans for handling UCF to determine
whether these UCF names should be added as emendation rules, or whether he
will be handling them some other way.

Also, existing search_records will have to be re-transformed for all
records affected by changed emendation rules, so we may want to wait to
apply them until we pick up the other changes that also require
search_records to be updated (wildcard, etc.).

**Comment by edickens** [comment]
Hi Doug,
    
    I would like "some other way".
    
    Perhaps we should add to V1.6 Roadmap the need for extra fields.  We
    need the TWYS field, but also the transcriber's searchable version
    of most fields.  If there is no problem, both fields can be the
    same, but if there are any abbreviations or UCF, then the
    transcriber should enter something in the new field.  Computers
    should not make assumptions.
    
    At the same time we need some extra fields, such as the
    Transcriber's Notes, which are different to any Notes entered in the
    Register.
    
    Eric
    
    On 25/02/2016 05:26, dougkdev wrote:
    
    Looking at the list of recommended emendations from
      Eric Booker, which he
      based on the forename analysis done by Ben B. on the FreeReg data,
      I make a
      couple of observations:
      1) There are several in which the same abbreviation should be
      expanded
      differently based on the gender of the person, such as Alex =>
      Alexander
      (male) / Alexandra (female).
      2) Quite a few of the "abbreviations" listed for expansion are
      actually UCF
      names.
      
      Regarding observation 1, I have added code to support gender-based
      emendations.
      Regarding observation 2, there is also story #42 (UCF Search
      support), and
      I need to confer with Ben on his plans for handling UCF to
      determine
      whether these UCF names should be added as emendation rules, or
      whether he
      will be handling them some other way.
      
      Also, existing search_records will have to be re-transformed for
      all
      records affected by changed emendation rules, so we may want to
      wait to
      apply them until we pick up the other changes that also require
      search_records to be updated (wildcard, etc.).
      
      
      
      On Wed, Feb 10, 2016 at 11:25 AM, sean-wood
      <notifications@github.com>
      wrote:
      
      > Assigned #516
      <https://github.com/FreeUKGen/MyopicVicar/issues/516> to
      > @dougkdev <https://github.com/dougkdev>.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/516#event-546176715>.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment]
Hi Eric,

Isn't this about search, rather than display. So the transcriber sees (and
types) Alex.  But the searcher types 'Alexandria' and the computer goes
'ok, I will give results for Alexandria, but also Alex-if-female'.   When
we have additional notes, for very 'odd' abbreviations where the researcher
might not understand that the result relates to her or his search, we might
auto-add a note that says 'Mt is an abbreviation for Margaret - other
abbreviations include Polly, Meg, [etc]' as someone searching for Polly
might not understand why Mt is returned.

Cheers,

Pat

On 25 February 2016 at 07:43, Eric Dickens <notifications@github.com> wrote:

>
>
>
>
>
> Hi Doug,
>
> I would like "some other way".
>
> Perhaps we should add to V1.6 Roadmap the need for extra fields.  We
> need the TWYS field, but also the transcriber's searchable version
> of most fields.  If there is no problem, both fields can be the
> same, but if there are any abbreviations or UCF, then the
> transcriber should enter something in the new field.  Computers
> should not make assumptions.
>
> At the same time we need some extra fields, such as the
> Transcriber's Notes, which are different to any Notes entered in the
> Register.
>
> Eric
>
>
> On 25/02/2016 05:26, dougkdev wrote:
>
> Looking at the list of recommended emendations from
> Eric Booker, which he
> based on the forename analysis done by Ben B. on the FreeReg data,
> I make a
> couple of observations:
> 1) There are several in which the same abbreviation should be
> expanded
> differently based on the gender of the person, such as Alex =>
> Alexander
> (male) / Alexandra (female).
> 2) Quite a few of the "abbreviations" listed for expansion are
> actually UCF
> names.
>
> Regarding observation 1, I have added code to support gender-based
> emendations.
> Regarding observation 2, there is also story #42 (UCF Search
> support), and
> I need to confer with Ben on his plans for handling UCF to
> determine
> whether these UCF names should be added as emendation rules, or
> whether he
> will be handling them some other way.
>
> Also, existing search_records will have to be re-transformed for
> all
> records affected by changed emendation rules, so we may want to
> wait to
> apply them until we pick up the other changes that also require
> search_records to be updated (wildcard, etc.).
>
>
>
> On Wed, Feb 10, 2016 at 11:25 AM, sean-wood
> <notifications@github.com>
> wrote:
>
> > Assigned #516
> <https://github.com/FreeUKGen/MyopicVicar/issues/516> to
> > @dougkdev <https://github.com/dougkdev>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> >
> <https://github.com/FreeUKGen/MyopicVicar/issues/516#event-546176715>.
> >
> —
> Reply to this email directly or view
> it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/MyopicVicar/issues/516#issuecomment-188656991>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
In determining the sex from name, please remember that some first names are " bi-sexual' .
And also that some abbreviations will suffer from the writer not being too literate or the dialect causing the to be spelled incorrectly - so to make a decision on which sex, may not be the wisest move.

**Comment by PatReynolds** [comment]
I think the decision on sex comes from the record: 'Alex daughter of Andrew
and Anne' is female, for example, and will be picked up if someone searches
for Alexandra, or Alex, but not if the search for Alexander.

On 25 February 2016 at 09:29, Sherlock21 <notifications@github.com> wrote:

> In determining the sex from name, please remember that some first names
> are " bi-sexual' .
> And also that some abbreviations will suffer from the writer not being too
> literate or the dialect causing the to be spelled incorrectly - so to make
> a decision on which sex, may not be the wisest move.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/MyopicVicar/issues/516#issuecomment-188689970>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
I agree with Pat's point just above. this is how to respond to a search request.
The action starts with the searcher putting in a first name ( if they wish).
If they use Alex then my view is to return ALL the sex variants  without comment.  but if they put in Lesley then they should just get Les or Lesley regardless of sex implied - even if the recorder spelled it incorrectly and should have recorded the female version Leslie.

Or is the intention to assume the researcher uses the correct spelling for what they want, and we return everything that could conceivably be  that name including all the abbreviations an mis-spellings? - which is very near to Soundex of Fuzzy searching.
So where do we draw the line?
Perhaps reverse our logic and give Fuzzy + Soundex as the standard default, and change our button to pick EXACT spelling.?

**Comment by Sherlock21** [comment]
Yes, Pat,  "sex" would come from the clue: Dau or S etc. But there are a significant few early records where no such clue is given in the original Register - so how does the search code cope with these?

**Comment by PatReynolds** [comment]
I would guess Alexandra serves Alex (f) and Alex (no sex) but not Alex
(m).  Or rather, will do - Doug is working on this at the moment.




On 25 February 2016 at 09:46, Sherlock21 <notifications@github.com> wrote:

> Yes, Pat, "sex" would come from the clue: Dau or S etc. But there are a
> significant few early records where no such clue is given in the original
> Register - so how does the search code cope with these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/MyopicVicar/issues/516#issuecomment-188695247>
> .
>



-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
Hi Pat,

No, my thinking is the other way round so that the researcher does not 
get wrong entries.  For example, if they ask for Alexandra, then they do 
not get the TWYS Alex. when the transcriber could know from other 
sources that it is Alexander.  The search is made first on the 
Transcriber's interpretation, then on the TWYS, as that will have got 
rid of the abbreviations.  With this there is no need for the search to 
do any conversions.

Also, remember that we recommend that if a search does not bring 
results, then the Firstname should be omitted.  Use of the Firstname is 
really just to reduce the number of results, so is not very important in 
the search.

This system needs to apply to Surnames as well.  For example, I know 
that there is a Diggins which should be Dickens.  And there used to be 
people known by their Alias name, so that Smith could have had an alias 
name of Jones.  At present we have to create two records, linked in the 
notes (TWYS notes) as we do not have the means to upload the Transcriber 
Notes yet, even though the field is there.

Regards,

Eric

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
I do agree with EricD that the system is Essential for Surnames.

But I am of open mind on how to primarily handle First names . But the counter to Eric D's point of use surname only at first, will most likely  get one over 250 records, so how does the researcher provide a better spec to fine all the possible "Elizabeth" say? Eliz, Eliza, Ezbth, Elizabth? and no doubt others. So I would like some help in the software to ensure I fined a record if its there -without me having to guess all the possible abbreviations - especially if she is a very common surname in that place.

**Comment by edickens** [comment]
Which is why I suggest a second "Transcriber version" of the name,
    which in your examples would always be "Elizabeth".  We then have a
    TWYS and a searchable version.
    
    E
    
    On 25/02/2016 12:38, Sherlock21 wrote:
    
    
      I do agree with EricD that the system is Essential for
        Surnames.
      But I am of open mind on how to primarily handle First names .
        But the counter to Eric D's point of use surname only at first,
        will most likely get one over 250 records, so how does the
        researcher provide a better spec to fine all the possible
        "Elizabeth" say? Eliz, Eliza, Ezbth, Elizabth? and no doubt
        others. So I would like some help in the software to ensure I
        fined a record if its there -without me having to guess all the
        possible abbreviations - especially if she is a very common
        surname in that place.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dougkdev** [comment]
This particular story deals with given names, not surnames.  As far as I
know this is not related to any system of users creating their own
interpretations of alternate names, this is mainly to handle the shortened
versions of names that happen very frequently in the transcriptions (Wm,
Eliz, Jas, Jos, etc.) and some of the very common variations that people
might not think to search for. Many of those were already added to the
system, but Ben and Eric B. did an analysis of the names used in FreeReg so
we could add those that weren't already in the list.

Pat is correct, this is not about how the name is transcribed or stored in
the transcription.  This is just about alternate versions of the name that
get stored in the search_record, so if somebody searches for alexandra,
their search results include female records transcribed as alex in addition
to alexandra.  (Similarly, if they search for William, they will also get
results for records transcribed as Wm).

By "some other way" I did not mean changing anything that the user sees or
anything the transcriber does, I was only talking about how Ben anticipates
handling UCF searches, whether as part of the search_record, or with
regular expressions in the search, or some other brilliant way that I have
not even considered.  So I just need to check with him before spending time
putting UCF-style names into the current set of emendation rules since I
suspect they would need to be removed later anyway when he does the UCF
story.
