### ISSUE TITLE
Move Detail Column

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#522]

**Comment by Captainkirkdawson** [comment]
Move the detail column to position 1 in the table

**Comment by Sherlock21** [comment]
If this is about the Search Results page layout, the I am strongly not in favour of this change.
In My view, the  present order is the correct order.  One would only go to the detail if the content of cols 1,3, and 5 are interesting. If Col6 drops off the page for tablet & iphone users, then tough!  They can scroll to the right easily enough.

**Comment by Sherlock21** [comment]
A possible solution to Kyran's point would be to split the string in col 5 - so that Placename + church name are string together (as now) on line 1 and move Record source label onto a new line - line2.
OR even: given that Place names are often long, multi word n/ames,  have Place name on line 1 and the church name + Record source on line 2 but not strung together so it wraps if longer than the basic page?

**Comment by PatReynolds** [comment]
Added to intern task list for #394: including repositioning of 'details' to position 1 in the table

**Comment by Gingerygamer** [comment]
Survey conducted of  users and results analyzed.  Users prefer maintaining current organization.
