### ISSUE TITLE
Update rejects because UserID does not exist

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#564]
What happens when the UserID is not in FR2

**Comment by edickens** [comment]
The overnight update reported this...
RReeve does not exit
RReeve does not exit
RReeve does not exit
RReeve does not exit
RReeve does not exit
RReeve does not exit
The problem is that she registered in FR1 at 22.55 and I did not pick it up in time to set her up in FR2 before she uploaded files.  So does she have to edit the files to force the Update to process them, or if she just uploads again will they be accepted and not rejected as "Unchanged"?
The same question could apply to any file reported as "Rejected" or "Not processed", such as ...
HShave STSBUUBU.CSV had been locked by either yourself or the coordinator and is not processed
IvorC	NTHUNKBA.CSVThe Place Unknown is unapproved and rejected at line 14

**Comment by Captainkirkdawson** [comment]
Any file coming from FR1 has to have a userid to store the results into.

**Comment by edickens** [comment]
Yes Kirk.  But if a file has been rejected like this in the overnight update does it have to be edited to force the update and if not will "digest has not changed since last build" come first and the file not be processed again?
I suppose my question is really "What is the sequence of the checks".  Are "No UserID" and "Locked" checked before "Has not changed"?  These two problems are things which need correcting in FR2 to make the file become accepted.

**Comment by Captainkirkdawson** [comment]
The first check is to see that we have somewhere to put the file before we try even looking at its content. Hence the existence of a userid is the first check. After that we check to see if we have a forced processing; (the reprocess action sets this) followed by digest change, more recent file and lastly locked.
Since the update uses a list of changed files from the sync of FR1 with our copy of FR1 to start the update it will not touch the files of such a user unless they have been re-uploaded into FR1. 
This was one of the reasons for developing the collection of Physical Files so we could see such situations and act appropriately.
This problem does not exist when we move to uploads into FR2 since the userid has to exist in the first place to log in to the system.
