### ISSUE TITLE
Reassigning Batches to a different UserID

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#574]
There is a need to reassign batches to a different UserID but there is no formal way to do this.

**Comment by edickens** [comment]
This is perhaps a documentation problem rather than a system change.  But there is a need for Coordinators to move batches between UserIDs.  This is because historically for convenience Coordinators have been keeping files from lapsed transcribers under a single UserID.  Some Coordinators are now separating these out in FR2.  This makes it much easier to handle in FR2 so is a good move.  It lets us add information, such as copyright issues, to these batches.
I have defined this as the process.  Is it correct and is it the best?..
    Download file from FR2 old username.
    Destroy the file on old username in FR2
    Destroy the file in old user name in FR1
    Make any changes needed to file downloaded from FR2 and save.
    Upload to new user ID on FR2.
    Check Processed email in the morning to make sure all is well. 
    If anything goes wrong contact the System Administrator who can recover the file from the FR2 Attic.
If this is acceptable it needs to go in the CCs How To document.  E

**Comment by Captainkirkdawson** [comment]
I totally disagree with this approach. (It will work) It is labour and computer resource intensive. The suggestion makes me shudder. The idea of deleting userids is abhorrent to me. (except those that did not complete registration) We should as a matter of practice always leave files with the originator and never delete their userid.
We deliberately did not make a file move between userids available because we did not want people moving files between userids; essentially because we wanted to keep work with the people who contributed it and not someone else. We provided the coordinators with all of the tools they needed to work with files/batches where they were stored. 
Coding a transfer of files between userids is straight forward. But we did not because we did not want people doing it.
I do see you stating a limited time requirement to enable a clean up of previous bad practice (something I applaud). So we could add that function limited to the data managers to do this on FR2. Justas we have provided other limited access capabilities

**Comment by edickens** [comment]
Hi Kirk,
    I do not want this facility in FR2 as well.  This is just a short
    term tidy up from FR1 and should never happen again.
    CCs do not like this laborious work, so if the Data Manager could do
    it easily with a new Action, then the CC could send EricB a list of
    Filenames with the from and to UserIDs.  They usually have already
    created this list.  Normally it will be from one UserID to many
    others.  But the receiving UserIDs will have to be created, and an
    SC can do this.
    A much simpler and safer method.
    I can't put a time limit on it because there are inactive counties
    which need sorting out and this will only happen when they become
    active as we get data.  E
    
    On 18/09/2015 00:25, Kirk Dawson wrote:
    
    
      I totally disagree with this approach. (It will work) It is
        labour and computer resource intensive. The suggestion makes me
        shudder. The idea of deleting userids is abhorrent to me.
        (except those that did not complete registration) We should as a
        matter of practice always leave files with the originator and
        never delete their userid.
        We deliberately did not make a file move between userids
        available because we did not want people moving files between
        userids; essentially because we wanted to keep work with the
        people who contributed it and not someone else. We provided the
        coordinators with all of the tools they needed to work with
        files/batches where they were stored. 
        Coding a transfer of files between userids is straight forward.
        But we did not because we did not want people doing it.
        I do see you stating a limited time requirement to enable a
        clean up of previous bad practice (something I applaud). So we
        could add that function limited to the data managers to do this
        on FR2. Justas we have provided other limited access
        capabilities
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Same as 566

**Comment by edickens** [comment]
Sean - May Kirk have permission to do this fairly soon?  I have coordinators who are tiding up the entries in FR2 and this will save a lot of time and processing.  I don't mind if it is a System Administrator rather than Data Manager Action as it is more to do with Syndicates and does not change the Data.  Thanks E

**Comment by PatReynolds** [comment]
Coming late into this .... we do need to retain a way of associating the
transcriber with their transcriptions - otherwise, we will no way of
ensuring we know whether the transcriber has signed the Transcriber
Agreement or not. (or do we?)

With best wishes,

Pat

On Sunday, 20 September 2015, Eric Dickens <notifications@github.com> wrote:

> Sean - May Kirk have permission to do this fairly soon? I have
> coordinators who are tiding up the entries in FR2 and this will save a lot
> of time and processing. I don't mind if it is a System Administrator rather
> than Data Manager Action as it is more to do with Syndicates and does not
> change the Data. Thanks E
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeUKGen/MyopicVicar/issues/574#issuecomment-141775479>
> .
>


-- 
*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
This is being done to assist in that.

On your return  we can explain how we know who did what and what a transcriber has agreed
