### ISSUE TITLE
Info does not display well on a phone

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#599]
The info boxes are often clipped and the page always goes to the top having tapped it

**Comment by AlOneill** [comment]
Do we have a way of specifying different display positions (and/or widths) of the info boxes for different screen/window widths?

One setting for all screen/window sizes is probably never gonna work...

**Comment by Captainkirkdawson** [comment]
Yes we do. Can either specify it on a per element test or, as in this case, we are already in a view that is dedicated to mobiles. So we can specify a different a different scheme.

**Comment by Captainkirkdawson** [comment]
They display fine with the phone on its side. The new results layout is actually excellent on its side as well. So maybe we just advise people rather than try to shoe horn it into a narrow display.
What we do have to fix is why it goes to the top of the page after clicking the info button!!

**Comment by dougkdev** [comment]
Jumping to the top of the page is an issue for other layouts, too, we just
don't notice it as much because we are usually already at the top of the
page.  If you reduce the height of your browser window enough that you can
scroll down a bit, then click on the info button, you can see that it jumps
to the top, too.

The reason it jumps to the top is because of the href="#" in the <a> tag.
The browser follows the link to "#" (the top of the page).  This can be
stopped by adding an onclick="return false;" into the <a> tag.  Returning
false will keep it from following the link specified in href.

**Comment by Captainkirkdawson** [comment]
Excellent Doug; works like a charm.
