### ISSUE TITLE
Duplicating files in overnight update

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#621]
Needs a bit more investigation, but EricB and I think files are getting duplicated

**Comment by edickens** [comment]
In this FR overnight update a file was uploaded three times (edited version)...

Started a build at 2015-10-24 02:31:11 +0100with options of add with true search_records, a base directory at /raid/freereg2/users, a change directory at /raid/freereg2/freereg1/users and a file a-9 and a delta process that was run at 24/10/2015 02:31
17	 files selected for processing
nzdarryl	CONLAVBA2.CSV	processed  1021 data lines for location CON, Lanivet, St Nivet, PR, ba;  813 unchanged and 5 removed.  0 header errors and 0 data errors
nzdarryl	CONLAVBA2.CSV	processed  1021 data lines for location CON, Lanivet, St Nivet, PR, ba;  1021 unchanged and 0 removed.  0 header errors and 0 data errors
nzdarryl	CONLAVBA2.CSV	processed  1021 data lines for location CON, Lanivet, St Nivet, PR, ba;  1021 unchanged and 0 removed.  0 header errors and 0 data errors
Created  28769 entries at an average time of 169.77516362466542ms per record at 2015-10-24 03:52:35 +0100

They all would need to be "Replace" as this is obviously not a new file, because the first had 813 unchanged records.  The file listing for this UserID only shows one version with 1021 records, so this update is working.  But what if the first had been a new file?  What if any records had been added (these were corrections).  What if a second update was done on the same new file in the same day?  E

**Comment by Sherlock21** [comment]
I did uploaded a file to rectify missing Marriage dates in dbrogan/STS/ STSWEIMA.csv last night, having deleted the existing version without Marriage dates.
BUT then this morning, I went to recheck and there were 2 copies of the file there!! both with same userid & file name
One was mine  because I put a note in the header : reloaded be Data Manager and the other looked like been uploaded by the user or someone with access to use the userid. I have deleted that one!
But it seems the one I deleted was the product of the overnight F1 > FR update - which i though had now ceased.
The file I uploaded in the ID of dbrogan was not locked as i had expected to would be. so I locked it manually this morning to stop further interference.

**Comment by edickens** [comment]
This file was uploaded from FR1 last night I assume because of the deletion and so replaced as considered missing, or was it the case of the CSV csv?  Perhaps these are not duplicates?  FR1 is case sensitive on filenames and would create duplicates if it was just the case of the CSV...
dbraden	STSWEIMA.CSV	processed  2504 data lines for location STS, West Bromwich, Christ Church, PR, ma;  0 unchanged and 0 removed.  0 header errors and 0 data errors
