### ISSUE TITLE
Add new Surname Fields to BA and BU

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#655]
We have always had problems with parents names and trying to fit them to the existing fields.

**Comment by edickens** [comment]
Sandra and Glen have been having problems with Welsh Patronymic  names.  This is their report...
Glen and I have been going round the twist trying to figure out how best to fit entries with patronymic names etc into the system, and I think we need guidance from you all.

Let me give you an example we are faced with:

Thomas David christening: 05 Jul 1807 parents: David Williams,​ Margt.

Ann David christening: 07 Apr 1805 parents: David Williams,​ Margaret

Margaret David christening: 01 Oct 1809 parents: David Williams,​ Margaret

It is clear that the children here have been given the father's forename to carry as their surname. However on FreeREG we have no way to accurately record this.

We are faced with entering the father's name David Williams, in turn which will show all the children's surname as Williams, or leaving the father's forename out and entering David as the surname, and then adding a note to say David Williams is the father's correct name.

Neither of these solutions is adequate, as the children will not have the correct surname or the father will be missing in searchable records.

So we need a workable solution to this, and to be frank Glen and I cannot come up with a viable solution in the confines of the program as it is.

We also have issue with illegitimate births.

We have records entered like this:

Thomas Williams or Jones  christening: 05 June 1802 Parents: John Williams, Anne Jones

My solution to this would be two entries, with a note in each saying child might be found by the other surname

The patronymics is the biggest issue, and we would be grateful for input, to be able to maintain the integrity of the children's and fathers names.

Whatever we come up with can be entered into the Help guide for future reference.

Thank you
Sandra

So my recommendation is that every Firstname should have its own Surname.  This will mean in many case there will be two fields that are the same, but at least there will be no doubt as to what the person is called.  I would even prefer that a field is not left blank as an assumption that it is the same as the relative.  The past does not need correcting, but we should do this for the future and also include it in WinREG which can duplicate the field to avoid extra typing.  BA and BU are affected.   E

**Comment by Sherlock21** [comment]
Let me ask a fundamental question please:
How are you sure, from the information given here, that the "David" attaching to the child's first name is an attempt to change the child's surname, and not just another first name? notwithstanding that one of the children is a girl so they would be less likely to be given male first names - but the other 2 could be double first names AND if they had been baptised on different occasions, you would not have been able to conclude otherwise would you?

I think its dangerous to do anything which amounts to assuming surname changing is taking place.
And even if its normal practice in Wales to do this, do we allow it there, but not elsewhere?

In WRY/ Dewsbury / All Saints, which I am transcribing at the moment,  I have quite a few baptisms where the child is given as a 2nd first name, a name thats normally a surname. -eg:
23 April 1854 Noah Gledhill bap. son of John and Mary.  Surname Orange.
9 Jul 18854 Joseph Stapleton bap. son of Edwin Stapleton and Mary. Surname: FIRTH
17 May 1854 Reuben Micklethwaite bap. son of George and Emma. Surname: KEMP.
16 Oct 1853 Elizabeth Wood dau. of Richard and Elizabeth. Surname: Cully.

These are from the time when the records are in pre-printed books so that helps know which are first names & which is Surname.

But I have had one Baseborn baptism - cant find at the moment - where the record said something like
5 May 1756 Eliza, dau of John Smith and Mary Green - baseborn.
So what do you put in FR for this one? Not a regular occurrence but in modern times will become very much more regular.

I am thinking: The Child takes the Surname of the Father at all times.

ON the other hand, i think in Quaker records they oft are taken form the Area Meeting book which is written like as minutes of the meeting saying something like;
James Green, some of Thomas and Mary was admitted 3 Dec 1786.

So what do we do with that? Assume GREEN is the PARENT's surname don't we. BUt its not strictly TWYS.

**Comment by Sherlock21** [comment]
There is a similar issue raised today ( 4 Aug 2016) by Jackie James ( SOM) about identifying and finding Base born children.

And another by myself - can't find it now -  of naming and searching to ensure we find  ALL records like this.

**Comment by edickens** [comment]
To clarify?  In BA, if the person is an adult and no parents shown, then the name has to go into Father-surname, even though it might not be the father's surname but the person's married name.
Also, if the father is not known, then no father-surname should be entered, but just the mother-surname.  But it looks odd for the person being baptised not to have their surname clearly identified.
We need a specific field to identify the person's surname.

**Comment by SteveBiggs** [comment]
Yes we should have a baptisee surname field so in a case such as:
James Green, son of Thomas and Mary
Only the child's surname should be entered, neither parent's surnames.
An age field would also be needed in some cases.

**Comment by edickens** [comment]
I've just been converting a BA with god-parents names.  This is the same as witnesses in MA.  They are in the notes now, but not searchable.
Do we need a new story specifically to just list the new fields that we would like?

**Comment by Sherlock21** [comment]
Steve: If the Register shows: James, son of Thomas and Mary Green,  baptised 4 Feb 1806.
Then given this is the only data you have to  transcribe,  you would have 2 totally different Record in fR - one with a child with no surname, and one with  a child with a surname but parents without a surname.

And what would your interpretation produce in the case of:-
James Green, illegit son of Mary.
or even from this original record:-
James, illegit son of Thomas Brown and Mary Smith

THEN: if your suggestion is introduced, what is the proposal for dealing with all the historical Transcriptions?

**Comment by Sherlock21** [comment]
If we are raising topics about new fields, then can we accommodate double barrelled surnames properly? - i.e. all in the Surname field. -but how can the search cope if only one or the other part is entered?

The present guidance notes don't help here.
Similarly, the guidance notes could be improved by spelling out: Surname is the be ONLY the last name in a the list of Father's ( or mother's etc)  names even though it might look like some of the names preceding the ultimate one,  are likely to be multiple surnames in the early time period before the hyphenation was introduced.
 
example attached. The presence of a Hyphen in this one clearly shows we should not split the Anderson off and call it one of the First Names -



![double barrelled surnames](https://user-images.githubusercontent.com/9368704/35298350-ceec2a0c-0079-11e8-8c4f-1cdb5fac0f31.jpg)

**Comment by SteveBiggs** [comment]
In all those cases, you simply TWYS:

James, son of Thomas and Mary Green -> baptisee surname blank, father and
mother surnames = Green
James Green, illegit son of Mary. -> baptisee surname = Green, father and
mother surnames blank
James, illegit son of Thomas Brown and Mary Smith -> baptisee surname
blank, father = Brown and mother = Smith

Historical transcriptions have to stay as they are, unless someone feels
inclined to go through and change them.


Steve


Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
New fields exist as part of flexible csv
