### ISSUE TITLE
Investigate how to update search records

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#659]
Can we update search records selectively when we change the search record creation algorithms or update specific fields.
ie can we avoid a total rebuild of the full search_record collection when only selected documents are affected.

**Comment by benwbrum** [comment]
I'll try to add code to no-op the search record rebuild whenever there are
e.g. no witnesses, or no UCF.  Maybe we'll have you do a code review before
we merge the wildcard branch back into master?

**Comment by Captainkirkdawson** [comment]
I was being more radical. Can we avoid a full rebuild? 
I have significant concerns with a)doing a rebuild and b)deploying a rebuild c)how to deal with changes made to the existing database during a rebuild

**Comment by edickens** [comment]
I too have concerns, although not knowing the technicalities.  I
    think we need to do what the banks do which is to give notice of
    website maintenance and then block all access while the rebuild
    takes place.  E
    
    On 18/11/2015 15:38, Kirk Dawson wrote:
    
    
      I was being more radical. Can we avoid a full rebuild? 
        I have significant concerns with a)doing a rebuild and
        b)deploying a rebuild c)how to deal with changes made to the
        existing database during a rebuild
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
A rebuild will take 5-10 days

**Comment by benwbrum** [comment]
I believe that we can avoid a full rebuild.  So long as the code @dougkdev
and I write on the search engine is backwards compatible (new code still
works on old data), we could update the appropriate records in place
following a methdology similar to the one we used for apply_emendations.

**Comment by Sherlock21** [comment]
Well if you really are sounding out views, her's my thoughts. If you were not, then read no further.

Seems to me that if a rebuild is the best way to get from A to B, then that's what we need to do.
No good having the tail wag the dog.

SO: first: were you thinking os shutting down SEARCH facility as well as Members facilities? Thats the extreme. If you shut the whole site for the 10 days, the word will go out of a major issue - perhaps not the political nor financial ( from the long - Term Advertising consequences)  So copy the database to T3 or somewhere and direct searching to there. That leaves Members. And we can more safely tell them its down for a fortnight. just to save up their actions and don't drop them all in at once when it comes back.

If only shutting down the Member facilities, just  do that bit of the above.

**Comment by Sherlock21** [comment]
Thinking long-term, if Rebuilds re likely to be needed every year or two, then perhaps its time to develop a robust method along Ben's email lines?

**Comment by benwbrum** [comment]
I just realized that I never wrote up the results of my research in December.  Here is the elapsed time of each stage of `search_record` creation:
```
.Phase	User	System	Real
populate_tts	  3.800000   0.040000   3.840000 (  3.854419)
downcase_tts	  0.190000   0.000000   0.190000 (  0.172557)
separate_tts	  0.510000   0.010000   0.520000 (  0.492847)
emend_tts	  0.680000   0.000000   0.680000 (  0.656138)
soundex_tts	  1.230000   0.010000   1.240000 (  1.282967)
date_tts	  0.310000   0.030000   0.340000 (  0.432652)
location_tts	  0.840000   0.030000   0.870000 (  0.909015)
translate_tts	 11.690000   0.180000  11.870000 ( 11.562009)
place_lookup_tts	  3.520000   0.100000   3.620000 (  3.508178)
total_save_tts	 21.000000   0.360000  21.360000 ( 21.962394)

```
(note that `total_save_tts` is a sum of the component parts, plus the actual insertion of the record into the database)

This indicates--contrary to my expectations--that just over half of the time taken to create search records is the effort to "translate" a freereg1_csv_entry.  I'm astonished by this finding, and suggest we create a new story to fix whatever is going on there.  (I suspect that the `yaml` file specifying the mapping is being parsed for each record, but since that system was designed for extensibility to FreeCEN--an extensibility we ended up not needing--it probably just makes sense to ditch it altogether and hard-code the mapping.)

**Comment by Captainkirkdawson** [comment]
Agree on that recommendation for another story to improve the transformation.
That in itself does not explicitly address the matter of implementing selective updates to the search record collection when it is modified.

**Comment by benwbrum** [comment]
Agreed.

Previously we explored using the `dirty?` method on Mongoid to determine
what changed, but discarded that idea when we realized that when the
call-back to create the search record is called, the record has already
been changed, so all attributes are "clean".

Mongoid uses the dirty functions that ActiveModel uses, so I did more
research this morning on ActiveModel's support for tracking changes to
fields.  It turns out that there is a `changes` method which returns dirty
attributes (including the value changes), and--more useful here--a
`previous_changes` method which holds the changes prior to the record's
most recent `save`.

This `previous_changes` looks like exactly what we need, so I suggest we
incorporate that into the rewrite of the translation feature.

See this example for more detail:

```
2.1.2 :005 > e.burial_person_abode='ground'
 => "ground"
2.1.2 :006 > e.changes
 => {"burial_person_abode"=>[nil, "ground"]}
2.1.2 :007 > e.previous_changes
 => {}
2.1.2 :008 > e.save!
 => true
2.1.2 :009 > e.changes
 => {}
2.1.2 :010 > e.previous_changes
 => {"burial_person_abode"=>[nil, "ground"],
"record_digest"=>["jp0DCXWLpETa9ygeOhprww==", "2Wk9et0dR8epQC/BgiTgLg=="],
"u_at"=>[2016-01-13 17:27:24 UTC, 2016-01-13 17:28:49 UTC]}
```
