### ISSUE TITLE
Rewrite unchanged entry test

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#668]

**Comment by edickens** [comment]
Could a Place/Church name only change be identified and then only
    those indexes need changing?  E
    
    On 21/11/2015 18:07, Kirk Dawson wrote:
    
    
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Captainkirkdawson** [comment]
Needs more thought and logic but in principle yes

**Comment by edickens** [comment]
I'm also wondering if we have too many indexes?  Just searchable fields need indexing.  Others can be "sub-indexes".  For example the link between a UserID and a Syndicate very seldom changes, so to find the information to send an email to a SC this link is used, and every field does not need to be linked to the SC, if it is.
And a number of fields can be put together if they are never split up and can be treated as one entity.  For example in BA Register No, gender, abode, occupation, notes, film, image No are only presented to the researcher once the entry is found.  Of course the problem is that we don't know what we might want in the future, such as referencing the Film/Image No to the actual image..
But probably too late to change and it will just make it too complicated.  E

**Comment by Captainkirkdawson** [comment]
Makes little sense; indexes are required for many reasons other than searching. Without them you have to look at every document in the system

**Comment by Captainkirkdawson** [comment]
Deployed
