### ISSUE TITLE
Document "search family members"

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#701]
It appears that the family member option does not always work as anticipated. This was first reported in feedback 229 which we rejected (correctly) but there are a number of example that confirm there is likely an issue.
Baptism example.
Agnes ROODE is not retrieved in Norfolk, Great Yarmouth in 1589
![roode1](https://cloud.githubusercontent.com/assets/2874694/12080339/f5802f2a-b214-11e5-89a6-a29d61cf6b15.JPG)
The entry is retrieved under a primary search for Agnes THORPE
![roode](https://cloud.githubusercontent.com/assets/2874694/12080355/6cde87ec-b215-11e5-8bf0-6324d618319c.JPG)
There are successes so it is not 100% failure
eg Sarah HALSTEED  is found where her primary is Sarah BENNICKS
![halsteed](https://cloud.githubusercontent.com/assets/2874694/12080391/ffbcb99e-b215-11e5-881b-ce7228499711.JPG)

Similar issues exist in burials
Wylliam SMYTHE is found in Norfolk, West Harling in 1582 
![smythe](https://cloud.githubusercontent.com/assets/2874694/12080435/ffc0af9e-b216-11e5-8e5f-9b511d2f4e14.JPG)
but not under the secondary as Wylliam THORPE the relative name 

similarly Ane LOVELL is not foud in Norfolk West Harling in  throught the relative name 
![lovell](https://cloud.githubusercontent.com/assets/2874694/12080456/ceabb2a4-b217-11e5-934b-a23971072b98.JPG)

but is in the primary Ane BENSTED
![bensted](https://cloud.githubusercontent.com/assets/2874694/12080459/dc837448-b217-11e5-826c-e4e9116a58e2.JPG)

**Comment by benwbrum** [comment]
In the first example, Agnes ROODE does not exist in the entry being searched for, which contains Agnes THORPE, daughter of Elizabeth ROODE.  I gather that FreeREG1 tried all possible name combinations in the record, but F2 tries to match forename-surname pairs for the same person.

I also don't see an Ane LOVELL in the last entry -- Ane Bensted is daughter-in-law of Thomas LOVELL, so should not appear in a search for Ane LOVELL.

I need to do more research on the middle examples you gave -- unfortunately I'm a bit rushed at the moment.

**Comment by Captainkirkdawson** [comment]
But should it not if one selects the Family Member? If not what does the Family Members option actually do in a baptism?.
Or you are saying that what the Family Member does is search for a mother whose name was Agnes ROODE .
And why did we say that in response to 229 that to get a maternal match we use the Family Member? Clearly we do not.
Agnes THORPE's baptism is retrieved by a family search for ROODE without a forename. So the way our search appears to work one must NOT enter a forename to get a maternal offspring. This is not an intuitive performance and really needs a clear explanation . Perhaps we need to consider a different search option that resembles the FR1 performance

**Comment by benwbrum** [comment]
I think that there are two issues at play here -- how we populate the surname of a baptizee, and how we search for family members.  Both appear to be working as I designed them, but that doesn't mean that they're working correctly!

Here is the `search_record` in question:
```
{"_id"=>"5659075cf493fdc41401045e",
 "transcript_dates"=>["24 Aug 1593"],
 "search_dates"=>["1593-08-24"],
 "location_names"=>["Great Yarmouth (St Nicholas)", " [Parish Register]"],
 "search_soundex"=>
  [{"first_name"=>"A252", "last_name"=>"T610", "type"=>"p"},
   {"first_name"=>"W450", "last_name"=>"T610", "type"=>"f"},
   {"first_name"=>"E421", "last_name"=>"R300", "type"=>"f"}],
 "record_type"=>"ba",
 "chapman_code"=>"NFK",
 "file_line_number"=>1231,
 "line_id"=>"vk3dwu.NFKGYABA14.CSV.1231",
 "transcript_names"=>
  [{"role"=>"ba",
    "type"=>"primary",
    "first_name"=>"Agnes",
    "last_name"=>"THORPE"},
   {"role"=>"f",
    "type"=>"other",
    "first_name"=>"Wyllyam",
    "last_name"=>"THORPE"},
   {"role"=>"m",
    "type"=>"other",
    "first_name"=>"Elizabethe",
    "last_name"=>"ROODE"}],
 "freereg1_csv_entry_id"=>"5659075cf493fdc41401045d",
 "place_id"=>"53cd4970eca9ebee4f007099",
 "search_names"=>
  [{"_id"=>"5659075cf493fdc41401045f",
    "first_name"=>"agnes",
    "last_name"=>"thorpe",
    "origin"=>"transcript",
    "type"=>"p"},
   {"_id"=>"5659075cf493fdc414010460",
    "first_name"=>"wyllyam",
    "last_name"=>"thorpe",
    "origin"=>"transcript",
    "type"=>"f"},
   {"_id"=>"5659075cf493fdc414010461",
    "first_name"=>"elizabethe",
    "last_name"=>"roode",
    "origin"=>"transcript",
    "type"=>"f"}]}
```
and here is the `freereg1_csv_entry` it was created from:
```
{"_id"=>"5659075cf493fdc41401045d",
 "error_flag"=>"false",
 "line_id"=>"vk3dwu.NFKGYABA14.CSV.1231",
 "file_line_number"=>1231,
 "register_entry_number"=>nil,
 "birth_date"=>nil,
 "year"=>"1593",
 "baptism_date"=>"24 Aug 1593",
 "person_forename"=>"Agnes",
 "person_sex"=>"F",
 "father_forename"=>"Wyllyam",
 "mother_forename"=>"Elizabethe",
 "father_surname"=>"THORPE",
 "mother_surname"=>"ROODE",
 "person_abode"=>nil,
 "father_occupation"=>nil,
 "notes"=>"Base born",
 "film"=>"4033324",
 "film_number"=>"00718",
 "county"=>"NFK",
 "place"=>"Great Yarmouth",
 "church_name"=>"St Nicholas",
 "register_type"=>"PR",
 "record_type"=>"ba",
 "freereg1_csv_file_id"=>"565906c3f493fdc41400ec35",
 "record_digest"=>"fMWl1SIS66x/oyl9/nWyGg==",
 "u_at"=>2015-11-28 01:46:04 UTC,
 "c_at"=>2015-11-28 01:46:04 UTC}
```

When we created a baptizee surname for the search record, we looked first for a `father_surname`, and found `"THORPE"`.  Since that was non-nil, we didn't have to fall back to `mother_surname`, and created a search record for whom the participant (baptizee in this case) was Agnes Thorpe.

The additional family member population algorithm for baptism search_records is straight forward -- create a name constructed from `father_forename + father_surname` and another constructed from `mother_forename + mother_surname` (although it is more complicated when `mother_surname` is blank).

As a result, the `search_record` contains three people: Agnes Thorpe (the primary participant), Wyllyam Thorpe (a family member), and Elizabethe Roode (another family member).  A search for _Agnes Thorpe_ should find this record whether _include family members_ is checked or not.  Searches for _Willyam Thorpe_ or _Elizabethe Roode_ should find this record *if* _include family members_ is checked.  Searches for _Willyam_ alone, _Elizabethe_ alone, _Thorpe_ alone, or _Roode_ alone should find the record if _include family members_ is checked, while only a search on _Thorpe_ alone will find the record if _include family members_ is not checked.

A search for _Agnes Roode_ will not ever find this record--regardless of the _family member_ checkbox--since no person named _Agnes Roode_ exists in the record.  That may be unexpected -- should we expand search names for baptizees to include `person_forename + mother_surname` combinations, even though those are likely to produce a lot of false positives?

**Comment by benwbrum** [comment]
Regarding https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/229 it seems that the user was searching by maternal surname (_Salmon_) and not checking the _include family members_ box.  A search for _Salmon_ naturally doesn't return someone with the surname _Manship_.  

The _freereg1_csv_entry_ in that case was this:
```
{"_id"=>"5463a6d9e937904abbcb4246",
 "error_flag"=>"false",
 "line_id"=>"Sueseaman1.NFKGYABA3.CSV.663",
 "file_line_number"=>663,
 "register_entry_number"=>nil,
 "birth_date"=>"15 Jan 1810",
 "baptism_date"=>"18 Jan 1810",
 "year"=>"1810",
 "person_forename"=>"Susanna",
 "person_sex"=>"F",
 "father_forename"=>"John",
 "mother_forename"=>"Sarah",
 "father_surname"=>"MANSHIP",
 "mother_surname"=>"SALMON",
 "person_abode"=>nil,
 "father_occupation"=>nil,
 "notes"=>"Private",
 "county"=>"NFK",
 "place"=>"Great Yarmouth",
 "church_name"=>"St Nicholas",
 "register_type"=>" ",
 "record_type"=>"ba",
 "freereg1_csv_file_id"=>"5463a6d8e937904abbcb3a83",
 "u_at"=>2015-05-28 17:55:15 UTC,
 "c_at"=>2014-11-12 18:28:41 UTC,
 "multiple_witnesses"=>
  [{"_id"=>"5463a6d9e937904abbcb4247",
    "witness_forename"=>nil,
    "witness_surname"=>nil},
   {"_id"=>"5463a6d9e937904abbcb4248",
    "witness_forename"=>nil,
    "witness_surname"=>nil}],
 "record_digest"=>"1t8C3FKa/+TbV7yQFCmArA=="}
```
and the `search_record` generated from it was this:
```
{"_id"=>"5510801ee93790ccb62a5735",
 "transcript_dates"=>["18 Jan 1810", "15 Jan 1810"],
 "search_dates"=>["1810-01-18", "1810-01-15"],
 "location_names"=>["Great Yarmouth (St Nicholas)", "[Unspecified]"],
 "search_soundex"=>
  [{"first_name"=>"S250", "last_name"=>"M521", "type"=>"p"},
   {"first_name"=>"J500", "last_name"=>"M521", "type"=>"f"},
   {"first_name"=>"S600", "last_name"=>"S455", "type"=>"f"}],
 "record_type"=>"ba",
 "chapman_code"=>"NFK",
 "file_line_number"=>663,
 "line_id"=>"Sueseaman1.NFKGYABA3.CSV.663",
 "transcript_names"=>
  [{"role"=>"ba",
    "type"=>"primary",
    "first_name"=>"Susanna",
    "last_name"=>"MANSHIP"},
   {"role"=>"f",
    "type"=>"other",
    "first_name"=>"John",
    "last_name"=>"MANSHIP"},
   {"role"=>"m",
    "type"=>"other",
    "first_name"=>"Sarah",
    "last_name"=>"SALMON"}],
 "freereg1_csv_entry_id"=>"5463a6d9e937904abbcb4246",
 "place_id"=>"53cd4970eca9ebee4f007099",
 "search_names"=>
  [{"_id"=>"5510801ee93790ccb62a5736",
    "first_name"=>"susanna",
    "last_name"=>"manship",
    "origin"=>"transcript",
    "type"=>"p"},
   {"_id"=>"5510801ee93790ccb62a5737",
    "first_name"=>"john",
    "last_name"=>"manship",
    "origin"=>"transcript",
    "type"=>"f"},
   {"_id"=>"5510801ee93790ccb62a5738",
    "first_name"=>"sarah",
    "last_name"=>"salmon",
    "origin"=>"transcript",
    "type"=>"f"},
   {"_id"=>"561f7f2af493fdc89503681f",
    "first_name"=>"susan",
    "last_name"=>"manship",
    "origin"=>"e",
    "type"=>"p"}]}
```

**Comment by benwbrum** [comment]
I just double-checked, and Agnes THORPE is returned if the user searches for Elizabeth_e_ ROODE
![screenshot from 2016-01-03 20 08 38](https://cloud.githubusercontent.com/assets/199961/12082284/e353d7de-b255-11e5-9c8b-99cdbcff9300.png)

**Comment by Sherlock21** [comment]
regardless of what F1 did, we should keep pairs together - and only match as pairs.
In the case of Baptisms, the first try should be baptised  + Father's surname if present. If father's surname not present then on Mother Surname (if Present) and if neither is present you cannot do it.
This is how the data is transcribed so that's the assumption to make and you can;t try and taake any notice of theNotes which may tell a different story.

**Comment by PatReynolds** [comment]
Perhaps something for the Intern to explore (may need two interns at this rate!) - would users be confused if a firstname-Mother'smaiden-name was returned?  If I knew (or suspected that an ancestor went by their mother's maiden name (e.g. after a separation or divorce) how would I search for that person, if I didn't know the mother's first name?

**Comment by Sherlock21** [comment]
I am thinking that these occasions where one would actually find the family of divorced people as Pat suggests, is a lot less than the "normal' case. And thus would cause more confusion than it would help. so I think you need to give the precise wording of how these will be labelled given that the user will get our standard output at that time of seeing result, rather than seeing the whole record first, where it may be more obvious what is happening.

**Comment by Captainkirkdawson** [comment]
Clarification required, 
William baptised son of William Cranness and Elizabeth Culpitt is retrieved by a search for William Cranness and Elizabeth Culpitt if the family search option is added. Which is what would be expected based on my new understanding. It is not retrieved in a family search for Elizabeth Cranness, Again as expected,
Thomas Culpitt buried son of William Culpitt is retrieved by a search for Thomas Culpitt and a family option search for William Culpitt. As expected.
What is the expectation for how the search will handle the following. 
William baptised son of Daniel and Ann Cranness. Is retrieved by William Cranness search and a family search for Daniel Craness. Would we expect a search under the name Ann Cranness to retrieve that baptism with a family search option? It does.
However Samuel Culpitt son of William is only retrieved by a search for Samuel Culpitt. It is not retrieved in a search for William Culpitt using the family option. This appears to be inconsistent with the baptism experience. There the family name seems to be picked up when the mothers surname is not entered. In a burial the persons surname is not used if the relative surname is not entered
The marriage results work as expected using father names.
These are Norfolk, Wymondham records between 1750 and 1820

**Comment by edickens** [comment]
If you have to create extra fields to handle these searches, please
    get back to me first.  In BA and BU we do not have matching Surnames
    for every Firstname.  We have been asked for this so that there can
    be no confusion over which surname matches which firstname.  E
    
    On 14/01/2016 05:49, Kirk Dawson wrote:
    
    
      This appears to be inconsistent with the baptism experience.
        There the family name seems to be picked up when the mothers
        surname is not entered. In a burial the persons surname is not
        used if the relative surname is not entered
        These are Norfolk, Wymondham records between 1750 and 1820
      —
        Reply to this email directly or view
          it on GitHub.
