### ISSUE TITLE
Unprocessed files sort issue

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#729]
Start by asking Eric Booker for more info and reviewing email from Eric B to Ben B.

**Comment by dougkdev** [comment]
The unprocessed files list was sorted by the userid, then by upload date
(the "loaded into FR2" column).  Note that due to mongo not supporting
case-insensitive indexes/sort, the userid sort order is case-sensitive with
all capitals considered to be before any lower-case letters.  So for
example, "CZ" is considered to be before "Ca", and "Ca" before "aa".  I
suspect that is what is causing people to assume the list isn't sorted.

I have changed the code to sort the list in memory instead of by mongo, so
it is now sorted as most people expect (sort order not affected by
capitalization). Fix is on test3.




On Wed, Feb 10, 2016 at 11:21 AM, Ben W. Brumfield <notifications@github.com
