### ISSUE TITLE
Active marker(s) to indicate more than just Yes/No

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#739]

**Comment by edickens** [comment]
The new transcriber agreement will be introduced in due course, but who to?  We have a Marker for Active = Yes/No.  But some transcribers are Inactive because they have taken a break, whereas some are Inactive because they no longer want anything to do with FR, and some have died but we still have their transcriptions.
So the Active marker needs to say Active/Inactive/No contact.  I am not sure if there are other indications needed.  For example some UserIDs are under the control of the SC so that they can save transcriptions donated to us.  I see these as "No contact".
When this change to the marker is done, then the time will come when the new Agreement needs to be accepted.  All UserIDs that are Active or Inactive will need to accept the Agreement or not be given access, or limited access depending on the final format of the agreement.  Those with No contact will not be able to log in, but the SC will have access.  E

**Comment by PatReynolds** [comment]
Hi Eric,

Transcriber agreement / open data is not relayed to activity status.

I would like to see "deceased" added to activity status.

Best wishes,

Pat

**Comment by dougkdev** [comment]
In addition to adding the new status values, also requires updating all existing user records in the database and changing all code that currently interpret the Active field as a true/false value.

**Comment by dougkdev** [comment]
I need a little clarification on this story.  There is already a "Reason
for making inactive" field that is supposed to be filled in when a user is
marked as inactive.  What is the functional difference between a user who
has a status of "deceased" (the new status to be added in this story) and a
user who is inactive with the reason being "deceased"?

It is unclear to me how the code should be treating someone who is deceased
differently than someone who has been marked inactive for another reason
(whether temporarily or permanently).  Unless there is some difference
between the two, we would be adding complexity to the code in every place
that a user's status is checked if we change the status from a true/false
value to a set of possible status values that mean the same thing as the
status combined with the reason field.

**Comment by edickens** [comment]
Hi Doug,
    
    Pat can confirm, but the reason for having the change is that we may
    need to email "Inactive" UserIDs, for example to promote what we are
    doing and try to get them active again, but we do not want to email
    those who are deceased.  So either the Active/Inactive needs to be
    Active/Inactive/Deceased, or we need a new marker which will say why
    someone is Inactive as a pick list and not just text.  This might
    get over the problem of having to change the coding elsewhere which
    is using Active/Inactive, for example, for blocking log in.
    
    EricD
    
    On 19/03/2016 22:52, dougkdev wrote:
    
    I need a little clarification on this story. There is
      already a "Reason
      for making inactive" field that is supposed to be filled in when a
      user is
      marked as inactive. What is the functional difference between a
      user who
      has a status of "deceased" (the new status to be added in this
      story) and a
      user who is inactive with the reason being "deceased"?
      
      It is unclear to me how the code should be treating someone who is
      deceased
      differently than someone who has been marked inactive for another
      reason
      (whether temporarily or permanently). Unless there is some
      difference
      between the two, we would be adding complexity to the code in
      every place
      that a user's status is checked if we change the status from a
      true/false
      value to a set of possible status values that mean the same thing
      as the
      status combined with the reason field.
      
      On Thu, Feb 25, 2016 at 11:07 AM, sean-wood
      <notifications@github.com>
      wrote:
      
      > Assigned #739
      <https://github.com/FreeUKGen/MyopicVicar/issues/739> to
      > @dougkdev <https://github.com/dougkdev>.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
<https://github.com/FreeUKGen/MyopicVicar/issues/739#event-566056255>.
      >
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by dougkdev** [comment]
Thanks, EricD.  Adding "No contact" as you first suggested seems to be the
most representative of what you want.  We could change it to a pick-list to
incorporate both the status and no-contact into the same field, but having
a separate tick box may allow flexibility in some situations.  For example,
someone who is not dead and hasn't asked for no future contact, but who has
an out-of-date email address that is bouncing.  The user could be marked as
"no contact" with an explanation in the reason field until contact is
re-established, at which point they could be made active again.

I'm attaching a screenshot of what I propose and am CC'ing you, Pat, and
Kirk directly in case the attachment doesn't go through to github.

**Comment by PatReynolds** [comment]
Looking at this from the perspective of (putative) rights management:
There is no 'no contact'.
There is 'deceased' which also needs the name and email address of the heir..
There is 'active' (which in the consultation document was defined as
'substantial contribution in the last year'), which has been challenged in
the first phase of consultation, and may be revised (or at least
'substantial' more closely defined). The Trustees are considering this -
but it is likely that it will not exactly coincide with the use which
'active' has (and needs?) within FreeREG.  It might even be 'not deceased'.

Within FreeREG, rather than 'no contact', there needs to be a series of
self-managed opt-ins for the various communications possible (e.g.
newsletters, forums).

Best wishes,

Pat





*- -*

*Dr Pat Reynolds*
Executive Director
Free UK Genealogy  <http://www.freeukgenealogy.org.uk/>
A charity registered in England and Wales, number 1096940.  VAT
registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
We also need to trap and record bouncing messages so that the SC knows 
why they are not getting a reply.  E

_____________________________________
Eric J Dickens
FreeREG Chairman

**Comment by dougkdev** [comment]
edickens responded directly to me and his response did not make it into this thread, copying it below:

You have given a number of reasons why someone should not be contacted.  I would prefer a pick list so that the marker is standardised.  A SC can then have a report by type of "No contact" reason.  Also, when someone is sending an email, they can be presented with the pick list and by using Ctl+Click can select all those reasons that they do wish to include.  Emailing will most likely be a SysAdmin action, although SCs will want to email their transcribers, and perhaps past but inactive transcribers so will need to be excluded from some reasons.

The pick list needs to be easily amended to add other reasons, particularly when we start to use it.

**Comment by dougkdev** [comment]
I looked through the current reasons people are inactive and used that to create a list of standardized reasons.  The text reason field can still be used to add additional comment or detail.  I have added story #761 to address using the pick-list for allowing messages to inactive users based on the standardized list of reasons.
