### ISSUE TITLE
Fix files post new processor

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#790]
On deployment the file processor created 1) incomplete files (location and search record issues) 2) after correction LDS indicator and upload date were incorrectly set (does not affect searchability)

**Comment by Captainkirkdawson** [comment]
Have determined that we need to fix 111 files for and 114,112 entries for  1) and 134 files and 132354 entries for 2). 
All records and indexes will have to be processed for 1) Only file index will be processed for 2)
Estimated processing time for 1) is 6 hrs and 2 hrs for 2)

**Comment by Captainkirkdawson** [comment]
Code is ready and 779 has been fixed by Doug. We are ready to go as soon as the word is given.

**Comment by edickens** [comment]
I don't know if it is significant, or even relevant, but over the past month or more there have been quite a few nights when the number of entries added has been negative.  I have always thought that this was because CCs have been removing duplicate files.  But since we have had the new File upload processor this has not happened.  Perhaps it is coincidence, or does it mean that for some time files have been deleted and the replaced file not added properly to the database?  I can  ask CCs if they have stopped deleting duplicates.
I've added this to this story as it could be another source of incomplete files.    E

**Comment by Captainkirkdawson** [comment]
Eric

Please do not confuse this issue with other undocumented possible issues. This leads to issue creep.
This issue is specific to the implementation of the New Processor and the known problems with that implementation.

The negative occurs because transcribers or coordinators have deleted files for reasons best known to themselves and they have not uploaded a replacement file. Why they do this is beyond me although some do it to "move" the file from one userid to another which is totally unnecessary as you can do that in 30 seconds . Our Help advises against this but they continue to do it. The only valid reason for the deletion of a file is that the file is a duplicate.
