### ISSUE TITLE
Undefined method `each_index' for nil:NilClass

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#821]
[See this exception on Errbit](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/574c874ce937908c74000000)

**Comment by dougkdev** [comment]
This happened when the contents of the register were viewed after starting processing the files for that register, but while they were still being processed.  The date ranges were nil because they were not yet computed, causing the error on the each_index.  Added a check for nil.

**Comment by edickens** [comment]
Do we need a "Please wait" and spinning wheel while ASAP
    processing?  (I do realise that this could last for some time.)  Or
    was this a different person viewing the contents?  I would suspect
    it was the transcriber looking for the result of their work before
    the processing was complete.  They look for errors.  E
    
      On 08/06/2016 02:04, dougkdev wrote:
    
    
      This happened when the contents of the register were viewed
        after starting processing the files for that register, but while
        they were still being processed. The date ranges were nil
        because they were not yet computed, causing the error on the
        each_index. Added a check for nil.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by dougkdev** [comment]
Yes, it was the submitter looking for the result.  The user submitted three
files for processing at 18:30, 18:31, and 18:31.  The error happened at
18:33 when the same user checked the contents of that register.  The files
completed processing at 18:34, 18:35, and 18:35.

The processing happens in the background while the user continues to do
other things, so a spinning wheel probably wouldn't be appropriate.
However, a message on the register page that files are being processed for
that register may be useful if this is a pretty common use case.  We would
need a waffle story for that and a determination of its priority and size.

**Comment by Sherlock21** [comment]
Might it have been me, looking for the file on the occasions that I did not get the system email for over an hour?

I later did get the email, which showed the job ran withing a minute of upload - but it was the delay in email transit 

In which caseI agree with Eric D about putting up a “still processing” token

eric b

**Comment by edickens** [comment]
Doug.  This is a better solution.  A message to say that the batch is 
being processed and so is not accessible would be sufficient.  It 
actually has another benefit in that it confirms that processing is 
working (a file with place/church error would mean that processing was 
not working) and it would show when processing finishes.  The 
transcriber also does not need to keep checking their emails to see if 
processing has finished and if there are errors,  They can just refresh 
the screen with their list of batches.  If this is implemented, then I 
would also like the limit for ASAP processing to be increased and so 
reduce the need to wait for overnight processing.  Quite a lot of what 
is being done is to split up files into smaller batches so that ASAP 
processing can take place.  New transcriptions are not a problem as 
people know to keep the batch small and WinReg warns the transcriber 
when the batch gets too large.  I don't see this as urgent.  It is V1.6.  E

**Comment by dougkdev** [comment]
User was jmh with files ESSMAN[BA/BU/MA].CSV

This story was to fix the bug -- the crash and error message when this
particular circumstance happened.  I agree that a processing message on the
content register page seems beneficial.  That would be a new feature that
likely involves checking the files to see if they are being processed and
adding the plumbing to display the message on the page. I've added a new
waffle story (#831) "Processing message for registers" with the request for
that feature so it can be reviewed and assigned a priority.  I tentatively
put it as 1.6 Transcriber enhancement.

**Comment by Sherlock21** [comment]
Ah well,  that was not me then!!

eb
