### ISSUE TITLE
Asset Pipeline Setup

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#856]
Assets are application specific and need to be loaded for that application.

**Comment by Captainkirkdawson** [comment]
Will review once we have asset pipeline

**Comment by Captainkirkdawson** [comment]
The theme and styling provided by the consultants does not permit use of the asset pipeline without major intervention. The use of grunticon to create icons on application load is one example of the issues. Similarly the palm.min.css does not use the font_path to load fonts. I am not willing to undertake such modifications with my level of knowledge. Hence the setup I have adopted applies a manual introduction of the fonts into public/assets as well as a precompilation of the other assets for production purposes.

**Comment by Captainkirkdawson** [comment]
This is related to #895

**Comment by benwbrum** [comment]
We should bring @dougkdev in on this.

**Comment by Captainkirkdawson** [comment]
Doug was added at the last scrum.

**Comment by dougkdev** [comment]
I guess I'm not clear on what is still to be done on this story.  I don't see any difference between the cookie notice on test3 and the cookie notice on production.  Are they both incorrect and need fixing, or is this no longer an issue?  Also, #895 doesn't mention specifics on what GETs are failing, so I'm not sure what to be investigating here.  I've added the "needs info" tag-- lets discuss this in the scrum later today.

**Comment by Captainkirkdawson** [comment]
The issue is not the cookies but

The theme and styling provided by the consultants does not permit use of the asset pipeline without major intervention. The use of grunticon to create icons on application load is one example of the issues. Similarly the palm.min.css does not use the font_path to load fonts. I am not willing to undertake such modifications with my level of knowledge. Hence the setup I have adopted applies a manual introduction of the fonts into public/assets as well as a precompilation of the other assets for production purposes.

**Comment by dougkdev** [comment]
Some additional discussion about the assets setup.

*Background:*
When I first joined the project we looked into whether it was worth
incorporating bower, etc. (the tools used by the front-end consultant who
designed the assets and stylesheets) into our rails build process.  At the
time, we all decided that it would just be extra work and extra points of
potential failure, without any added value since we wouldn't really be
changing the assets that had already been delivered.  It made more sense to
just copy the delivered assets into the rails project and be done with it.

Since each application (reg/cen/bmd) has a different set of assets that
mostly all have the same names across projects, it was not practical to
just put them all in the /public and /assets directories like one would
normally do in a rails project.

In the freecen_parsing branch, I created parallel directories of assets for
each application in app/assets_freebmd, app/assets_freecen, and
app/assets_freereg.  I also created a rake task to copy the correct set of
assets into the app/assets/ directory by checking the
MyopicVicar::Application.config.template_set variable to see which
application the rake task was running for.

*Things to consider:*
1) With the completion of the accessibility audit, we may need to make
changes to the styles and assets.  Whether we really want to include bower,
etc. in the actual build/update process, I am not sure, but we probably at
least need to set up the process in a way that we can make necessary
changes to the files and copy them over again.  Also, instead of copying in
and referencing the minified css directly, we should reference the
unminified sources in the code and configure the asset pipeline to do the
minification when assets are precompiled.

2) We have never merged freecen_parsing back into master, but we fairly
regularly merge master into freecen_parsing.  While freecen_parsing is
app-aware, master is not.  All of the changes we are making to the assets
now and also the recent changes that were made (for example 27 July when
assets were moved around and reorganized) are being made in the directories
things get copied into instead of where they are copied from (in the
freecen_parsing branch, that is).  If we set up master in a similar manner
as the freecen_parsing branch, it would be much easier to keep things in
sync between the projects and not clobber or lose changes when merging from
branch to branch.

**Comment by dougkdev** [comment]
Point 2 in my previous comment is not just a concern with assets.  Since
the freecen_parsing branch has some app-specific templates and partials,
and app-specific logic and language, it is common for functionality to
break or revert back to FreeReg-specific functionality every time we merge
master.  Those issues usually do not show up as conflicts in the merge
process, so unless we spend quite a bit of time reviewing all changes, we
tend to miss things every time master is merged in. (In fact I noticed some
a few minutes ago that were missed after the last merge).

I wonder if it is worth setting up a story to discuss a stretegy for
when/if we should merge freecen_parsing back in to master?  Merging back in
would take time and effort from all three of us (Kirk, me, Ben), but it may
be wise to do so at some point.

**Comment by Captainkirkdawson** [comment]
When updating an asset eg freereg_contents.css  coomit and pull
then  f2rake assets:precompile to add the updated asset 
followed by f2rake assets:clean to remove the old outdated version

**Comment by Captainkirkdawson** [comment]
Doug I believe this to be finished. Reopen if you think there remains additional work. We have spun off #943 to deal with the freecen_passing integration

**Comment by Captainkirkdawson** [comment]
This needs review in light of initial and proposed changes to the way in which assets are merged that changes Doug's original process

**Comment by Captainkirkdawson** [comment]
The site specific assets are added to the assets pipeline in the application.rb file. This means a n rake:assets_precompile ensure each application has the assets it needs either from the common assets or the site specific assets. 
Wrote and added an initializer that deletes anything in the public folder as a file.( ie does nothing to the assets which are controlled by the assets precompiler.) It then copies the appropriate files from public_site_specific folder for that application. 
This means that changes must be made to the files in the public_site_specific folder; just like changes to assets must be made in the common app asset folder or in the site specific app assets folder if the change is specific to that one application. 
This gives us control through standard rails pipeline management using precompile and clean as well as the initializer. There is no longer a need to use any special rake task. Works like a charm!!

**Comment by Captainkirkdawson** [comment]
Added to the integrated master branch.

**Comment by Captainkirkdawson** [comment]
Realigned assets between root and modal folders

**Comment by richpomfret** [comment]
Vino to assist Kirk with donate/adblocker detection script which has caused a few issues.
