### ISSUE TITLE
Too many GET failures; needs an update

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#895]
Under the new system we are getting a large number of failures to display a page.
Many failures are a result of crawlers.
Need to update robots txt and to review assets failures

**Comment by Captainkirkdawson** [comment]
This is related to #856

**Comment by Captainkirkdawson** [comment]
Each server is responding to about 250 page requests that do no exist on the servers. The majority are pages associated with FR1

**Comment by Captainkirkdawson** [comment]
Have updated the robots txt. Will review again tomorrow

**Comment by Captainkirkdawson** [comment]
No apparent change. Is this related to

**Comment by Captainkirkdawson** [comment]
Is this related to #856 Features?????

**Comment by dougkdev** [comment]
Many errors are from bots and also some referrals from links on websites
that would have originally pointed to valid FR1 pages, but now that FR2
uses the freereg domain name, those links are broken and they get the
static public/404.html message with red text and a link to the old FR1
website.  Now that refinery isn't handling all requests like it used to
with a nicely-formatted page, I recommend we clean up the message in
public/404.html and add a link to the current search page there so users
arriving via broken links will realize they have the option to go to the
current freereg page instead of just following the link back to the old
site.  Created story #909 to do this.

Looks like we are getting some referrals from http://freereg.rootsweb.com
so if someone has access to those pages the links there at least could be
changed. I am not familiar with the rootsweb pages, and not sure that would
be a development task?

/browserconfig.xml is a file that Internet Explorer and Edge look for for
"pinned" websites (somewhat akin to how browers check for /favicon.ico).
We should probably create a browserconfig.xml file at some point, but I
don't think it is urgent.  Added story #910 to do this.

**Comment by Captainkirkdawson** [comment]
Thanks Doug. Is your bottom line that all page get failures are not a result of FreeREG itself?

**Comment by Captainkirkdawson** [comment]
PS We have no access to the referring pages at rootsweb.com

**Comment by dougkdev** [comment]
My position is not that no GET failures are a result of FreeReg itself, but
that the majority of the ones that we looked on the list of failures from a
single day are not.  There could be others we did not see on that day.

There are still definitely some on the list from that single day that are
caused by FreeReg, mainly related to assets.  For example, in the list you
gave me, there are failures for both /assets/images/apple-touch-icon.png
and /search_queries/57bd...50abf/assets/images/apple-touch-icon.png (as
well as several other similar ones where the
/assets/images/apple-touch-icon.png is added at the end of some other
URL).  I noticed that the the code for apple-touch-icon.png is using the
wrong path (as was favicon.ico), but if you copied those both into both
places it was looking anyway, that should not matter.  Regardless,

We can investigate those weird asset anomalies as part of story 856.

This story seemed more concerned with the fact that we are seeing lots of
404 errors in the log now. If we weren't already seeing all of these 404s,
it is probably because refinery was handling all of the missing pages
before you recently moved it down into the cms directory.  We should expect
to see these 404s because existing external references to pages that are no
longer available (FR1 pages for example) should generate 404s.  Also
requests for bogus pages (the bots looking for wordpress vulnerabilities,
for example) are 404s, too.

**Comment by dougkdev** [comment]
Sorry, accidentally sent while still editing. Was adding "Regardless, that
does not explain why it is looking for assets at the end of other urls." to
the second paragraph.

**Comment by dougkdev** [comment]
The reason for apple-touch-icon at the end of other URLs is because
relative path was used (missing "/" at the beginning of the URL) in
application.html.erb.  Also fixed a couple of other incorrect paths.  Will
push to test3 later tonight (Saturday).

**Comment by dougkdev** [comment]
I followed up by sifting through the 404 errors in another week's worth of
logs looking for additional broken links within FreeReg.  I fixed the
cookie policy link (which was missing the new /cms/ prefix) and added a
minimal browserconfig.xml (#910) because we were still getting 404s for
that.  There are still quite a few asset-related 404s that should go away
when #856 is done.

A significant number of 404s are broken links from other pages, bookmarks,
and search engine bots.  We get lots for FR1 pages (/parishes/... and
/cgi/... and /graphics/... ).

I see some 404s where search engine bots are not finding .css and .js files
from the asset pipeline. I suspect this is because the assets are
precompiled independently on each machine, therefore they have different
digests in the filename (the freereg_content-73c...10c.css file exists on
saki but not on colobus, for example). The bots request the html page that
references the css, which gets returned from one server using the digest
from its asset pipeline, and then the bot makes a request for the css file
(the load balancer might route the request to a different server that
doesn't have the same digest for the css file since the bot probably isn't
paying attention to cookies).

There are a few others that appear to be from within FreeReg, maybe you
have some insight?

  1) /refinery/login (from http://www.freereg.org.uk/cms/refinery/login) --
I don't see why this is happening
  2) /wymiframe (from
http://www.freereg.org.uk/cms/refinery/pages/system-documents/edit and
similar pages being edited)
  3) newrelic-related files /js-agent.newrelic.com/nr-984.min.js and /
bam.nr-data.net (from http://www.freereg.org.uk/")
  4) a handful of uploaded screenshots for contacts. For example:
/uploads/contact/screenshot/57ded47833045b8125912b88/Taswell_Tree__Baptism_1857__John_Taswell_and_William_Taswell__Compton_Dundon.jpg

**Comment by benwbrum** [comment]
The second issue (dealing with `wymiframe` is likely to be the cause of the problem centering refinery editor contents.

**Comment by Captainkirkdawson** [comment]
Unable to create 4) or 1)

**Comment by Captainkirkdawson** [comment]
Lemon reports that he has redirected all page requests for FR1 assets in FR to redirect to the home page.

**Comment by Captainkirkdawson** [comment]
Needs to be reviewed again now that changes have been made

**Comment by Captainkirkdawson** [comment]
We continue to see 100 failures a day/server

**Comment by Captainkirkdawson** [comment]
Issue appears to be resolved
