### ISSUE TITLE
RAP - who and how to approach to get part of the register assigned to them for transcription

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#955]

**Comment by edickens** [comment]
The transcriber should be able to see what is available and select 
accordingly.  But we had a long discussion about this a few years ago, 
and we agreed that the transcriber cannot get those images assigned to 
them without the SCs approval.  So they need to click a button against 
the chosen "register book" to express an interest. This needs to alert 
the SC by email, who can then either (another button?) agree to 
assigning that work, or discuss with the transcriber what they should 
do.  The reason for this is that the Register Book may not have been 
categorised for difficulty, or there is something more urgent, or the 
transcriber is new or slow and only needs part of the register book, in 
which case the SC will divide the Register Book into smaller sections.  
Or something like that because I don't want to prescribe how this should 
be done, but the best programmable and manageable system needs to be 
agreed.  We also need a priority system so that when the transcriber is 
selecting, they can ask to choose from urgent work, which is especially 
needed if we are filling in gaps.  E
