### ISSUE TITLE
RAP - inform the coordinator of the completion of the transcriptions

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#956]

**Comment by edickens** [comment]
I've discussed this with a number of Coordinators and had very positive 
support.

At present the SC gets an email each time the transcriber uploads a 
file.  But they may not have finished what has been assigned to them.  
They are just uploading for validation or to make what they have done 
available to researchers.  SCs tend to ignore these emails.  What they 
want to know is when the assigned images are complete so that they can 
check the work and assign more work.  So a button as part of the 
uploading for the transcriber to say "Finished and sight checked" will 
trigger the email to the SC.  Other emails are not needed.  It is then 
time to remove this assigned work from the RAP (they were "In progress" 
until then).  Or perhaps they stay on the RAP as "Being checked by SC" 
until the SC signs it off as OK.  The batch to have a Coordinators Lock 
applied so that no more changes are made by the transcriber, because the 
transcriber has no more need to work on this batch.  These changes in 
status to be done by just clicking buttons.  At present it involves the 
SC updating spreadsheets on their computer in many different formats.  
It could be so much easier and quicker.  E

**Comment by richpomfret** [comment]
Tied-in with the allocation process.

**Comment by PatReynolds** [comment]
I like the "being checked" notice - helps the researcher to see that things
are progressing.
