### ISSUE TITLE
RAP - to set ownership and any copyright / licencing information for the register

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#957]

**Comment by edickens** [comment]
This needs to be done when the images are uploaded to the images 
server.  But it must also be possible to do this at register book level 
because sometimes the images are not on the images server, for example 
when the transcriber takes their laptop to the Records Office or Church 
and transcribes from the original.  E

**Comment by PatReynolds** [comment]
Issue #518 = will move Eric's comment there.
