### ISSUE TITLE
GAP - A report on the years for which there are no entries

### ISSUE THREAD

**Issue by sean-wood** [FreeUKGen/MyopicVicar#961]

**Comment by edickens** [comment]
Yes.  Or can this be a database which is accessed when someone searches 
for a Place and Dates so that they can get a warning to alert them as to 
why they have not got a result, and particularly to say if they never 
will get a result.  E

**Comment by richpomfret** [comment]
Still requires info/a clear specification.

**Comment by edickens** [comment]
DRAFT
Purpose of this report:-
1. For researchers to know that they will never be able to find an entry because the data does not exist.
2. For Coordinators to know if something has not been transcribed when the year range would indicate that it should have been.

How and where this information is presented is open to discussion.   But my suggestions.
1. This can be included in the Transcription report presented to Researchers.  The information is often available on GENUKI and just needs to be entered as a Place/Church/Register Type/Record Type/Year range.  Once entered it will never change, so is a one off exercise.  This information could also be presented to the researcher if they select a year range for a place which will never have any entries and thus avoid them searching needlessly.
2. This could be part of the RAP report.  Ideally, as well as the RAP showing details of images that have not been started and are in progress, I would like to see an entry in this report if there are no entries uploaded for any year within the year range of the images that have been completely transcribed.  This will mean that the transcriber will need to enter something if there is a gap in the register resulting in a year(s) with no entries.  My reason for this is that work is sometimes spread among a number of transcribers and it is easy for part not to get allocated, or the batch could get deleted, or pages can get missed because they were not photographed, or the transcriber can miss an image, in fact a number of different reasons.  A positive entry is better than just a gap in the year range.
The entries made by the transcriber to say that years have no entries could be presented to the researcher if they select these years.

**Comment by richpomfret** [comment]
Comes later (1.5.8 - to quote Eric).
