### ISSUE TITLE
Review data model for GAP/RAP/DAP

### ISSUE THREAD

**Issue by benwbrum** [FreeUKGen/MyopicVicar#984]
We need to review the data model in pull request #983 for compliance with the use cases described in the google document.

**Comment by Captainkirkdawson** [comment]
There is nothing technically wrong with the proposed code.

However this structure is going to make it difficult for us to manage the work flow.

I would prefer to see a structure that has :

Images belonging to a page. (We should permit multiple images for a page although the norm is just 1)

Pages belong to a source and to an assignment

Gaps belong to a source. There can be many gaps in a source. This will allow us to accumulate at both register and church levels. If required for efficiency purposes they can also belong a  place but we need to keep an eye on the number of indexes being created 

Sources belong to a register. There can be many sources in a register. This means that the mstype in source is not required.

Assignments belong to a userid_detail

If you agree and so wish I can make the required code changes

**Comment by benwbrum** [comment]
For some reason I don't see my comments via email.
I'm modifying the code in the branch as follows:

New `page_image` model which is a child of `source`
New associations on `page`
New `sources` association on `register`

I disagree on moving `mstype` to `register` -- if an `OR` is transcribed as a `BT`, it's still the same `register` but the `source` is different.  I really need to draw up a diagram here to make what I'm thinking clearer, so we can have something to point to and argue about.

Gaps can belong to a source--and I'm adding a `has_many :gaps` to `source` as you suggested--but gaps may be attached to larger units than that, as when record offices or entire county units don't cooperate, or when we haven't surveyed the registers available.  (I may have mis-read your comment as disagreement when it wasn't, in which case, apologies.)

I believe that the commit I'm about to push covers these comments, and--with the exception of `source.mstype`--implements every suggestion.

**Comment by benwbrum** [comment]
I finished the push -- see #983.

**Comment by Captainkirkdawson** [comment]
Ben
One could argue that page and page_image could be combined if there is only one page_image per page. If they are are kept separate do we need the following in page
https://github.com/FreeUKGen/MyopicVicar/blob/20829887eaa4a9d55b96a7372c590a5d01edf92a/app/models/page.rb#L26-L27
My argument for a many relationship is that there could be 2 images made of the same page in the same source. I have seen cases where the LDS photographer did the page twice or sometimes 3 times with different camera settings in order to get a clearer picture. I do not know if our scanner operator does the same.I do not know the practice with digitization in CRO.
page_image should belong to freereg1_csv_entry when transcribed if we are going to show the image and if page_image is the link between the image server and the app
I was not suggesting that mstype be moved to register. I was making the point that the register type already is in register. 
I agree that gaps can exist at multiple levels. That can be perhaps be problematic. Clearly there are gaps in a source so thank you for adding that. But as you say there can be gaps at a church because a complete book has been destroyed or we don't have access Similarly at places where a church was destroyed or there are restrictions. Also we have access to some counties period. But are these the same gaps or are they separate collections eg church_gaps place_gaps county_gaps.

**Comment by benwbrum** [comment]
Overslept this morning so will need another day.  Feel free to add the changes you suggest excepting gaps and sources, which I would like to chew over more.

**Comment by edickens** [comment]
So can a batch belong to a source?  In this way both the images and
    the transcription will be associated with the source.
    
    Quite often there are more than one physical page in an image.  Is
    this worth taking into account?
    
    E
    
      On 21/10/2016 23:46, Kirk Dawson wrote:
    
    
      There is nothing technically wrong with the proposed code.
      However this structure is going to make it difficult for us to
        manage the work flow.
      I would prefer to see a structure that has :
      Images belonging to a page. (We should permit multiple images
        for a page although the norm is just 1)
      Pages belong to a source and to an assignment
      Gaps belong to a source. There can be many gaps in a source.
        This will allow us to accumulate at both register and church
        levels. If required for efficiency purposes they can also belong
        a place but we need to keep an eye on the number of indexes
        being created 
      Sources belong to a register. There can be many sources in a
        register. This means that the mstype in source is not required.
      Assignments belong to a userid_detail
      If you agree and so wish I can make the required code changes
      
      
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #984: There is nothing technically wrong with the proposed code.\n\nHowever this structure is going to make it difficult for us to manage the work flow.\n\nI would prefer to see a structure that has :\n\nImages belonging to a page. (We should permit multiple images for a page although the norm is just 1)\n\nPages belong to a source and to an assignment\n\nGaps belong to a source. There can be many gaps in a source. This will allow us to accumulate at both register and church levels. If required for efficiency purposes they can also belong a  place but we need to keep an eye on the number of indexes being created \n\nSources belong to a register. There can be many sources in a register. This means that the mstype in source is not required.\n\nAssignments belong to a userid_detail\n\nIf you agree and so wish I can make the required code changes"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/984#issuecomment-255482923"}}

**Comment by benwbrum** [comment]
Give my tonight to do another pass, then let's chat again tomorrow.

**Comment by Captainkirkdawson** [comment]
Eric D added following comment in April 2017
I do remember it now, but it has been significantly improved since I read it last. In fact it is word perfect as far as I am concerned and I suggest that it should go into the Transcribers and Coordinators Help pages on the website.

Some very minor suggestions:-

RAP The County Coordinator needs to be able to upload Images, information on which will then appear under R1)
RAP R9) As it is shown, when a transcription is complete it goes on the DAP, as it should, and is no longer on the RAP. But I think it should still be shown on the RAP until the County Coordinator has signed it off as acceptable. If there are a lot of UCF then it should be marked as needing investigation, perhaps a new image needs to be found.
You mention "Coordinator" throughout this report. I think you need to show whether it is the CC or SC. This is because it determines who allocates work to the transcriber and who checks the accuracy.
These reports will need to be selectable by County/Place/Church and perhaps by Transcriber.
I don't know how big the RAP will be. At present not very big. But if we get access to images, it could be very large because we are only, I estimate, about 10% through the work. All the images may not be on our image server, but if we have permission to look at them elsewhere, we need to be able to put an entry in the RAP to say that we have permission and where they can be found.
Many thanks,

Eric
