### ISSUE TITLE
Superscript letters in WinREG WinFreeREG

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#986]

**Comment by edickens** [comment]
From a transcriber:-
Superscript letters - is it possible for these to be accepted so that the transcription more accurately reproduces an entry?

And my suggestion:-
Allow all characters including "ss" §
But how will this affect the Soundex?
E

**Comment by Captainkirkdawson** [comment]
On special characters (e.g. superscript, oe ligature) : Kirk said on #469 "FR2 supports all special characters in the CP1252 character codeset. It uses a conversion of that codeset into Unicode. If there are missing special characters then it is likely caused by WinREG which uses a subset of CP1252 that does not include a number of special characters. It uses iso-8859-1."

So FreeREG2 can cope with all the characters mentioned.

**Comment by Captainkirkdawson** [comment]
Will not happen
