### ISSUE TITLE
Implied cookie consent

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/MyopicVicar#992]
FR uses explicit cookie consent because we cannot function without cookies. BMD uses implied cookie consent but does not require cookies to operate. What is the official position of the Society.

**Comment by Sherlock21** [comment]
I vote for a change over to Implicit Cookie Acceptance as described in the text.

**Comment by Captainkirkdawson** [comment]
Given that we are currently revising the cookie display etc I would like a response from @PatReynolds  rather than reopen again

**Comment by suffolkroots** [comment]
Please could we have implicit acceptance of cookies, to save time and patience through not having to click and wait at each and every logon.

**Comment by Sherlock21** [comment]
I enthusiastically support this request.

**Comment by Sherlock21** [comment]
See my additional comment after yours.
e

**Comment by edickens** [comment]
The reason why you have this problem (which I do not) is because each 
time you leave your web browser you have asked for "Cookies to be 
deleted".  This is generally a good idea, so if you want to keep doing 
this, then you have to look deeper into your web browser and find where 
you can say "Please keep this Cookie".  Then you will not have to accept 
each time.  E

**Comment by suffolkroots** [comment]
Even my bank has implicit consent for cookies. I do not keep any cookies.

**Comment by Captainkirkdawson** [comment]
Implement implied cookie consent,

**Comment by Captainkirkdawson** [comment]
@AlOneill  please review test3
