### ISSUE TITLE
Show files waiting to be processed to the transcriber

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/MyopicVicar#999]

**Comment by edickens** [comment]
(I thought I added a comment to this?  Perhaps it is in #825)
In the List Batches/Files report can unprocessed files be listed?  I know that the place/church cannot be known, so these fields can be blank.   They need to come first.  The option to Delete should be there, but perhaps not Replace.
This will make it easier to sort out #825.
Should this also be done at the same time as the change to the way files are uploaded?  It will help to show that a file has been held for overnight processing or is even in the process of being processed.

**Comment by Captainkirkdawson** [comment]
Cannot do it the way you suggest because as you have noted the file has not been processing. What we can do is provide a link to the display of files waiting to be processed for the user

**Comment by edickens** [comment]
I think I understand.  Your report is listing against certain
    criteria and that would only apply to processed batches.
    
    Yes a link to the Unprocessed would be a good idea, but I think that
    the report buttons should not say "FR2".  Some may ask why.  It is
    just a legacy from the past.  Would it be possible to show how many
    unprocessed there are?  And if zero not show the link?
    
    Thanks E
    
      On 30/10/2016 16:05, Kirk Dawson wrote:
    
    
      Cannot do it the way you suggest because as you have noted the
        file has not been processing. What we can do is provide a link
        to the display of files waiting to be processed for the user
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/MyopicVicar","title":"FreeUKGen/MyopicVicar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/MyopicVicar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #999: Cannot do it the way you suggest because as you have noted the file has not been processing. What we can do is provide a link to the display of files waiting to be processed for the user"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/MyopicVicar/issues/999#issuecomment-257160010"}}}

**Comment by Sherlock21** [comment]
If you are going to list files waiting to be processed, will this include the ones that are in the 900+ collection, with the date from which it was uploaded.?

Or are you discussing something different here?
It might well help prevent the list getting bigger in future if the CC concerned gets a listing of "please sort these out" style

**Comment by Captainkirkdawson** [comment]
This is nothing to do with the 900+ list none of those are waiting. Those need fixing under that story.

I had assumed that is was just a new requirement given the "new" update/replace process

**Comment by Sherlock21** [comment]
Having been out for the afternoon, i have missed much of the too and fro bits. 
Sorry i got the wrong tag.

**Comment by edickens** [comment]
I would have thought that the 900+ would automatically be included as 
they are "Unprocessed" which I had assumed was therefore waiting to be 
processed.  But seeing what EricB has found, I'm inclined to delete this 
lot and let the RAP show up gaps which need to be identified as actual 
gaps or uploads that did not work - when we get there.

The current "Waiting" is still useful as confirmation that the request 
to process has been successful.

E

**Comment by Captainkirkdawson** [comment]
Never make assumptions. The Waiting means exactly that. It has been scheduled for processing and has a date stamp that show when it was submitted for processing. The Files Not Processed means just that. We have apparentlt files that were uploaded/replaced and never processed. The capability to list them is one of the reports that are available to us to monitor that the system is performing as expected. It has shown that users where uploading /replacing and NOT submitting for processing

**Comment by Sherlock21** [comment]
Regarding  almost all of the files listed in this now 910 (for some reason reducing)  were now non existent files in terms of my being able download a copy and have a look, i am totally bemused.

Can we recap please?
Tell me please exactly  what conditions put a file into this category? 
and if it got into the list some time in the past, how does it now get to the state of being Not seeable online?
Not downloadable?

How then, given my success rate of only 1 out of 11 at random behaved like a normal file, - i.e. have a file name and some content even if its empty after the userid/filenmae and header rows, are we to make any headway in determining if they are still needed?

Let alone if we find one that has a userid + Filename +date loaded into FR waiting, but no content, and there is no matching filename in FR - a situation which I have not yet involved CC's in looking for.

instead of me trawling through the 914 list to see if the file is Genuine, ( at 11 an hour would be 9 solid days of excitement), Can we not get a little bit of code to do the lookup for content in the filespace thats listed behind the Not Processed list, to determine if there is any actually data there? i.e. in PC speck for these files with a file size greater than what;s needed for the header alone?

**Comment by Captainkirkdawson** [comment]
The capability already exists. One of the options available on the batches listing is to list waiting files
